### ISSUE TITLE
Migrate custom fields to fields

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/fields#10]
Hello,

When I install Fields I don't find all my custom fields from custom fields plugin.

Thank you for your work

**Comment by orthagh** [comment]
Hello @satyan01, @btry starts a migration script.
It's experimental, but you could find and test it here : https://github.com/pluginsGLPI/customfields/blob/master/scripts/migrate-to-fields.php

Feel free to report any errors here or in customfields repository.

**Comment by satyan01** [comment]
Hello

I have already tested and escalated issue

https://github.com/pluginsGLPI/customfields/issues/81
