### ISSUE TITLE
Import page PHP

### ISSUE THREAD

**Issue by bacus99** [pluginsGLPI/fields#105]
Bonjour,

J'ai créer un tableau permettant de voir les périodes de production critique de mes usines.  Ce tableau est accessible par un lien web https://glpi/prod.php?# de l'entitié.  Le tout basé sur une query MySQL

![image](https://cloud.githubusercontent.com/assets/11425241/21153546/f993b15c-c138-11e6-89f7-367183578274.png)

Voir mon tableau

Je ne sais pas si ceci devrait être adressé directement à l'équipe de GLPI, mais il serait très cool de pouvoir afficher une page web externe dans un nouveau TAB de FIELDS

Un jour je serai surement capable de créer mon propre plugin, mais pour l'instant

Merci

**Comment by trasher** [comment]
Hello,

I'm not sure this is a good idea to load something external; we can't know what we will obtain. Also, I'm not sure it fits this plugins goal.

👎

**Comment by orthagh** [comment]
> I'm not sure this is a good idea to load something external; we can't know what we will obtain. 

It's an admin action and his responsability, not ours.

> Also, I'm not sure it fits this plugins goal.

For this, yes, the feature would fit better in a new plugin (embed).
Redmine has this kind of feature (plugin?). I use it for the phpdoc: https://forge.glpi-project.org/projects/glpi/embedded/index.html

Plugin field tries to provide a way to add new fields to existing itemtypes, so embed external pages seems out of scope.

**Comment by trasher** [comment]
Thansk @orthagh .

@bacus99 so no, we won't do this, you'll have to create a new plugin (or to ask someone to do it for you).
