### ISSUE TITLE
Missing file or useless ajax call

### ISSUE THREAD

**Issue by trasher** [pluginsGLPI/fields#107]
Since https://github.com/pluginsGLPI/fields/commit/2acd3c465303bc820136acc0f21bdf8ec072258a#diff-d98456827cd3db0388884db44e3d5ea5R368

The specified field does not exists (it seems it has never existed before).

**Comment by trasher** [comment]
ping @orthagh

**Comment by trasher** [comment]
I'm not able to get "	Insertion in the form of a specific tab (before save button)" type blocs working; I've never been told to choose any tab.

Maybe this is related.

**Comment by orthagh** [comment]
I think also.

For the file: https://github.com/pluginsGLPI/fields/blob/0.90-1.0/ajax/container_subtype_dropdown.php

**Comment by trasher** [comment]
This one do exists, the missing one is `ajax/container_itemtypes_dropdown.php`.

I do replace `_itemtypes_` with `_subtype_` but this does not work (so I do not know if the .php file is the right one, or if the ajax stuff is wrong).
