### ISSUE TITLE
champ obligatoire interface simplifiée

### ISSUE THREAD

**Issue by romain1206** [pluginsGLPI/fields#109]
bonjour,

maintenant que les champs supplémentaires s'affiche bien sur l'interface simplifiée mais j'ai découvert un autre bug

les 2 champs sont en saisie obligatoire et que je complete ou non ces 2  champs ou l'un ou l'autre j'ai ce message d'erreur

http://i.imgur.com/K3eIt81.png

le ticket est bien enregistré mais c'est assez deroutant

**Comment by romain1206** [comment]
j'ai aussi le bug dans l'interface admin

**Comment by trasher** [comment]
En effet... La vérification est lancée deux fois : une première fois, qui fonctionne comme escompté ; et une secode, par effet de bord d'un appel interne du coeur de GLPI.

**Comment by romain1206** [comment]
je viens de tester le commit, plus de messages d'erreurs que je remplisse ou non les champs obligatoires

**Comment by trasher** [comment]
Ça fonctionne en admin ; visiblement pas en self-service...

**Comment by romain1206** [comment]
je confirme je viens de faire le test

**Comment by trasher** [comment]
Je pense qu'il devrait suffire de remplacer `pre_item_add` par `item_add` dans le fichier `setup.php` ; mais à priori le « vrai » problème est côté GLPI (enfin, il y a un comportement qui n'est pas tout à fait cohérent)

**Comment by trasher** [comment]
(voir https://github.com/glpi-project/glpi/issues/1438)

**Comment by trasher** [comment]
Le nouveau commit 732160df871d2d3c3a886b3027ccca4f45563d7b semble fonctionner dans les différents cas de figure.

**Comment by romain1206** [comment]
je viens de tester avec le second commit, le message d'erreur est revenu alors que le champ est rempli

**Comment by trasher** [comment]
Dans quel cas ? quel profil ?

**Comment by romain1206** [comment]
j'ai tester en admin et post_only
j'ai remis une seconde fois les fichiers du second commit au cas ou

**Comment by trasher** [comment]
En post_only c'est bon normalement. En admin, en création de ticket, il y a encore un gap... :(

**Comment by trasher** [comment]
Avec aa8172d1637d46afb0c73459ed62437085b43e9d : l'ajout et la modification, en superadmin ou en postonly ont le comportement attendu.

J'espère qu'il ne reste pas un cas de figure spécifique qui embêterai encore le monde ! ;)

**Comment by trasher** [comment]
(précision : le dernier commit doit remplacer intégralement les autres - attention de ne pas faire de mix)

**Comment by romain1206** [comment]
parfait ca fonctionne, merci pour tout ce boulot.
je suis bien content d'avoir apporter ma pierre au débogage de ce plugin

**Comment by trasher** [comment]
Coool :) Merci pour tes tests et ta patience :)
