### ISSUE TITLE
Fields at the top

### ISSUE THREAD

**Issue by choribull** [pluginsGLPI/fields#11]
I'm checking GLPI 0.90 with field plugin (0.90-1.1) and I have a problem.
When create a new field, in the ticket, the field appear at the top.
The field is "Test:"
![image](https://cloud.githubusercontent.com/assets/15675635/10977214/14cc940c-83f0-11e5-82ea-c2650acb91e6.png)
Another problem is when I create a new ticket, the field not appear.
Can you help me?
Thanks in advance

**Comment by orthagh** [comment]
Fixed in fddf201a3dbe13f496e64a74b574357fc9f30cef
