### ISSUE TITLE
problème création dans fields 1.4.0

### ISSUE THREAD

**Issue by sebfun** [pluginsGLPI/fields#112]
Bonjour

Dans la version 1.4.0 dans GLPI 9.1.1, je n'ai pas le bouton "+" pour pouvoir créer des champs supplémentaires dans le menu Configuration -> Champs supplémentaires -> Blocs.

Le "+" est grisé.
J'ai activé le mode debug il n'y a pas d'erreur

Je suis allé dans le profil correspondant il n'y aucun champ "Field" au niveau des droits
Avez-vous une idée ?

Merci

**Comment by trasher** [comment]
Sounds like a configuration issue more than an issue with the plugin. But I do not know myself what may be wrong.

**Comment by nicolasfo** [comment]
Same problem here.
Any help appreciated.
Thanks

**Comment by trasher** [comment]
It is an ACL issue on your profile.

In Setup > Profiles, select your profile, got to the Setup tab and check is "Update" is check on the "General setup" line.

**Comment by nicolasfo** [comment]
The checkbox is already checked. I uncheck it, save and re-check the box but still not working.
Thanks
Nicolas

**Comment by sebfun** [comment]
Same answer as nicolasfo

**Comment by trasher** [comment]
Did you logout and relogin after you changed the ACLs?

Could you test with a profile with full rights to see if that works? The "Update" ACL do change the behavior, but it may be possible something else (another ACL, another plugin, or else) affects it as well...

**Comment by nicolasfo** [comment]
Yes, I logout/login after made the changes.
I made tests with Embedded glpi user, everything is enabled but no luck.
I also tried to add "plugin_fields"="1" on the "profiles_id"="4" (glpi profile) in the table "glpi_profilerights" in glpi DB but same result
Thanks
Nicolas

**Comment by trasher** [comment]
Would you please try fix provided by @orthagh from #161?

**Comment by trasher** [comment]
Ping?

**Comment by orthagh** [comment]
no answer (and it should work in recent versions), closing
