### ISSUE TITLE
new installation and migration issue

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/fields#115]
Hello

I have to create a glpi test web server, I have installed glpi, copy the actual db.

In fields I have nothing anymore, however, database is correctly filled.

Nothing in dropdown in GLPI and nothing in fields.

Do you have an idea ?

this message in sql log

2016-12-16 10:36:08 [2@UNGSRVGVA218]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_fields_labeltranslations` WHERE plugin_fields_itemtype = \'PluginFieldsContainer\' AND plugin_fields_items_id = 12
  Error: Table 'glpidb91.glpi_plugin_fields_labeltranslations' doesn't exist
  Backtrace :
  inc\commondbtm.class.php:263                       
  plugins\fields\inc\container.class.php:361         CommonDBTM->find()
  inc\commondbtm.class.php:1356                      PluginFieldsContainer->pre_deleteItem()
  plugins\fields\inc\container.class.php:106         CommonDBTM->delete()
  plugins\fields\hook.php:134                        PluginFieldsContainer::uninstall()
  inc\plugin.class.php:639                           plugin_fields_uninstall()
  front\plugin.form.php:49                           Plugin->uninstall()

**Comment by satyan01** [comment]
2016-12-16 15:10:08 [854@UNGSRVGVA218]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_fields_fields` WHERE type = \"dropdown\"
  Error: Table 'glpidb91.glpi_plugin_fields_fields' doesn't exist
  Backtrace :
  inc\commondbtm.class.php:263                       
  plugins\fields\inc\dropdown.class.php:24           CommonDBTM->find()
  plugins\fields\hook.php:48                         PluginFieldsDropdown::install()
  inc\plugin.class.php:664                           plugin_fields_install()
  front\plugin.form.php:49                           Plugin->install()

**Comment by trasher** [comment]
Are you sure you've copied the whole database? Those tables are created on plugin installation/update; if they're missing, you missed tables or plugin has not been installed/updated correctly before.
