### ISSUE TITLE
Custom fields don't display on disposition classic and vertical separation

### ISSUE THREAD

**Issue by Lokydoki** [pluginsGLPI/fields#116]
Hi, 

as title says, custom fields can't be seen when on a different disposition as default left menu disposition. Same thing in simplified ticket creation form.

It appears that ids are different when using differnt dispositon.

I managed to make something work (very dirty) by injecting javascript but it is bound to vertical separation. 

      if ($current_itemtype == 'Ticket')
      {
          //echo "alert('$current_itemtype')"; //YLO debug
          if ($script_name == "helpdesk.public.php") { // si formulaire simplifié rechercher le champs titre et insérer avant
            echo "
            jQuery( document ).ready(function( $ ) {
               //ajout des champs custom juste au dessus de la description du titre
                     jQuery($(\".tab_bg_1:has(td:contains('Titre'))\").closest('tr').before('<tr  class=\"tab_bg_1\"><td colspan=4><div style=\"width:auto;\" id=\"fields_dom_container\"></div></td></tr>'));
                     jQuery('#fields_dom_container').load('../plugins/fields/ajax/load_dom_fields.php', {
                        itemtype: '$current_itemtype',
                        items_id: '$items_id'
                     });

            });
            ";
          } else { //Sinon insérer avant mainformtable4
            echo "
            jQuery( document ).ready(function( $ ) {
                     var custom_div = '<div class=\" tab_cadre_fixe custom_fields \" id=\"fields_dom_container\"></div>';
                     jQuery($('table#mainformtable4>tbody>tr>th:contains(Titre)').parent().parent().parent().before(custom_div));
                     //alert('mainformtable4');
                     jQuery('#fields_dom_container').load('../plugins/fields/ajax/load_dom_fields.php', {
                        itemtype: '$current_itemtype',
                        items_id: '$items_id'
                     });
            });
            ";
          }

      }
      else {

      echo "
      jQuery( document ).ready(function( $ ) {
         jQuery('div.ui-tabs').tabs({
            load: function( event, ui ) {
               jQuery('#page #mainformtable tr').eq($eq) // before last tr
               .before('<tr><td style=\"padding:0\" colspan=\"4\" id=\"fields_dom_container\"></td></tr>');
               jQuery('#fields_dom_container').load('../plugins/fields/ajax/load_dom_fields.php', {
                  itemtype: '$current_itemtype',
                  items_id: '$items_id'
               });
            }
         });

      });
      ";

      }

**Comment by trasher** [comment]
I've fixed that one before seeing you already did... But I've done it PHP side ;)

**Comment by Lokydoki** [comment]
Nice! thank you trasher ! will test this
