### ISSUE TITLE
Could not add blocs or fields

### ISSUE THREAD

**Issue by DjazzLab** [pluginsGLPI/fields#12]
Hi,

I've just installed this great plugin !
But, when I go to "Setup > Additionnal Fields", the "Add" (+) button is disabled.
Maybe a permission problem, but I don't see anything in the profiles panel to give permissions ...

I'm login with the super-admin account, GLPI 0.90.1.

Thanks for your help !

**Comment by btry** [comment]
Hi

I do not reproduce. On an empty GLPI 0.90.1, and a fresh install of the plugin, it just works.

Try to logout / login again. This shoul not be needed, though

**Comment by Manu1400** [comment]
You need 'config' right

**Comment by tomolimo** [comment]
Closed as we got no news from requester...
Feel free to re-open with news :smiley:

**Comment by tomolimo** [comment]
May be linked to https://github.com/pluginsGLPI/fields/commit/029da51
