### ISSUE TITLE
[glpi 0.90.5][fields 1.4.1] massive action no update the new fields

### ISSUE THREAD

**Issue by jsamaniegog** [pluginsGLPI/fields#120]
massive action no update the new fields

**Comment by trasher** [comment]
Try this fix: https://github.com/trasher/fields/commit/11abfaf5784a4a8ea515c54e6893289db373f8d9

**Comment by jsamaniegog** [comment]
It works! thank you @trasher

**Comment by trasher** [comment]
Cool, thanks for the test :)
