### ISSUE TITLE
Simplied Interface - Perfiles

### ISSUE THREAD

**Issue by dan723** [pluginsGLPI/fields#121]
If i add a field in a ticket in the simplified interface as "Insertion in the form (before save button)" and i set "no access" in a profile, i can still see the field when i create the ticket, i just can't edit the field. 
Is there a way to hide the field in the ticket creation for a specific profile?

Thanks

**Comment by trasher** [comment]
I'm not sure this is a bug or an expected behavior. Could you please confirm if the issue also happens on standard interface or when updating?

Thank you.

**Comment by dan723** [comment]
If I add the field as "tab" and set "no access" i'm not able to see it in the simplified interface.
I was expecting the same behaviour with "Insertion in the form (before save button)"

**Comment by trasher** [comment]
It should be the case with 1.4.2; it was kind of broken before

**Comment by dan723** [comment]
It works in the 1.4.2
Thanks!!
