### ISSUE TITLE
Can't create solution when plugin is active

### ISSUE THREAD

**Issue by Lokydoki** [pluginsGLPI/fields#122]
Latest version of plugin and GLPI 911.

Can't create solution when plugin is active. The problem is visible when any custom field is created. When doing a fresh install of plugin and an activation, it doesnt occur.

Tried disabling all other plugins and only let Fields activated.

**Comment by trasher** [comment]
I guess this is related to #120; could you please try this fix: https://github.com/trasher/fields/commit/11abfaf5784a4a8ea515c54e6893289db373f8d9 ?

**Comment by Lokydoki** [comment]
Just tested 1.4.2 with contains #120 patch.
Still the same issue.
Also tested in various disposition, still no solution is created.
Tested also with presaved solution and typed out solution
