### ISSUE TITLE
#122 [fields 1.4.2] didn't fixed it - Can't create solution

### ISSUE THREAD

**Issue by Lokydoki** [pluginsGLPI/fields#125]
I can't reopen #122 so I'm creating a new one.
Patch from #120 didnt fix the issue.

When I try to create a solution, it is not saved and status is not changed.
Works fine when I disable field plugin.

I catch this error on browser console just after clicking the save button : 
Navigated to http://sollicitation.vini.pf/glpi911/front/ticket.form.php
VM6192:1 Uncaught TypeError: Cannot read property 'appendChild' of null
    at <anonymous>:1:133
    at <anonymous>:1:151
(anonymous) @ VM6192:1
(anonymous) @ VM6192:1

**Comment by Lokydoki** [comment]
(je viens de voir que @trasher est FR :p)
Fais moi savoir de quelle information ou test vous avez besoin pour avancer sur ce probleme.

**Comment by trasher** [comment]
Hello,

(Oui, je suis français ; mais pour que le plus grand nombre puisse suivre, je préfère utiliser l'naglais ici ;))

So, could you please details which type of configuration you have on you solution fields? It seems that adding only a new tab is bugged (spotted in #124); maybe do you have the same exact bug.

**Comment by trasher** [comment]
Could you please try with the fix proposed in #124 to see if that solve your issue too? Thank you :)

**Comment by Lokydoki** [comment]
Ill try that fix but custom fields are added on the ticket main form (before save button).
Also I'll try to change the type of field if there's any difference. Right now I see the problem with string field and numeric field.

**Comment by Lokydoki** [comment]
Just tested it. Works great now !
