### ISSUE TITLE
Can't create ticket with custom forms while having custom fields on forms (cross plugin issue)

### ISSUE THREAD

**Issue by Lokydoki** [pluginsGLPI/fields#126]
Hi,
[glpi 9.1.1]
I don't know the problem occurs on formcreator side or fields side but I noticed that I can't create any ticket with forms when having custom fields on my ticket (tried with Fields 1.4.1, 1.4.2 and patched version pluginsGLPI/fields #124)

On version [Fields 1.4.1] and [Fields 1.4.2] I have this error after validating a custom form to create a ticket : 
![image](https://cloud.githubusercontent.com/assets/22624975/21461836/7405b436-c8f9-11e6-8ca7-c49a2e649d32.png)

On version [Fields 1.4.2 patch with #124] I dont have that pop up message but this 
![image](https://cloud.githubusercontent.com/assets/22624975/21462061/d181a41a-c8fb-11e6-86a3-99315d92bfe9.png)
Then wen i hit back button, I go back to prefilled custom form and a pop up saying ticket is created 
![image](https://cloud.githubusercontent.com/assets/22624975/21461991/2e539cbc-c8fb-11e6-90f2-eeec7025dc51.png)

Same ticket has been opened here pluginsGLPI/formcreator #404

To reproduce : 
- install [formcreator 0.90-1.3.4]
- create 1 custom form
- Add 1 question
- Add 1 destination (just a regular ticket will do)
- create a custom field attached to assistance /ticket (tab or main form doesnt matter ) with 1 field  (tested with header and text)
- go back to fill your custom form (dont forget to make it enable and visible)
- save and you will see the previous errors depending on with fields version you aure.

To make the error go away : deactivate fields plugin or disable all custom fields.

**Comment by btry** [comment]
I reproduce. with FormCreator 0.90+1.4beta7 and master branche of Fields

I got an error 500
```
PHP Fatal error:  Uncaught Error: Class 'PluginFieldsTicket' not found in //var/www/html/glpi/plugins/fields/inc/container.class.php:757
Stack trace:
#0 //var/www/html/glpi/plugins/fields/inc/container.class.php(1043): PluginFieldsContainer->updateFieldsValues(Array, false, 'Ticket')
#1 //var/www/html/glpi/inc/plugin.class.php(1125): PluginFieldsContainer::postItemAdd(Object(Ticket))
#2 //var/www/html/glpi/inc/commondbtm.class.php(885): Plugin::doHook('item_add', Object(Ticket))
#3 //var/www/html/glpi/plugins/formcreator/inc/targetticket.class.php(1367): CommonDBTM->add(Array)
#4 //var/www/html/glpi/plugins/formcreator/inc/form_answer.class.php(674): PluginFormcreatorTargetTicket->save(Object(PluginFormcreatorForm_Answer))
#5 //var/www/html/glpi/plugins/formc in //var/www/html/glpi/plugins/fields/inc/container.class.php on line 757, referer: http://localhost/~dethegeek/glpi-91/plugins/formcreator/front/form.form.php?id=9
```

**Comment by trasher** [comment]
Thanks to @btry; we have an idea of the problem.

Could you please try to drop the line:
https://github.com/pluginsGLPI/fields/blob/master/inc/container.class.php#L1121

It should solve the issue.

**Comment by btry** [comment]
did some tests with @trasher 

in container.class.php, removing line 1121 

```
      return $item->plugin_fields_data = [];
```
seems to solve the issue, but when we save a ticket , GLPI shows a new ticket form, and the additional field is populated with the content typed by the user in the previously saved ticket.

**Comment by trasher** [comment]
For the value issue; see #138

**Comment by sidneim** [comment]
Hello, I made the adjustment as requested and it continues not recording neither the Status nor the Category of the ticket.

But any tips besides deleting line 1121?

Thank you,
Sidnei
