### ISSUE TITLE
Ticket can not be finalized

### ISSUE THREAD

**Issue by sidneim** [pluginsGLPI/fields#127]
Hi, using a GLPI version 0.90.5 along with the Additional Fields Plugin 1.4.2. When I create as the example of the image, the tab appears in the message but I can not finish the ticket even preechendo the fields created, no message appears and nothing in the error LOG.

Disabling the plugin works normally.

Thank you,
Sidnei

![image](https://cloud.githubusercontent.com/assets/2439826/21485904/39767b2a-cb92-11e6-95f6-39a6aa1b9b16.png)

**Comment by trasher** [comment]
Please trey with fix proposed for #124

**Comment by sidneim** [comment]
Thank you thrasher, it worked. I have another problem but I will open another ticket to explain and discuss.
