### ISSUE TITLE
[BUG] The Insertion type in the form of a specific tab is not saving the entered data.

### ISSUE THREAD

**Issue by jorgecamargosdb** [pluginsGLPI/fields#129]
Greetings,

The Insertion type in the form of a specific tab is not saving the entered data. I tested it with "Text (single line)", "Dropdowns", "Text (Multiple line)" fields, and none of them writes to the database.

Fields in version 1.4.2
GLPI in Version 9.1.1

**Comment by trasher** [comment]
Hello,

This issue has already been reported; a fix is available (see #124) :)

**Comment by jorgecamargosdb** [comment]
Good afternoon @trasher 

I made the change to the .php file as reported in #124 , but the problem continued.
If you prefer I can send the database for testing.

[glpi-9.1.1-2016-12-28-16-52.sql.gz](https://github.com/pluginsGLPI/fields/files/676103/glpi-9.1.1-2016-12-28-16-52.sql.gz)


[container.class.gz](https://github.com/pluginsGLPI/fields/files/676108/container.class.gz)

**Comment by trasher** [comment]
I'll investigate

**Comment by trasher** [comment]
The latest release should solve the issue. Feel free to repoen if it does not ;)
