### ISSUE TITLE
Problem with form view (SQL error : Table of plugin doesn't exist)

### ISSUE THREAD

**Issue by plmorpheus** [pluginsGLPI/fields#13]
After enabling plugin, add fields and then enable (ie. in Computer tab) view of this new field, whole list in this view dissapears.
When plugin is enabled but added thru plugin filed in not selected as visible, the form is ok...
![1](https://cloud.githubusercontent.com/assets/4947597/12537933/82050bec-c2cc-11e5-8873-78987376a545.png)
...but when field is selected as visible in form settings - whole form dissapear :(
![2](https://cloud.githubusercontent.com/assets/4947597/12537932/8203d4de-c2cc-11e5-8db2-36e9861a4424.png)

**Comment by wawax** [comment]
hello,

any error message in debug mode or in the php-errors.log or sql-errors.log ?

**Comment by plmorpheus** [comment]
Hi, 
At first, thx for answer.

php-errors seems ok, but sql-errors returns this:

 *** MySQL query error:
  SQL: SELECT \'morpheus\' AS currentuser,
                         `glpi_computers`.`name` AS `ITEM_0`,
                        `glpi_computers`.`id` AS `ITEM_0_id`,
                        `glpi_states`.`completename` AS `ITEM_1`,  `glpi_manufacturers`.`name` AS `ITEM_2`,  `glpi_computers`.`serial` AS `ITEM_3`,  `glpi_computers`.`otherserial` AS `ITEM_4`,  `glpi_plugin_fields_computer_numerzksinwentarzowejfield`.`numerzksinwentarzowejfield` AS `ITEM_5`,  `glpi_computers`.`contact_num` AS `ITEM_6`,  `glpi_locations`.`completename` AS `ITEM_7`,  `glpi_computermodels`.`name` AS `ITEM_8`,  `glpi_operatingsystems`.`name` AS `ITEM_9`,  `glpi_computers`.`date_mod` AS `ITEM_10`,  `glpi_computers`.`id` AS id  FROM `glpi_computers`LEFT JOIN `glpi_states`
                                          ON (`glpi_computers`.`states_id` = `glpi_states`.`id`
                                              )LEFT JOIN `glpi_manufacturers`
                                          ON (`glpi_computers`.`manufacturers_id` = `glpi_manufacturers`.`id`
                                              ) LEFT JOIN `glpi_plugin_fields_computer`  AS `glpi_plugin_fields_computer_numerzksinwentarzowejfield`
                                          ON (`glpi_computers`.`id` = `glpi_plugin_fields_computer_numerzksinwentarzowejfield`.`items_id`
                                              AND `glpi_plugin_fields_computer_numerzksinwentarzowejfield`.`itemtype` = \'Computer\'
                                              ) LEFT JOIN `glpi_locations`
                                          ON (`glpi_computers`.`locations_id` = `glpi_locations`.`id`
                                              )LEFT JOIN `glpi_computermodels`
                                          ON (`glpi_computers`.`computermodels_id` = `glpi_computermodels`.`id`
                                              )LEFT JOIN `glpi_operatingsystems`
                                          ON (`glpi_computers`.`operatingsystems_id` = `glpi_operatingsystems`.`id`
                                              ) WHERE  `glpi_computers`.`is_deleted` = \'0\'  AND `glpi_computers`.`is_template` = \'0\'  ORDER BY ITEM_0 ASC  LIMIT 0, 20
  Error: Table 'IILO_glpi.glpi_plugin_fields_computer' doesn't exist
  Backtrace :
  inc/search.class.php:903
  inc/search.class.php:98                            Search::constructDatas()
  inc/search.class.php:81                            Search::showList()
  front/computer.php:44                              Search::show()

**Comment by plmorpheus** [comment]
Any ideas?

**Comment by trasher** [comment]
Since the issue was reported a while ago; would you please try with latest plugin release if the problem persists?
