### ISSUE TITLE
Can't update the label when i add a field

### ISSUE THREAD

**Issue by dan723** [pluginsGLPI/fields#130]
Hi,
I add a custom field on Contracts.
If i modify the label on the "Additional Fields" it doesn't reflect the change in Contract.

Thanks

**Comment by trasher** [comment]
Hello,

This issue has already been reported; a fix is available (see #124) :)

**Comment by dan723** [comment]
I tried but it doesn't work with this issue

**Comment by trasher** [comment]
Oh, OK, this is not a contract storage issue; sorry...

You'll probably have to edit the translation rather than change the label.

**Comment by dan723** [comment]
Ah ok i didn't know

Thanks a lot!!

2016-12-28 4:06 GMT-03:00 Johan Cwiklinski <notifications@github.com>:
