### ISSUE TITLE
[fields 1.4.2] Class 'PluginFieldsTicket' not found in /var/www/glpi/plugins/fields/inc/container.class.php on line 757

### ISSUE THREAD

**Issue by sidneim** [pluginsGLPI/fields#131]
Hi, I'm using the FormCreator plugin. When a ticket is opened, the system returns this error in the Apache logger:
PHP Fatal error: Class 'PluginFieldsTicket' not found in /var/www/glpi/plugins/fields/inc/container.class.php on line 757, referer: http://192.168.1.242/helpdesk/plugins/formcreator/front /formdisplay.php?id=16

I have a Block created as a new Call Guide.

Thank you,
Sidnei

**Comment by sidneim** [comment]
Hi, does anyone have any idea what this error might be? I am not using the plugin because this error will not use.

Thank you,
Sidnei

**Comment by trasher** [comment]
This duplicates #126
