### ISSUE TITLE
Modification tickets impossible avec votre plugin activé

### ISSUE THREAD

**Issue by tamtamaouy** [pluginsGLPI/fields#132]
Bonjour,

lorsque je veux modifier n'importe quel information dans un ticket, l'enregistrement n'est pas effectué. il me redonne la valeur d'avant, par exemple, modifier le status ou la validation ou meme la mise en place d'une solution ne s'enregistre pas.

j'utilise GLPI 9.1.1 et plugin fields version 1.4.2
PS il est utilisé avec d'autre plugin : formulaire, mreport, more ticket, 
merci de votre aide.

**Comment by trasher** [comment]
Hello,

This duplicates #124; a fix have been proposed for that already ;)

**Comment by tamtamaouy** [comment]
Bonsoir,

Merci bcp pour votre retour, effectivement la solution deja proposé marche très bien ;)

**Comment by trasher** [comment]
Super :)
