### ISSUE TITLE
Cannont change the status of a ticket when using the plugin

### ISSUE THREAD

**Issue by tamtamaouy** [pluginsGLPI/fields#133]
Hi,
i cannot change the status of a ticket when using the plugin, i already made the proposed change in the #124 but still cannot solve or close a ticket.
many thanks

**Comment by sidneim** [comment]
Hi, I'm also facing the same problem and instability elsewhere in the system like for example what I reported in #131.

**Comment by tamtamaouy** [comment]
Hi all,
i want to add some detail about my issue, when i create all my needed fields, every thing is working fine but if i click on "regenerate the blocks" all the visibility rights defined are no more applied and i cannot save any change in the ticket.
kind regards,

**Comment by trasher** [comment]
Please try this proposed fix:
https://github.com/pluginsGLPI/fields/issues/126#issuecomment-271300130

**Comment by sidneim** [comment]
Hello, I made the adjustment as requested and it continues not recording neither the Status nor the Category of the ticket.

But any tips besides deleting line 1121?

Thank you,
Sidnei

**Comment by trasher** [comment]
OK, could you please try this one: https://github.com/pluginsGLPI/fields/issues/137#issuecomment-271597335

**Comment by sidneim** [comment]
Thanks trasher , it worked now, at least the tests I did are working. I'm going to ask my group to test here to see if there's any other situation.

Thank you,
Sidnei

**Comment by trasher** [comment]
OK; thanks for the test; this is fixes in the latest plugin release :)
