### ISSUE TITLE
Conflict with monitoring plugin

### ISSUE THREAD

**Issue by keyser75000** [pluginsGLPI/fields#134]
Hi,

I've been trying for a while to get fields plugin works. I can create all type dom, domtab and tab without error. But dom and domtab do not appear in form. Only tab is functionnal.
After hours of research, I found that it is monitoring plugin that keep them to appear in my form (computers in my case).
If I disable monitoring plugin, fields (dom & domtab) both appear. The tab block is the only one to appear with monitoring enable. Nothing appears in logs (sql-errors.log & php-errors.log)

Is there a way to see what is wrong ?

(GLPI 0.90.5 & 9.1.1 - fields 1.4.3)

**Comment by trasher** [comment]
I do not know the other plugin; but it looks like a javascript issue. I guess the other plugin changes the asset page.

That will certainly be solved on the fields side once #119 has been integrated (with glpi 9.1.2); right now, I'm not sure this is really a fields issue...

**Comment by keyser75000** [comment]
Thanks for your fast answer.

Yep I think too it's not on fields side. But fields is more "alive" at this moment than monitoring :)
I'll try on monitoring github.
FYI it's a plugin that interface Shinken (nagios-like) with GLPI.

**Comment by trasher** [comment]
Yep I know the plugin existance and goals; but I do not know what it does exactly, espacially on the display side ;)

If you know javascript a bit, you may debug that. Fields use a jquery selector to find the row it must insert is stuff into. I the other plugin already adds something, it may break, and it may also break if the other plugin add not valid html (missing closing tags for example).

Hope that can help!
