### ISSUE TITLE
Menu entry displayed even if plugin must be upgraded

### ISSUE THREAD

**Issue by trasher** [pluginsGLPI/fields#143]
To reproduce:
- install fields plugin with on a glpi on 9.1/bugfixes branch
- create a container
- switch glpi branch to master

Plugin is marked "to upgrade" in plugin list; but "Additional fields" is present in the setup menu. It should not as it is not loaded.
The conséquence is an error message because of missing autoloader like `Fatal error: Uncaught Error: Class 'PluginFieldsContainer' not found`.

**Comment by trasher** [comment]
Sounds like this is a session issue: just log out an re-login solves this. not sure it can be fixed on the plugin side.

**Comment by orthagh** [comment]
Yes. menu is stored in session.
For debug purpose, i unset($_SESSION['glpimenu']) which force the reconstruction.

So yes, it's an issue, but i think also it shouldn't be addressed in the plugin.

**Comment by trasher** [comment]
OK, thank for the confirmation. I'll open an issue against the core :)
