### ISSUE TITLE
[1.4.5] Date field not saved

### ISSUE THREAD

**Issue by pcabreralallave** [pluginsGLPI/fields#147]
A date field is not being saved, tested in two different enviroments with same results

![image](https://cloud.githubusercontent.com/assets/19557972/22158321/b186236a-df09-11e6-979a-e71ce32d34cf.png)

**Comment by trasher** [comment]
Cannot reproduce here. Please give more details (container type, wich item, which profile, ...).

**Comment by trasher** [comment]
Ping?

**Comment by trasher** [comment]
Closing as no feedback
