### ISSUE TITLE
bug avec le plugin formcreator

### ISSUE THREAD

**Issue by romain1206** [pluginsGLPI/fields#149]
bonjour,

lors de la saisie d'un formulaire j'ai cette erreur  "Impossible de générer les destinations !"

aprés plusieurs essais et vérifications j'ai désactivé les plugins un par un

avec le plugin fields, j'ai activer un champ supplémentaire sur le ticket (telephone + personne a contacter)

j'ai tenter de modifier les champs en les rendant non obligatoire mais ca ne résoud pas le soucis

merci de votre aide

**Comment by trasher** [comment]
Please use english for tickets.

What version of fields are you using? There were issues with other plugins; that have been fixed in the last release.

**Comment by romain1206** [comment]
i use the 1.4.0

**Comment by trasher** [comment]
Please upgrade to 1.4.5

**Comment by romain1206** [comment]
thanks it's works

sorry

**Comment by trasher** [comment]
No problem ;)
