### ISSUE TITLE
Suppression d'utilisateur impossible à cause du plugin

### ISSUE THREAD

**Issue by Miminoux** [pluginsGLPI/fields#15]
Bonjour,

J'ai créé un bloc (infoscomplmentaires) avec 5 champs pour compléter les info des utilisateurs sauf qu'à présent je ne peux plus supprimer d'utilisateur. Je peux les mettre à la corbeille mais au moment de vider celle-ci, page blanche sur l'URL "https://glpi.atih.sante.fr/front/massiveaction.php", pas de chargement.
Dans les logs, j'ai l'erreur nginx suivante : 
`[error] 651#651: *57510 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'PluginFieldsUserinfoscomplmentaires' not found in /usr/share/nginx/html/plugins/fields/inc/container.class.php on line 270" while reading upstream, client: 10.42.11.22, server: localhost, request: "POST /front/massiveaction.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "glpi.atih.sante.fr", referrer: "https://glpi.atih.sante.fr/front/user.php?is_deleted=1&criteria%5B0%5D%5Bfield%5D=view&criteria%5B0%5D%5Bsearchtype%5D=contains&criteria%5B0%5D%5Bvalue%5D=ARS&itemtype=User&start=0"`

J'utilise GLPI 0.90 et la version 0.90-1.1 du plugin Fields.

Une idée de ce qu'il se passe ?

Merci

**Comment by trasher** [comment]
Hello,

Could you please try with the last plugin release? Many things have changed; I guess this should have been fixed since.

Closing this issue for now.
