### ISSUE TITLE
Bug to display a field when creating a ticket.

### ISSUE THREAD

**Issue by jfg-fimac** [pluginsGLPI/fields#152]
_GLPI 9.1.2
Plugins: fields Name: Extra Fields Version: 1.5.0 State: Enabled_

Hello,
Following the update of version 0.90.3 to version 9.1.2, my field "fields" no longer appears when creating a ticket.

However, the column and information are displayed correctly in the current ticket display.

Uninstalling and reinstalling does not change the problem.
Namely, adding a field as a tab will work properly.

Thank you in advance.

**Comment by jfg-fimac** [comment]
Hello @trasher ,

I'm blocked for Upgrade my production GLLPI because of this bug.
Have you a date for publish the version 1.5.1 ?

Thanks for your answer and your work.

**Comment by trasher** [comment]
Nothing is planned regarding a new release for the plugin, sorry.

**Comment by trasher** [comment]
For further investigation, could you please provide extra infos:

* what is the type of the container that does not work? (where is it supposed to be displayed)
* does it works/fails on a specific profile?
* are there any informations in glpi logs?

Thanks

**Comment by jfg-fimac** [comment]
Hello @trasher !

- what is the type of the container that does not work? (where is it supposed to be displayed)
It is a block "Insert in the form (before the save button)" with a field "Text (simple line)" which must therefore display a field tesx before the button "add" to the creation of a tcket.

- does it works/fails on a specific profile?
This field is set with no restrictions and does not work on any of the profiles.

- are there any informations in glpi logs?
I can not find SQL errors or events in logs.

Thanks

**Comment by trasher** [comment]
OK, thank you for the details. I'll try to reproduce (do not have many free time right now, sorry).

**Comment by mrspam** [comment]
Hi !

Same thing for me GLPI 9.1.2 and plugin 1.4.5 work perfectly.
After upgrade to 1.5.0, can't see the field on ticket and in create ticket section.

I'm use a block "Insert in the form (before the save button)" with a field "Yes/No".
With block 'Tab' no problem it work !

With plugin 1.6.0 and 1.6.1 same problem.

Thanks for your work =)

**Comment by jfg-fimac** [comment]
Hi !
Have you find the problem ?
Just for have a delay.
Thanks you ;)

**Comment by mrspam** [comment]
Hi 

No I have always the problem sorry...

**Comment by orthagh** [comment]
closing, next 1.7.0 will (i hope) definitively fix theses kind of issues
