### ISSUE TITLE
Install Plugin fields on glpi 0.90

### ISSUE THREAD

**Issue by osvaedca** [pluginsGLPI/fields#153]
Hello ,

I installed the glpi version 0.90, and now i want install the plugin "fields" , but after installation the plugin is 

not visible in the interface complements on glpi for activate is missing .....?  what's happen .... :(

thank you for the help.

**Comment by btry** [comment]
Hi

Did you installed it correctly ?

The folder containing the plugin must be **fields** and must be located in **glpi/plugins/** . If not, the plugin will not show in the plugins page.

An other common error is bad permissions or owner. Check this oo.

**Comment by trasher** [comment]
Closing as no feedback.
