### ISSUE TITLE
[Composer]Current 'scripts' block only apply on require-dev

### ISSUE THREAD

**Issue by orthagh** [pluginsGLPI/fields#154]
With 1.5.0 release.
In our teclib-glpi-util packaging bash script, we have this command:
```
composer install --no-dev
```

And so, it fails:
```
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
> patch -d vendor/atoum/atoum -p1 < tools/atoum-php71.patch
patch: **** Can't change to directory vendor/atoum/atoum : No such file or directory
Script patch -d vendor/atoum/atoum -p1 < tools/atoum-php71.patch handling the post-install-cmd event returned with error code 2

```

From [composer doc](https://getcomposer.org/doc/articles/scripts.md):

> Note: During a composer install or update process, a variable named COMPOSER_DEV_MODE will be added to the environment. If the command was run with the --no-dev flag, this variable will be set to 0, otherwise it will be set to 1.

Maybe we could test this env var before execute patch command, ex (no tested) :
```
[ $COMPOSER_DEV_MODE != 0 ] && patch -d vendor/atoum/atoum -p1 < tools/atoum-php71.patch
```

**Comment by trasher** [comment]
Fixed in develop, thanks.
