### ISSUE TITLE
how to hide dropdown line

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/fields#159]
Hello

We would like to remove an item in a dropdown, unfortunately this option is not available.

The only way is to delete the line but all tickets with this line are losing the item.

Is it possible to add this option ? (hide line)

![image](https://cloud.githubusercontent.com/assets/15144026/23121705/c0b2ef4c-f761-11e6-8020-c048264c0f01.png)

Thx

**Comment by stonebuzz** [comment]
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
