### ISSUE TITLE
[Massive actions] Ne pas vérifier l'intégralité des champs supplémentaire obligatoires lors d'une massive action

### ISSUE THREAD

**Issue by Miminoux** [pluginsGLPI/fields#16]
Bonjour,

Impossible de changer par exemple la catégorie d'un ensemble d'utilisateurs (sélectionner les utilisateurs, puis "Action", "Modifier", puis sélectionner le champ et sa valeur), lorsque l'on utilise un champ obligatoire sur les utilisateurs : 
Un champ obligatoire est vide : Fonction, Service, Profile d'accès 
Opération échouée
(0 problèmes de droits, 1 échecs)
DUPONT Jean : Erreur en exécutant l'action 

Je vais essayer de faire la modification en retirant l'obligation de saisir ces champs puis en les remettant mais c'est très lourd.

Merci
PS : GLPI 0.90, Fields 0.90-1.1

**Comment by Miminoux** [comment]
J'ai testé et j'ai pu passer les champs supplémentaires optionnels (non obligatoire), faire ma modification de masse et les repasser en obligatoire...
C'est certes un peu moche mais ça marche en attendant une correction.

**Comment by Manu1400** [comment]
Duplicated issue of #20
