### ISSUE TITLE
Error in creation new project after using PLUGIN FIELDS PLUGIN

### ISSUE THREAD

**Issue by surfreg** [pluginsGLPI/fields#160]
Hi,
After intall the FIELDS PUGIN on GLPI 9.1.1 and configure a new fields in GLPI PROJECT, each time we create a new project a HTTP ERROR 500 page arrive. We have to actualise and the page arrive and the project is create.

If i disable the plugin no error message when creating new project.

Thanks

Surfreg

**Comment by trasher** [comment]
What is the version of the plugin?

**Comment by surfreg** [comment]
Hi it's the 1.4.3

**Comment by trasher** [comment]
Please try with 1.4.5.

**Comment by trasher** [comment]
Ping?
