### ISSUE TITLE
Problem on update 1.5.0 to 1.6.0

### ISSUE THREAD

**Issue by 1Fopresta** [pluginsGLPI/fields#169]
Hello, when i update the plugin in 1.6.0 version (from 1.5.0), i have this error : 

PHP Fatal error:  require_once(): Failed opening required 'etatfielddropdown.class.php' (include_path='.:/usr/share/php:/usr/share/pear') in /data/support/www/glpi-9.1.2/plugins/fields/inc/dropdown.class.php on line 133

The update failed

**Comment by trasher** [comment]
Sounds like this is only related to dropdown fields... I've missed something on those particular cases :/

**Comment by trasher** [comment]
Fixed in 1.6.1.

**Comment by 1Fopresta** [comment]
It work ! :)
Thanks

**Comment by mrspam** [comment]
Perfect thanks ! =)
