### ISSUE TITLE
Can't display TWO tabs under one asset at the same time

### ISSUE THREAD

**Issue by CfYz-R** [pluginsGLPI/fields#17]
Fresh installation of GLPI 0.90.1
Fields 0.90-1.1
No other plugins or modifications to GLPI.

How to reproduce:
1. Add first **active** block under Asset Networks - type "Add tab", and add one header field in it.
2. Add second **active** block under Assets Networks - type "Add tab", and one header field in it.

Now add one asset under Networks, goto this item - and you will see just ONE first block from Field plugin. If you make first block inactive - then you will see the second block in item and vice versa.

Is this is a normal behavior or it's a bug? Can you fix it plz? :)

**Comment by CfYz-R** [comment]
Fixed... When you add blocks of fields in cyrillic - then a lot of bugs appears. When you using english names - all working fine. ty =)

**Comment by trasher** [comment]
This is actually possible to add two tabs on same item; it works well.

As for language bugs; I cannot reproduce with latests releases; it may have been fixed.
