### ISSUE TITLE
Default items to show in Project

### ISSUE THREAD

**Issue by gmourani** [pluginsGLPI/fields#170]
When adding a new field into Project and selecting this one as a default item to show, it appears as "Plugins - Tab - Name" and cannot be removed once added!

Should appears as Name only and be possible to remove it.

<img width="1279" alt="screen shot 2017-03-08 at 11 43 37 am" src="https://cloud.githubusercontent.com/assets/20328799/23713632/893eed46-03f4-11e7-9937-0cd26fd99df8.png">

**Comment by cedric-anne** [comment]
Hi,

We will not change the naming system for multiple reasons:
- the `Plugins - ` prefix gives a context to prevent ambiguity with GLPI fields,
- the `Tab - ` prefix gives another context to prevent ambiguity with another block fields.

I look about changing the `Plugins - ` prefix by the plugin name, but it requires a huge work, so I would not do it.

Regards
