### ISSUE TITLE
Update problem 1.5.0 to 1.6.0

### ISSUE THREAD

**Issue by mrspam** [pluginsGLPI/fields#172]
Hi !

Update failed and php error : 

 *** PHP Warning(2): require_once(codelistefielddropdown.class.php): failed to open stream: No such file or directory
  Backtrace :
  plugins/fields/inc/dropdown.class.php:133
  plugins/fields/inc/dropdown.class.php:133          PluginFieldsDropdown::create()
  plugins/fields/inc/dropdown.class.php:42           PluginFieldsDropdown::create()
  :                                                  PluginFieldsDropdown::install()
  plugins/fields/hook.php:80                         call_user_func()
  inc/plugin.class.php:664                           plugin_fields_install()
  :                                                  Plugin->install()
  front/plugin.form.php:49                           call_user_func()

GLPI 9.1.2.

Thanks for your help =)

**Comment by mrspam** [comment]
The file codelistefielddropdown.class.php is in /var/www/glpi/files/_plugins/fields/inc.

Right correct "www-data:www-data".

**Comment by trasher** [comment]
Duplicates #169
