### ISSUE TITLE
Fields not displayed on "Classic view" and "Vertical split" layout

### ISSUE THREAD

**Issue by C-Duv** [pluginsGLPI/fields#175]
When using _Classic view_ or _Vertical split_ layout (in user's personalization), plugin fails to display fields.

Here is my test matrix (using plugin version 1.6.1):

Container type | Associated item type | Extra config | Field name | Layout | Result | Notes
-------------- | -------------------- | -------------| ---------- | ------ | ------ | -----
Add tab | Computers |  | `at_txt` | Tabs on left | :heavy_check_mark: New tab added with `at_txt` field | 
Add tab | Computers |  | `at_txt` | Classic view | :heavy_check_mark: New tab added with `at_txt` field | 
Add tab | Computers |  | `at_txt` | Vertical split | :heavy_check_mark: New tab added with `at_txt` field | 
Insertion in the form (before save button) | Computers |  | `if_txt` | Tabs on left | :heavy_check_mark: `if_txt` field added on *main* form part | 
Insertion in the form (before save button) | Computers |  | `if_txt` | Classic view | :x: `if_txt` field not displayed | After page refresh, a new field is displayed on *main* form part. If displayed tab was -Operating System*, displayed field is `ifst_txt`, it's `at_txt` otherwise
Insertion in the form (before save button) | Computers |  | `if_txt` | Vertical split | :x: `if_txt` field not displayed | After page refresh, a new field is displayed on *main* form part. If displayed tab was *Operating System*, displayed field is `ifst_txt`, it's `at_txt` otherwise
Insertion in the form of a specific tab (before save button) | Computers | *Operating System* tab | `ifst_txt` | Tabs on left | :heavy_check_mark: `ifst_txt` field displayed on "Operating System" tab | 
Insertion in the form of a specific tab (before save button) | Computers | *Operating System* tab | `ifst_txt` | Classic view | :heavy_check_mark: `ifst_txt` field displayed on "Operating System" tab | 
Insertion in the form of a specific tab (before save button) | Computers | *Operating System* tab | `ifst_txt` | Vertical split | :heavy_check_mark: `ifst_txt` field displayed on "Operating System" tab | 

Il also tested on *GLPI*'s `9.1/bugfixes` branch (glpi-project/glpi@0b60ba752c705fdd10ac4b5abfacb5261dff40d3) and *GLPI* v9.2 (*GLPI*'s `master` branch, glpi-project/glpi@72af75ab418149e943e5055e227772c2b9ae5835): same results.

Note that the `if_txt` field (field on *Insertion in the form* tabs) is not shown when **adding** Computer on *GLPI* v9.1.x but is on v9.2 (*GLPI*'s `master` branch, glpi-project/glpi@72af75ab418149e943e5055e227772c2b9ae5835).

**Comment by orthagh** [comment]
1.7.0 will contains this bugfix

**Comment by juveboss** [comment]
Hello,

Problem on GLPI 9.2.2 / Fields 1.7.3.

When GLPI is opened, if I select the layout: Classic View or Vertical Separation the fields at ticket creation do not appear when the ticket is created.

![image](https://user-images.githubusercontent.com/31047406/46620684-abb82280-cb25-11e8-9ded-7297239c096f.png)



But if I select: tab on the left in the layout it's ok

![image](https://user-images.githubusercontent.com/31047406/46620656-980cbc00-cb25-11e8-89af-2e8fbea1abe3.png)
