### ISSUE TITLE
"Number" type fields cannot contains 0 when field is mandatory

### ISSUE THREAD

**Issue by C-Duv** [pluginsGLPI/fields#176]
I have a field named `foo` of type *Number* set as mandatory.

Form submission fails when field `foo` is filled with the value `0`, I get the following error message from GLPI:
> Some mandatory fields are empty : foo

Note that the value `00` is accepted but it's `0` that gets stored in the database

Version:
* GLPI v9.1.2 and GLPI v9.2
* Plugin v1.6.1

**Comment by orthagh** [comment]
1.7.0 will contains this feature request
