### ISSUE TITLE
PHP error vendor/autoload.php

### ISSUE THREAD

**Issue by J-n-s** [pluginsGLPI/fields#177]
Hi, 

With GLPI 9.1.3 and Fields 1.6.1, php errors: 
` *** PHP Warning(2): include_once(): Failed opening '/usr/share/glpi/plugins/fields/vendor/autoload.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php')
  Backtrace :
  plugins/fields/setup.php:67        
  plugins/fields/setup.php:67                        plugin_init_fields()
  inc/plugin.class.php:146                           plugin_init_fields()
  inc/includes.php:116                               Plugin::load()
  front/profile.php:38                               include()`
`  *** PHP Warning(2): include_once(/usr/share/glpi/plugins/fields/vendor/autoload.php): failed to open stream: No such file or directory
  Backtrace :
  plugins/fields/setup.php:67
  plugins/fields/setup.php:67                        plugin_init_fields()
  inc/plugin.class.php:146                           plugin_init_fields()
  inc/includes.php:116                               Plugin::load()
  front/plugin.php:38                                include()`

Maybe in setup.php, l67 replace this?:
`include_once(PLUGINFIELDS_DIR . "/vendor/autoload.php");`
by
`include_once(GLPI_ROOT . "/vendor/autoload.php");`

**Comment by trasher** [comment]
Hi,

I'm pretty sure you've downloaded the plugin source code, and not the plugin release.

The change you propose is not correct.

**Comment by J-n-s** [comment]
Correct, sorry!
