### ISSUE TITLE
interface simplifiée

### ISSUE THREAD

**Issue by romain1206** [pluginsGLPI/fields#179]
bonjour,

depuis mon passage en glpi 9.1.2 les champs supplémentaires ne s'affichent plus en interface simplifiée pour les utilisateurs.

par compte un utilisateur en super admin/admin et que je change le profil en post-only j'ai bien mes champs

en mode debug je n'ai pas d'erreurs

merci de votre aide

glpi: 9.1.2
fields: 1.6.1

**Comment by romain1206** [comment]
meme en admin le fonctionnement est aléatoire. les champs s'affichent et finissent par disparaitre

**Comment by romain1206** [comment]
le fait de désactiver / reactiver le plugin permet d'afficher les champs en admin

**Comment by romain1206** [comment]
bonjour,

je me permets un petit UP

toujours le soucis

**Comment by thefamedtm** [comment]
Hello,

I have the same problem. I can't view custom fields in simplified view with user profile.

I update fields plugin to 1.6.2 in my 0.9.1.4 glpi.

Thanks in advance.

**Comment by orthagh** [comment]
Hello all.

Could you precise a little ?
What's itemtype is affected, Tickets ?
Is it on creation or update of the object ?

**Comment by orthagh** [comment]
also probably a duplicate of #185
