### ISSUE TITLE
Undefined index when selecting infocom table in a mapping

### ISSUE THREAD

**Issue by xsgb** [pluginsGLPI/fields#180]
Shown per mapping line if the selected table is infocom.

Edit: There is v1.6.1

`PHP Notice: Undefined index: field in /var/www/html/4js_glpi/plugins/datainjection/inc/commoninjectionlib.class.php at line 1925`

![infocom](https://cloud.githubusercontent.com/assets/1431656/24445964/188cbadc-146c-11e7-8946-90ff820e842b.jpg)

**Comment by orthagh** [comment]
Hello @xsgb, sorry for the delay of answer.

Could you provide the full backtrace (should be availlable in glpi/_files/php_errors.log) ?

**Comment by xsgb** [comment]
No problem, here it is: https://gist.github.com/xsgb/fa42c5e33075d5b75ba03b7f558da4aa

**Comment by orthagh** [comment]
Thank you.
I suspected it but before i wanted to check.
Your logs indicates much clearly that's a issue of [datainjection](https://github.com/pluginsGLPI/datainjection) plugin not [fields](https://github.com/pluginsGLPI/fields) one

**Comment by trasher** [comment]
Please open issue against the correct plugin ;)
