### ISSUE TITLE
migrate from CustomFields to Fields plugin

### ISSUE THREAD

**Issue by mobidevadmin** [pluginsGLPI/fields#181]
Hello,

I  upgraded glpi and had to use Fields plugin instead of obsolete CustomFields one. 
How I can migrate my data from old plugin to new one? 

Thanks

**Comment by btry** [comment]
Hi

There is no tool to migrate data from custom fields to fields. The purpose of these plugins and their feature différences prevents building a method which works for every one.

However doing a migration manually with some SQL queries is reasonably easy. First discover how to use Fields and use its user interface to create new fields.

Next, view your database, study the model to understand the models of both plugin.

Finally build SQL requests to copy data from the old plugin to the new.

Prepare the whole process on a testing copy of GLPI, and reproduce on your production instance.

**Comment by mobidevadmin** [comment]
Hi,

thanks, will follow your tips
