### ISSUE TITLE
Ajout les champs supplémentaire au modèle de notifications

### ISSUE THREAD

**Issue by JeremyPOPIT** [pluginsGLPI/fields#184]
Bonjour,

Je souhaiterai savoir s'il est possible d'ajouter les champs d'un onglet supplémentaire créé à partir du plugin fileds aux modèles de notifications ?

Si oui avez vous une documentation ou des informations sur comment il serait possible de réaliser  ?

Merci bien,

Cordialement,
Jeremy

**Comment by bousahla** [comment]
Bonjour,

J'ai le même problème. quelqu'un pourra nous aider svp?

**Comment by JeremyPOPIT** [comment]
Bonjour, 

Désolé mais cela n'est pas possible actuellement. Il faut intervenir via du développement pour l'instant.

**Comment by bousahla** [comment]
Je vous remercie

**Comment by wawax** [comment]
Bonjour,

Ce n'est actuellement pas prévu proche.
Si vous avez besoin de ce développement, je vous invite à nous écrire sur contact@teclib.com pour une proposition commerciale.

Cordialement,

**Comment by bousahla** [comment]
Bnjour,

Je vous remercie, j'ai envoyé un mail à l'adresse que vous m'avais donné 
ce matin. J'attends leurs réponse.
Salutations Respectueuses.



Sarah  BOUSAHLA
0  670   443   567



De :    Walid Nouh <notifications@github.com>
A :     pluginsGLPI/fields <fields@noreply.github.com>, 
Cc :    bousahla <sarah.bousahla@mobilis.dz>, Comment 
<comment@noreply.github.com>
Date :  25/08/2017 15:38
Objet : Re: [pluginsGLPI/fields] Ajout les champs supplémentaire au modèle 
de notifications (#184)



Bonjour,
Ce n'est actuellement pas prévu proche.
Si vous avez besoin de ce développement, je vous invite à nous écrire sur 
contact@teclib.com pour une proposition commerciale.
Cordialement,
?

**Comment by orthagh** [comment]
1.7.0 will contains this feature request

**Comment by trasher** [comment]
@juveboss Please use [forums](http://forum.glpi-project.org) to get support.
