### ISSUE TITLE
An error in your SQL syntax

### ISSUE THREAD

**Issue by AircraftRu** [pluginsGLPI/fields#187]
2017-05-04 09:39:08 [1000@glpi]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_fields_computer647122290s` WHERE plugin_fields_containers_id = 7 AND items_id = 
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2
  Backtrace :
  inc/commondbtm.class.php:263                       
  plugins/fields/inc/field.class.php:590             CommonDBTM->find()
  plugins/fields/inc/field.class.php:494             PluginFieldsField::prepareHtmlFields()
  plugins/fields/inc/field.class.php:565             PluginFieldsField::showDomContainer()
  inc/plugin.class.php:1138                          PluginFieldsField::showForTab()
  inc/commondbtm.class.php:2085                      Plugin::doHook()
  inc/computer.class.php:667                         CommonDBTM->showFormButtons()
  inc/commonglpi.class.php:473                       Computer->showForm()
  ajax/common.tabs.php:97                            CommonGLPI::displayStandardTab()

**Comment by trasher** [comment]
Please provide additional info on how to reproduce; version used, and so on.

**Comment by AircraftRu** [comment]
The error has been in 9.1.2 version, no errors in 9.1.3

**Comment by trasher** [comment]
Great, thank you
