### ISSUE TITLE
Simplified interface

### ISSUE THREAD

**Issue by kapzwaz** [pluginsGLPI/fields#19]
Hello, i'm trying to add a new field to simplified interface. I followed the documentation and created a block to tickets but when i'll open a ticket the field don't appear. Could someone help me with this issue?

**Comment by Mhedivh** [comment]
Hello, I have the same problem, the new field is shown in the standard interface but not the simplified one eventhough:
- The field is appended to the from.
- All profiles have the correct privileges to access to the new field.

Any help ?

**Comment by lucianoes** [comment]
@orthagh 

Same problem here. 

Is this feature (custom field) in simplified interface?

**Comment by kapzwaz** [comment]
In the french documentation, the 5.1 item told about simplified interface. But I tried to follow the inscructions without success... Someone have a solution?

Thanks!

**Comment by edumabreu** [comment]
I´m facing the same problem. I was using glpi 9.0.1 and the problem remains after update to glpi 9.1. Could anyone help us?

**Comment by romain1206** [comment]
same problem for me in 9.1

**Comment by prob6** [comment]
same problem for us. It's important for us that this functionnality work again on GLPI 9.1

**Comment by ocs-lsanchez** [comment]
Same problem, see "Champs non visibles sur interface simplifiée #85"

**Comment by romain1206** [comment]
toujours pas de news de ce bug ?

**Comment by trasher** [comment]
Hello,

I'll take an eye asap.

**Comment by trasher** [comment]
I cannot reproduce on my side; with latest Fields release (1.3.2).

To get this working; bloc **must** be associated to ticket item; and **must** be of type "Insertion in the form (before save button)". Also check in the bloc profiles that "self-service" has read or write access.

Please upgrade to last release and double check your configuration.

**Comment by romain1206** [comment]
je suis bien en version 1.3.2 avec glpi 9.1.1 mais j'ai pas accés en self service

[http://i.imgur.com/C7udIzb.png](url)

[http://i.imgur.com/wt4UdQV.png](url)

[http://i.imgur.com/p4SQSr1.png](url)

**Comment by trasher** [comment]
Indeed, your configuration seems correct; but I still can't reproduce :/

Could you please enable debug mode and also check in your logs if something appears?

**Comment by romain1206** [comment]
j'ai cette erreur en mode super admin debug
`PHP Runtime Notice: Declaration of PluginFormvalidationField::displayTabContentForItem() should be compatible with CommonGLPI::displayTabContentForItem(CommonGLPI $item, $tabnum = 1, $withtemplate = 0) in /var/www/glpi/plugins/formvalidation/inc/field.class.php at line 0`

mais pas d'erreur en post-only

**Comment by romain1206** [comment]
j'ai désactiver le plugin fiormValidation je n'ai plus d'erreurs mais ca ne fonctionne pas mieux.

rien dans le fichier php-errors.log non plus

**Comment by tomolimo** [comment]
> PHP Runtime Notice: Declaration of PluginFormvalidationField::displayTabContentForItem() should be compatible with CommonGLPI::displayTabContentForItem(CommonGLPI $item, $tabnum = 1, $withtemplate = 0) in /var/www/glpi/plugins/formvalidation/inc/field.class.php at line 0

This is not an error, but a notice only!

**Comment by dan723** [comment]
Hi,
I've got the same problem, any news?

Thanks

**Comment by romain1206** [comment]
bonjour,

toujours pas d'avancée, je suis dispo pour des test et ouvrir un teamviewer si besoin

**Comment by dan723** [comment]
With the simplified interface, you can see the new field if you open a ticket from the ticket list.
It would be useful to have the possibility to see the field when creating a new ticket.

**Comment by romain1206** [comment]
merci ca apparait maintenant

**Comment by dan723** [comment]
That worked great!!!
Thanks a lot

**Comment by l2aggron** [comment]
Hello! I have same issue with glpi 9.1.2 and fields 1.5.0 - works on standart interface but not on simplified. I checked all of what you said and did as it is written in the user manual.

**Comment by trasher** [comment]
Sounds like the field do appear on ticket creation in simplified interface; I do not have problems.

As for the field emplacement, there was an issue that has been fixed recently on glpi side; make sure you got the latest git revision.

**Comment by marcoscarrihlo** [comment]
Hello!
I have the same problem, but the error occurs when i use the profile self-service.
If i use "create ticket" in super-admin profile, the error not occurs.
Plugin version: 1.6.1
GLPI Version: 9.1.2

Thanks for any help.
