### ISSUE TITLE
Can't use field in filter

### ISSUE THREAD

**Issue by msizec** [pluginsGLPI/fields#190]
When using a new field as a filter "contains", there's no result.

Also, when adding the field as a column in a personal view, GLPI hangs and the user has to delete the personal view.

Using Fields 1.5.0

**Comment by msizec** [comment]
Am I the only one facing this issue ?

**Comment by msizec** [comment]
Heres hte content of sql-errors.log

[...]                   ) LEFT JOIN `glpi_plugin_fields_phone`  AS `glpi_plugin_fields_phone_imeifield`
                                          ON (`glpi_phones`.`id` = `glpi_plugin_fields_phone_imeifield`.`items_id`
                                              AND `glpi_plugin_fields_phone_imeifield`.`itemtype` = \'Phone\'
                                              )  WHERE  `glpi_phones`.`is_deleted` = \'0\'  AND `glpi_phones`.`is_template` = \'0\'  AND (    `glpi_plugin_fields_phone_imeifield`.`imeifield`  LIKE \'%12345%\'   ) GROUP BY `glpi_phones`.`id` ORDER BY ITEM_0 ASC
  Error: Table 'glpi.glpi_plugin_fields_phone' doesn't exist
  Backtrace :
  inc/search.class.php:921
  inc/search.class.php:97                            Search::constructDatas()
  inc/search.class.php:80                            Search::showList()
  front/phone.php:44                                 Search::show()

**Comment by msizec** [comment]
the same with 1.6.1

Is there anyone reading issues ?

**Comment by orthagh** [comment]
Hello. by checking the log you providing, it seems the table generation didn't work well.
Could you go into the administration of additional fields and clic on the top button: 
![image](https://user-images.githubusercontent.com/418844/29923825-16dbe3ca-8e5b-11e7-83f8-4e08675b8dcb.png)

It will regenerate also the missing table, i think.
Let me know if this fix your issue (i close atm)

**Comment by msizec** [comment]
Hello,

No it did not resolve my problem

**Comment by orthagh** [comment]
the "Regenerate..." action will fix table in the next release (1.7.0 for glpi 9.2)
Waiting for it, i could just suggest you to remove your container & recreate it, without its table, it cannot working well.

**Comment by msizec** [comment]
Ok so im waiting for the next version.

But if I delete the container will it delete the already existing data ?

 

 

De : Alexandre Delaunay [mailto:notifications@github.com] 
Envoyé : lundi 4 septembre 2017 10:08
À : pluginsGLPI/fields <fields@noreply.github.com>
Cc : msizec <mathieu.sizec@maximo.fr>; Author <author@noreply.github.com>
Objet : Re: [pluginsGLPI/fields] Can't use field in filter (#190)

 

the "Regenerate..." action will fix table in the next release (1.7.0 for glpi 9.2)
Waiting for it, i could just suggest you to remove your container & recreate it, without its table, it cannot working well.

**Comment by orthagh** [comment]
> But if I delete the container will it delete the already existing data ?

Unfortunately yes

**Comment by msizec** [comment]
ok we'll wait for the next version, thx
