### ISSUE TITLE
Support adding fields to non-standard object.

### ISSUE THREAD

**Issue by marcogaio** [pluginsGLPI/fields#197]
This probably _extend_ #188 .

Would be useful if this plugin can add custom fields to non-standard objects, like object created by other plugin (as 'badge' plugin, or 'rooms' plugins and so on).

Thanks.

**Comment by orthagh** [comment]
Hello @marcogaio 

This plugins supports the addition of itemtypes by others plugins.
A hook exists in the code: https://github.com/pluginsGLPI/fields/blob/master/setup.php#L82

But as far i remember, no plugins use it already

**Comment by marcogaio** [comment]
Ok. I can do something to try to ''force'' the use of the plugin?!

Supposing i need custom fields on 'appliances' items (created by appliances plugin) for the block 'sic', i need to create the table 'glpi_plugin_fields_appliancesics' (with the same schema of other tables)?

Or i need to do more things?

**Comment by marcogaio** [comment]
Ok, no, it suffices to know/understand as GLPI name object classes. I've done:
`update glpi_plugin_fields_containers set itemtypes='["Computer","Monitor","Software","Peripheral","Printer","PluginAppliancesAppliance"]' where id=1;`

and then create the table glpi_plugin_fields_pluginappliancesappliancesics, and now i've my custom field also on appliances.

Good!

**Comment by orthagh** [comment]
it's a "solution" for bypass, yeah.
You'll understand i will not furnish as if in the plugin :D

**Comment by marcogaio** [comment]
Sure!

But consider adding all itemtypes (also plugin-based ones) to containers creation.

Also, the ability to modify items associated to container will be useful. ;-)

Thanks.

**Comment by trasher** [comment]
It is not possible to list all item types. Some from the core will not work (because of core specificities).

> Also, the ability to modify items associated to container will be useful. ;-)

See https://github.com/pluginsGLPI/fields/issues/165
