### ISSUE TITLE
Possible PHP 7 error 

### ISSUE THREAD

**Issue by alejandroed** [pluginsGLPI/fields#198]
Hi!

I've problems with my install with PHP7 and GLPI 9.1.2. When I try to create a new custom field (ie. TEST, text type) I obtain a Error 500 from the browser.

The apache2 error log say:

[:error] [pid 30307] PHP Fatal error:  Uncaught Error: Class 'PluginFieldsTicketTEST' not found in /var/www/glpi/plugins/fields/inc/field.class.php:120\nStack trace:\n#0 /var/www/glpi/inc/commondbtm.class.php(815): PluginFieldsField->prepareInputForAdd(Array)\n#1 /var/www/glpi/plugins/fields/front/field.form.php(14): CommonDBTM->add(Array)\n#2 {main}\n  thrown in /var/www/glpi/plugins/fields/inc/field.class.php on line 120, referer: https://demo.glpi-test.local/plugins/fields/front/container.form.php?id=1

Maybe I'm missing some PHP dependencies, any ideas? 

ThankU in advance

**Comment by orthagh** [comment]
tested on my 9.2 branch (#203), it seems the bug is not present anymore, wait for the next release

**Comment by trasher** [comment]
This seems not related to any PHP version; sounds more like the "common" missing class issue (which regenerate fixes).
Slosing for now, feel free to reopen if required.
