### ISSUE TITLE
Problème de droits

### ISSUE THREAD

**Issue by neeftarah** [pluginsGLPI/fields#2]
Bonjour,

N'ayant pas accès en modification à un élément, je peut malgré tout modifier les champs supplémentaires !
Les droits devrais être calqués sur les droits de l'objet et je ne devrais donc pas pouvoir les modifier.

GLPI 0.90
Fields 0.90-1.1
Objet ciblé : Groupes

Cordialement,
Jérémy

**Comment by neeftarah** [comment]
Bonjour,

Actuellement les droits sont gérer bloc par bloc.
Cela peut être déroutant et risquerais de passer à coté (ce qui à été mon cas).

Ne serait-il pas plus intéressant de matcher les droits des blocs sur les droits de l'objet sur lequel il est rajouté ?

Cordialement,
Jérémy

**Comment by tomolimo** [comment]
Hello,
This is a good remark, and we should speak about these rights.
I don't fully agree with you, as you may want to keep some field tabs from being modified for some profile, and open in read-write for others.
But we may imagine that when using the 'in dom' blocks we may use the rights of the current tab/object.
regards,
Tomolimo

**Comment by stonebuzz** [comment]
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
