### ISSUE TITLE
[0.91] No possibility mass update

### ISSUE THREAD

**Issue by awiamo** [pluginsGLPI/fields#20]
No possibility of a mass update by 'Actions->Update' when the type custom field is set other than drop-down list (text, multiline-text...).

https://www.dropbox.com/s/fd0eiyubqgc5eop/glpi-fields-mass-update-problem.jpg

GLPI 0.91(2016-03-02), Plugin Field (2016.03.02)

**Comment by Manu1400** [comment]
* Tested with GLPI 0.84 and a dropdown fields (on Computer) : OK (drodpdown is display, massive actions works)

**Comment by Manu1400** [comment]
Tested with last commit of GLPI and last commit of fields : OK (display dropdown in massive actions, massive actions works).

Can i have the list of all plugins ?

And more informations about your issue.

**Comment by Manu1400** [comment]
No have error in log. Need more informations about your configuration.

**Comment by Manu1400** [comment]
Can you give me **all** steps for reproduce this isssue ?

**Comment by awiamo** [comment]
I'm install new glpi and fields plugin from github (current version) and i've same problem. I need to test on a different server and gather details about the problem.

**Comment by awiamo** [comment]
Below configuration step by step:

#Get, install GLPI and Fields Plugin:
git clone https://github.com/glpi-project/glpi
git clone https://github.com/pluginsGLPI/fields

#Activate plugin Fields (Additional Fields)
Setup->Plugins

#Create new objects
Assets->Computers(+)->Name-> '01'
Assets->Computers(+)->Name-> '02'

#Create Additional Fields (+):

Bloc->Label: 'CF'
Bloc->Type: 'Insertion in the form (before save button)'
Bloc->Active: 'Yes'
Bloc->Associated item type: 'Assets - Computers'

#Create Fields (+):

Add a new field->Label: 'Multiline'
               ->Type: 'Text (multiple lines)'
			   ->Active 'Yes'
			   ->Read only 'No'

#Use actions to modify 2 objects (select computer - 01 and 02):

Assets->Computers: 'select computer - 01 and 02'
Actions->Action->Update
               -> CF - Multiline
			  !error!  -> 'No multiple lines form'

#When I create fields 'Single line' - everything works properly. When update multiline field like 'Comments' from orgin GLPI this also work correctly.
#Server1 configuration: Ubuntu LTS 14.04.04, Apache 2.4.7, PHP 5.5.9, MySQL 5.5.47
#Server2 configuration: Ubuntu LTS 14.04.04, Nginx 1.8.1-1, PHP 5.5.9, MySQL 5.5.47

Database and logs:
https://www.dropbox.com/s/mx5x3psf913xtu8/glpi_fields_issue.zip?dl=0

**Comment by Manu1400** [comment]
Issue was only on textarea, date and datetime fields. Fixed with the last commit.

Know issue : #25
