### ISSUE TITLE
Dropdown linked lists

### ISSUE THREAD

**Issue by bousahla** [pluginsGLPI/fields#200]
Hi, 
Can we create two dropdown lists linked between them with this plugin?
for example, the first list contains group's names (group1 , group2,..) and the second list contains the user's names contains in the group selectionned in the first list. 
if we choose "group 1" in the first list, the second list will contain only the users of the "group 1"

is there another plugin allow that or  can we configure it without any plugin?

thank you

**Comment by bousahla** [comment]
Bonjour,

J'ai toujours le même problème, pour les listes reliées entre elles.
peux-on avoir deux listes déroulantes dépendantes l'un à l'autre?
exemple: liste1 pour catégorie et liste2 pour sous catégorie.

**Comment by wawax** [comment]
Hello,

This is definitly not something in our roadmap.
If you're really willing to have it, please contact contact@teclib.com for a commercial proposal.

Thank you in advance.

**Comment by bousahla** [comment]
thank you
