### ISSUE TITLE
Add field type 'Data (user)' and dependent field 'Choose data'

### ISSUE THREAD

**Issue by msizec** [pluginsGLPI/fields#202]
When selecting Data (user), the list 'Choose data' will appear and let me select a User field (name, comment, picture, ...).
Thats the data that will be displayed.

Will let us display relative data when displaying a computer page for exemple.

This feature could be adapted to show data of Group, Entity, Label ...

**Comment by stonebuzz** [comment]
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
