### ISSUE TITLE
How to add custom fields to different entities?

### ISSUE THREAD

**Issue by kindaniel** [pluginsGLPI/fields#204]
I need to add custom fields to entity A, and another fields to entity B. 
The message is: 
"You cannot add several blocks with type 'Insertion in the form' on same object"

The same object is "Tickets", but every entities are using tickets.

Have a another way to fix this?

**Comment by Miminoux** [comment]
It might be related to https://github.com/pluginsGLPI/fields/issues/157

Using blocks in different entities is not really working.

**Comment by stonebuzz** [comment]
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Comment by mooseyfate** [comment]
I have just come across this issue also.
When trying to add a block in a ticket, I get the error message "You cannot add several blocks with type 'Insertion in the form' on same object".

I have one other block for tickets in a different entity.

GLPI version: 9.4.6
Fields version: 1.10.3
PHP: 7.2

**Comment by stonebuzz** [comment]
Actually, fields plugin can't add same block on itmetype for different entities.

It's a good feature, you can propose it by pull request or contacting us.

Best regards

**Comment by hugorn** [comment]
It's a good feature!
