### ISSUE TITLE
1.6.2 Unescaped character ' in field name

### ISSUE THREAD

**Issue by error500** [pluginsGLPI/fields#206]
In 1.6.2 
In the Field admin section, my traduction in french with a ' in the label is truncated in edit mode but not in display mode

**Comment by cedric-anne** [comment]
I just checked on GLPI 9.2.3 with Fields 1.7.0 and the label is well displayed in edit and display mode. Can you try to update and check if you still have this problem ?

**Comment by cedric-anne** [comment]
Hi,

As I cannot reproduce this issue, I close it.

Regards
