### ISSUE TITLE
Fix permissions issues (cannot create containers or fields) with 1.4.5

### ISSUE THREAD

**Issue by kchassaing** [pluginsGLPI/fields#208]
Hi,
Is there a possibility to know the part of code which was changed between the 1.5.0 and the 1.6.0 to **fix the permissions issues** with the previous version (the cross to add container unactivated and the permission error following the creation of a new field with an existant container) ?

I migrated from 0.80.5 to Glpi 0.90.5 in production not long ago (nearly one year) and I have not the possibility to had more than the version 1.4.5 of the plugin witch this version and also not the possibility to migrate to the last version of Glpi for the moment.*
Thank you.

**Comment by trasher** [comment]
I guess you are looking for: https://github.com/pluginsGLPI/fields/commit/029da51e1635995faa0c45ae7db1de0db1e36fd1

The whole changes: https://github.com/pluginsGLPI/fields/compare/1.5.0...1.6.0

It may not work with an old version of GLPI.
