### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by miodzio97** [pluginsGLPI/fields#209]
Hi,
I have GLPI 9.2 and when i try add custom field i have fatal error. What's wrong?

Fatal error: Uncaught Error: Class 'PluginFieldsPrintertest' not found in /usr/share/glpi/plugins/fields/inc/field.class.php:117 Stack trace: #0 /usr/share/glpi/inc/commondbtm.class.php(891): PluginFieldsField->prepareInputForAdd(Array) #1 /usr/share/glpi/plugins/fields/front/field.form.php(14): CommonDBTM->add(Array) #2 {main} thrown in /usr/share/glpi/plugins/fields/inc/field.class.php on line 117

![image](https://user-images.githubusercontent.com/32955663/31816147-6dfc9c5c-b58f-11e7-8189-cb61bc30f5d9.png)

**Comment by cedric-anne** [comment]
I just checked on GLPI 9.2.3 with Fields 1.7.0 and I did not reproduce this bug. Can you try to update and check if you still have this problem ?

**Comment by miodzio97** [comment]
on GLPI 9.2.3 the problem does not occur.
