### ISSUE TITLE
Cannot create fields in block

### ISSUE THREAD

**Issue by Vozzd** [pluginsGLPI/fields#215]
1. When I try to create field in a block, after applying field name and type, nothing happens - only blank page opens. In an apache log files I see php error in field.inc.php file:
_PHP Fatal error:  Class 'PluginFieldsComputertest' not found in /var/www/html/plugins/fields/inc/field.class.php on line 117, referer: http://glpi-test/plugins/fields/front/container.form.php?id=1_
2. When I try to remove plugin from GLPI, this procedure stops on page with "Mysql tables removing". In this case I see in apache log:
_PHP Fatal error:  Call to a member function query() on null in /var/www/html/plugins/fields/inc/container.class.php on line 474, referer: http://glpi-test/front/plugin.php_

In my case I use 1.70 version with GLPI 9.2.

**Comment by cedric-anne** [comment]
I take a look at the code and it seems that the plugin is not able to create some files. Can you check if apache user is able to create files inside `/var/www/html/files/_plugins/fields/front/` and `/var/www/html/files/_plugins/fields/inc/` ?

For the second problem, I made a fix on PR https://github.com/pluginsGLPI/fields/pull/246

**Comment by cedric-anne** [comment]
Hi,

Some fixes has been made to recreate missing files, so the first issue should be solved.

A fix has been made in PR #246 for the second issue.

Regards
