### ISSUE TITLE
interface simplifiée II le retour

### ISSUE THREAD

**Issue by romain1206** [pluginsGLPI/fields#216]
bonjour,

depuis mon passage en glpi 9.2.1 les champs supplémentaires ne s'affichent plus en interface simplifiée pour les utilisateurs.

par compte un utilisateur en super admin/admin et que je change le profil en post-only j'ai bien mes champs

en mode debug je n'ai pas d'erreurs

merci de votre aide

j'avais déja eu le cas en précédente version https://github.com/pluginsGLPI/fields/issues/179

glpi: 9.2.1
fields: 1.7.0

**Comment by trasher** [comment]
Duplicates #213
