### ISSUE TITLE
Attempting to delete a block throws an undefined variable error (DB)

### ISSUE THREAD

**Issue by Ewanuk** [pluginsGLPI/fields#217]
1) Navigate to Setup > Additionnal fields
2) Select any existing block
3) Click "Delete Permanently", confirm the action

Error log reports the following error:
PHP Notice: Undefined variable: DB in /var/www/html/glpi/plugins/fields/inc/container.class.php at line 474

the DB global doesn't appear to be getting correctly set. Could this be a configuration issue on our end?

We have the following plugins installed:
Additionnal fields
GLPI Modifications
More Reporting
More ticket

However, only Additionnal fields is enabled.

**Comment by cedric-anne** [comment]
Should be fixed by https://github.com/pluginsGLPI/fields/pull/246.
