### ISSUE TITLE
Field  label in views

### ISSUE THREAD

**Issue by Reguardo** [pluginsGLPI/fields#22]
How to change column label in example if i add a fields too ticket view a i get long  names
Plugins- Block name - field name 
It's  very long in my case.
When adding field  or searching its very useful but in column view its going out of screen when i add more filelds.
How to work around in quick way and maybe a request to add a next version: when we add field the add the name on view. 
Do new fields have same msgid to add in translation file ?

**Comment by trasher** [comment]
I do not know how that was managed previously, but actually, when you add a field on ticket, you got just the file name displayed.
As for translation; it's been added recently.
