### ISSUE TITLE
Use Fields plugin with Fusion Inventory

### ISSUE THREAD

**Issue by mohierf** [pluginsGLPI/fields#222]
A problem is raised when trying to use the Fields plugin with the Fusion Inventory plugin.

The FusionInventoy plugin uses a FusionInventoryComputer class that inherits from the GLPI Computer base class. When Glpi builds a request mixing fields from base Computer and Fields plugin, the Fields plugin is using an item type that is FusionInventoryComputer whereas the defined fields are set on the Computer.

A simple fix in the Fields plugin would allow to make both plugins work together.

I will submit a PR for this

This solution looks like the most simple and integrated to me, but any other suggestion is welcomed!

**Comment by mohierf** [comment]
I found a workaround in the FusionInventory plugin to avoid some modifications in the Fields plugin. I am closing this issue

**Comment by grego1981** [comment]
What is your workaround? Whenever I have additial fields enabled I cannot view many of the fusion menu. 

Could you help me?
