### ISSUE TITLE
Blocker: Not able to delete fields

### ISSUE THREAD

**Issue by shyamsoundar18** [pluginsGLPI/fields#228]
I am not able to delete fields associated to computers etc. It displays blank page

GLPI : 9.2.1
Fields: 1.7.0

Error Message: 

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Migration::__construct(), 0 passed in /var/www/helpdesk/files/_plugins/fields/inc/computerasset.class.php on line 55 and exactly 1 expected in /var/www/helpdesk/inc/migration.class.php:73\nStack trace:\n#0 /var/www/helpdesk/files/_plugins/fields/inc/computerasset.class.php(55): Migration->__construct()\n#1 /var/www/helpdesk/plugins/fields/inc/field.class.php(146): PluginFieldsComputerasset::removeField('plugin_fields_i...')\n#2 /var/www/helpdesk/inc/commondbtm.class.php(1450): PluginFieldsField->pre_deleteItem()\n#3 /var/www/helpdesk/plugins/fields/front/field.form.php(22): CommonDBTM->delete(Array, 1)\n#4 {main}\n  thrown in /var/www/helpdesk/inc/migration.class.php on line 73,

**Comment by cedric-anne** [comment]
Fixed by https://github.com/pluginsGLPI/fields/pull/245.
