### ISSUE TITLE
[9.1.1+1.4.4] Using API does not update history log

### ISSUE THREAD

**Issue by pVesian** [pluginsGLPI/fields#229]
Hi,

There's a problem when using the GLPI API. When I make a call to update a field in a change for example, the update is made but not logged in the change's history tab. Using GLPI 9.1.1 and Fields 1.4.4.

Data: `POST /apirest.php/PluginFieldsChangeType{"input":[{"items_id":1, plugin_fields_statutprocessusfielddropdowns_id": 5, "itemtype":"Change"}]}`

Example of a field updated by hand:
![screenshot fr-2018-02-16-10-30-42](https://user-images.githubusercontent.com/3509962/37140853-6310f414-22b3-11e8-9e2b-9afe05fd66a5.png)

![screenshot fr-2018-02-16-10-28-18](https://user-images.githubusercontent.com/3509962/37140908-9354b9b2-22b3-11e8-82d4-b6853a22ec69.png)

![screenshot fr-2018-02-16-10-28-53](https://user-images.githubusercontent.com/3509962/37140913-96b34e02-22b3-11e8-9eaf-06e70fbebc44.png)

Thanks!

**Comment by trasher** [comment]
There is nothing about the API on the plugin, maybe a core issue.
