### ISSUE TITLE
Le plugin GESTION D'OBJETS

### ISSUE THREAD

**Issue by Manu97139** [pluginsGLPI/fields#23]
bonjour,
Merci de pour ce plugin très intéressant, mais est il possible d'y intégrer les objets personnalisés du parc qui ont été insérés par le plugin Gestion d'objets.

Exemple: Copieurs, Traceurs, Tableaux numériques.

**Comment by Manu1400** [comment]
A hook was added in the last commit : https://github.com/pluginsGLPI/fields/commit/f0d476c3a58165250b362d5365cc53019e6d336b

Now a plugin (in this code) can declare class(es) can be used by plugin fields.

**Comment by Manu1400** [comment]
Fix URL in fields (for **futur** genericobjet) and best display :

https://github.com/pluginsGLPI/fields/commit/92811856b4b11518eb7ccf8955cfd9d9d0178298

**Comment by Manu1400** [comment]
Note : Les champs supplémentaires n'apparaissent pas dans l'onglet Prévisualisation (dans genericobject). Le code ne sera pas modifié (ne peut être modifié) pour cela.

**Comment by Manu1400** [comment]
Code added on genericobject for support that in my dev branch : 

View last commits in : 
https://github.com/TECLIB/genericobject/pull/84

**Comment by satyan01** [comment]
but it is not available

**Comment by orthagh** [comment]
closing in favor of #197
