### ISSUE TITLE
The added field does not appear in the tab named "Solution"

### ISSUE THREAD

**Issue by bguerlot** [pluginsGLPI/fields#230]
A new block has been created and inserted before the "Save" button of the tab "Solution"
Find attached some screenshots, of the configuration and a screenshot of the tab "Solution" where the field is missing

GLPI version : 9.2.1
Plugin version : 1.7.0

![image](https://user-images.githubusercontent.com/25660535/37145678-ca3a6f7c-22c1-11e8-8bdf-413279db2f5a.png)
![image](https://user-images.githubusercontent.com/25660535/37145769-111c3222-22c2-11e8-8571-26e2d8be700a.png)

![image](https://user-images.githubusercontent.com/25660535/37145783-1e264c78-22c2-11e8-9332-6525aa5b19f1.png)

**Comment by nam23690** [comment]
I have the same problem.

**Comment by pukllana** [comment]
I have the same problema... any idea the solution???

**Comment by trasher** [comment]
Duplicates https://github.com/pluginsGLPI/fields/issues/236
