### ISSUE TITLE
Can't add Fields to Management/lines  ?

### ISSUE THREAD

**Issue by ejaecker** [pluginsGLPI/fields#232]
Hi, 

It looks like it's not possible to add custom fields to Lines screen.
![image](https://user-images.githubusercontent.com/26645521/37154069-1eb832ec-22df-11e8-992f-215f2a1a3d36.png)

Is it by design ? 

> Setup : Glpi 9.2.2 / PHP 7.2.2 / IIS10 / MySQL 5.7.19

**Comment by trasher** [comment]
Each "linkable" item type has to be added by hand. There are several issues on core side that prevents any automation.

**Comment by cedric-anne** [comment]
Done in #279 .
