### ISSUE TITLE
Error 500 when I add a new fields 

### ISSUE THREAD

**Issue by usrqmor** [pluginsGLPI/fields#233]
Hello,

I've installed the plugin fields on my test GLPI and I've no problem. I try to do the same on my prod GLPI but I get an error 500 when I add a new field in a block.
I search on the github and find this subject #79. 

I check the log in php-error.log and sql-error.log and find nothing. I get this errors with Apache :

> [Mon Mar 12 08:21:17.365644 2018] [:error] [pid 27982] [client 192.168.*.254:35029] script '/var/www/glpi/license.php' not found or unable to stat
> [Mon Mar 12 08:21:17.395530 2018] [:error] [pid 27843] [client 192.168.*.254:35030] script '/var/www/glpi/license.php' not found or unable to stat
> [Mon Mar 12 08:24:11.626661 2018] [:error] [pid 27997] [client 192.168.*.254:35189] PHP Fatal error:  Class 'PluginFieldsSoftwarelicenseperiodicite' not found in /var/www/glpi/plugins/fields/inc/field.class.php on line 117, referer: http://glpi/plugins/fields/front/container.form.php?id=1
> [Mon Mar 12 08:24:16.807990 2018] [:error] [pid 28067] [client 192.168.*.254:35233] PHP Fatal error:  Call to a member function getField() on null in /var/www/glpi/plugins/fields/inc/field.class.php on line 375, referer: http://glpi/plugins/fields/front/field.form.php
> [Mon Mar 12 08:24:34.333035 2018] [:error] [pid 28068] [client 192.168.*.254:35235] PHP Fatal error:  Class 'PluginFieldsSoftwarelicenseperiodicite' not found in /var/www/glpi/plugins/fields/inc/field.class.php on line 117, referer: http://glpi/plugins/fields/front/container.form.php?id=1
> [Mon Mar 12 08:32:21.040153 2018] [:error] [pid 28288] [client 192.168.*.254:36029] PHP Fatal error:  Call to a member function query() on null in /var/www/glpi/plugins/fields/inc/container.class.php on line 474, referer: http://glpi/front/plugin.php
> [Mon Mar 12 08:33:38.406749 2018] [:error] [pid 28351] [client 192.168.*.254:36112] PHP Fatal error:  Call to a member function query() on null in /var/www/glpi/plugins/fields/inc/container.class.php on line 474, referer: http://glpi/front/plugin.php
> [Mon Mar 12 08:41:15.089192 2018] [:error] [pid 28583] [client 192.168.*.254:36685] PHP Fatal error:  Class 'PluginFieldsSoftwarelicenseperiodicite' not found in /var/www/glpi/plugins/fields/inc/field.class.php on line 117, referer: http://glpi/plugins/fields/front/container.form.php?id=1

I check the SQL table I've 4 tables : 
- glpi_plugin_fields_containers
- glpi_plugin_fields_fields
- glpi_plugin_fields_labeltranslations
- glpi_plugin_fields_profiles

I try to delete the table and the folder then reinstall but it didn't work.

This is my system :

Informations sur le système, l'installation et la configuration
```

 
GLPI 9.2 ( => /var/www/glpi)

Server
 
Operating system: Linux OR-WEB-GLPI 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64
PHP 5.6.30-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	bcmath, bz2, calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json,
	ldap, libxml, mbstring, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="64M" safe_mode="" session.save_handler="files"
	upload_max_filesize="64M" 
Software: Apache/2.4.10 (Debian) (Apache/2.4.10 (Debian) Server at 192.168.1.5/glpi Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
Server Software: (Debian)
	Server Version: 5.5.54-0+deb8u1
	Server SQL Mode: 
	Parameters: glpi@192.168.1.5/glpi
	Host info: 192.168.1.6 via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
/var/www/glpi/config : OK
/var/www/glpi/files : OK
/var/www/glpi/files/_dumps : OK
/var/www/glpi/files/_sessions : OK
/var/www/glpi/files/_cron : OK
/var/www/glpi/files/_graphs : OK
/var/www/glpi/files/_lock : OK
/var/www/glpi/files/_plugins : OK
/var/www/glpi/files/_tmp : OK
/var/www/glpi/files/_rss : OK
/var/www/glpi/files/_uploads : OK
/var/www/glpi/files/_pictures : OK
/var/www/glpi/files/_log : OK
Web access to files directory is protected : OK

Libraries
 
htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed)
phpCas version 1.3.5 in (/var/www/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.24 in (/var/www/glpi/vendor/phpmailer/phpmailer)
SimplePie version 1.5 in (/var/www/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.13 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)

LDAP directories
 
Server: 'ldap://192.168.1.8', Port: '389', BaseDN: 'OU=Users,OU=domain,DC=domain,DC=fr', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'service.ldap@domain.fr', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (mail@smtp.mandrillapp.com)

Mails receivers
 
Name: 'glpi.web_commandes@domain.info' Active: Yes
	Server: '{outlook.office365.com:993/imap/ssl/novalidate-cert/notls}Web_Commandes' Login: 'service.monitoring@domain.fr'
		Password: Yes
Name: 'glpi.web_doublons@domain.info' Active: Yes
	Server: '{outlook.office365.com:993/imap/ssl/validate-cert/notls}Web_Doublons' Login: 'service.monitoring@domain.fr'
		Password: Yes
Name: 'presta1@domain.fr' Active: Yes
	Server: '{outlook.office365.com:993/imap/ssl/validate-cert/notls}presta1' Login: 'service.monitoring@domain.fr'
		Password: Yes
Name: 'presta2@domain.info' Active: Yes
	Server: '{outlook.office365.com:993/imap/ssl/validate-cert/notls}presta2' Login: 'service.monitoring@domain.fr' Password:
		Yes
Name: 'presta3@domain.info' Active: Yes
	Server: '{outlook.office365.com:993/imap/ssl/validate-cert/notls}presta3' Login: 'service.monitoring@domain.fr' Password:
		Yes
Name: 'monitoring.erp@domain.info' Active: Yes
	Server: '{outlook.office365.com:993/imap/ssl/validate-cert/notls}erp' Login: 'service.monitoring@domain.fr'
		Password: Yes
Name: 'salaries@domain.info' Active: No
	Server: '{outlook.office365.com:993/imap/ssl/validate-cert/notls}Salaries' Login: 'service.monitoring@domain.fr' Password:
		Yes

Plugins list
 
	news                 Name: Alertes                        Version: 1.3.4      State: Enabled
	fields               Name: Champs supplémentaires         Version: 1.7.0      State: Enabled
	behaviors            Name: Comportements                  Version: 2.0.0      State: Enabled
	formcreator          Name: Formulaires                    Version: 2.6.0      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.2+1.0    State: Enabled
	genericobject        Name: Gestion d'objets               Version: 2.5.0      State: Enabled
	mod                  Name: GLPI Modifications             Version: 1.1.4      State: Enabled
	browsernotification  Name: Notification de Navigateur     Version: 1.1.9      State: Enabled
	dashboard            Name: Tableau de bord                Version: 0.8.8      State: Enabled

```

Thanks in advance.

**Comment by trasher** [comment]
«PHP Fatal error: Class 'PluginFieldsSoftwarelicenseperiodicite' not found»

You need to regenerate class files.

**Comment by usrqmor** [comment]
Hello,

I solved my problem after I disabled all other plugins and a proper reinstall of the plugin. I forgot to comment after solving my problem.
What do you mean by "regenerate class file" ?

Thanks

**Comment by trasher** [comment]
> What do you mean by "regenerate class file" ?

The " Regenerate container files" button :)

Anyways, it's fine if your problem is solved.

**Comment by dytrip77** [comment]
> Hello,
> 
> I solved my problem after I disabled all other plugins and a proper reinstall of the plugin. I forgot to comment after solving my problem.
> What do you mean by "regenerate class file" ?
> 
> Thanks

Hi, I'm having the same issue. Could you please elaborate on the step above?

I did try disable other plugins and proper reinstall but to no avail.

Thanks

**Comment by usrqmor** [comment]
Hi @dytrip77,
After you disabled all the plugins, you have to delete field folder in the GLPI Plugin folder (in www\glpi\plugins\).
Then you reload the folder of the plugin and you can enable the plugin on GLPI. That's what I've done to solve my problem.
