### ISSUE TITLE
Ability to add full fields

### ISSUE THREAD

**Issue by joaovitorcavalcante** [pluginsGLPI/fields#235]
The following error occurs when adding a certain number of fields in the plugin.

0 multiple alter in glpi_plugin_fields_ticketcamposcustomizados - 
Database query error: ALTER TABLE `glpi_plugin_fields_ticketcamposcustomizados` ADD `ndamatriculafield` VARCHAR(255) DEFAULT NULL - Erro é Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**Comment by trasher** [comment]
Just use "Text (multiples lines)" and you wll have  TEXT column.
