### ISSUE TITLE
Not show fields in tab Solution

### ISSUE THREAD

**Issue by nam23690** [pluginsGLPI/fields#236]
Dear all,
Please help me fix error. Custom new field show in Insertion in the form of a specific tab (before save button)  Tab : Solution
![image](https://user-images.githubusercontent.com/30283615/38133215-7873534c-3438-11e8-9cc6-a4317b6fb8a8.png)
But not show in
![image](https://user-images.githubusercontent.com/30283615/38133382-2b3b2c20-3439-11e8-9021-2ba4ac1d3206.png)
Thanks

**Comment by pukllana** [comment]
I have the same problem... do you find the solution???

**Comment by stonebuzz** [comment]
Duplicate with #328

I'll close this issue in favor of the other thread.

Best regards
