### ISSUE TITLE
Fields empty

### ISSUE THREAD

**Issue by titidelaff** [pluginsGLPI/fields#237]
Hi,

I added two mandatory fields in the tickets, it happens some times when we open the tickets that the fields are empty, after reloading the page the content appears.

**Comment by Twentycents84** [comment]
Same for me ! GLPI 9.3 and Plugin .1.8.2
And in simply interface i have an error in field.class line 547
regards

**Comment by stonebuzz** [comment]
Hi @titidelaff 

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
