### ISSUE TITLE
[Massive action] No 'update' massive action in Profile

### ISSUE THREAD

**Issue by Manu1400** [pluginsGLPI/fields#24]
In Profile list page, the massive action 'update' is forbidden by core of GLPI.

We can't update a field in a new tab in Profile with massive action because don't gave 'update' massive action in this itemtype.

**Comment by stonebuzz** [comment]
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
