### ISSUE TITLE
Impossible d'ajouter un block / can't add  block

### ISSUE THREAD

**Issue by mkmen** [pluginsGLPI/fields#241]
Bonjour,
j'ai ajouter le plugin fields mais lorsque que je vais sur l'onglet additional fields je ne peux pas cliquer que le + pour ajouter un block. Il y aurait une solution?
Hello,
i add plugin fields but when i try to add block i can't click on + button, There is an issue?

Info system : 
- server GLPI (0.90.5) : Centos 7, php 5.6 plugins fields 90+1.3
- server db : Centos 7, mysql.

thanks for your help.

**Comment by cedric-anne** [comment]
Hello,
You are using a really old version of GLPI and Fields. Can you try to upgrade to latest versions and check if you still have the problem ?

**Comment by cedric-anne** [comment]
Hi,

As I have no feedback, I close this issue.

Regards
