### ISSUE TITLE
Can't add a new field in latest Chrome

### ISSUE THREAD

**Issue by Alwaysin** [pluginsGLPI/fields#259]
In Chrome 67.0.3396.99, nothing happens when clicking on "add a new field" (supposedly, because I'm on a french language). It works on Firefox.

What is displayed on the console:
```
Uncaught ReferenceError: viewAddField11011338814 is not defined
    at <anonymous>:1:1
(anonymous) @ VM2235:1
```

**Comment by cedric-anne** [comment]
Hi,

Maybe you have something that prevent trigerring of the ready document event on Chrome. Could you try with patch b5c313124315d19328c469fb6db278f583d2e3af ? Waiting for this event seems not useful in this case, as it is just a function definition.

Regards

**Comment by Alwaysin** [comment]
Hi,

I'm now on Version 68.0.3440.75 and it works wihout further modification :)
