### ISSUE TITLE
[Infocom] No save datas of fields in Infocom tab

### ISSUE THREAD

**Issue by Manu1400** [pluginsGLPI/fields#26]
1/ Install fields
2/ Activate fields
3/ Create a field 'nb' (text) in Infocom tab (Financial informations) in Computer
4/ Create a Computer and in this computer item Activate Infocom
4/ Put "15" in nb field and save

Result : No data is saved in database !

fields : 0.90-1.1 (last commit of git)
GLPI : 0.91 (last commit of git)

**Comment by Manu1400** [comment]
Quick solution : Don't permit to add fields (with domtab) in Infocom tab ?

**Comment by Manu1400** [comment]
Sended by browser when submit the update :
(...)
_plugin_fields_type:domtab
nbfield:15

**Comment by Manu1400** [comment]
Because this code don't return 'Infocom' in $itemtypes, fields of Infocom is not saved.

      //Retrieve dom container
      $itemtypes = PluginFieldsContainer::getUsedItemtypes();

**Comment by Manu1400** [comment]
**domtab => not supported**

**Comment by trasher** [comment]
Adding fields content on this tab is no longer allowed with latests releases.
