### ISSUE TITLE
Not Compatible with SimCard Plugin

### ISSUE THREAD

**Issue by Anakin3456** [pluginsGLPI/fields#262]
Dear Sir or Maddam, 

unfortunately your Plugin is not Compatible with the Sim Cards Plugin http://plugins.glpi-project.org/#/plugin/simcard

Can you Please fix this so i can also add the fields there?

Many Thanks 

Marco

**Comment by trasher** [comment]
Simcard plugin is part of core since 9.2; and is therefore discontinued.
