### ISSUE TITLE
Problem with dropdowns when using a symoblic link for files folder

### ISSUE THREAD

**Issue by Nexoz** [pluginsGLPI/fields#267]
Hi,

When we're trying to show a dropdown page from your plugin, a white plage occurs and a runtime exception is logged : 
```
Thu Aug 02 13:45:14.494614 2018] [php7:error] [pid 19540] [client 10.89.14.1:52128] PHP Fatal error:  Uncaught RuntimeException: Attempt to load unsecure or missing /data/glpi/glpi-9.2.3/files/_plugins/fields/front/antivirussolutionfielddropdown.php! in /data/glpi/glpi-9.2.3/plugins/fields/front/commondropdown.php:11\nStack trace:\n#0 {main}\n  thrown in /data/glpi/glpi-9.2.3/plugins/fields/front/commondropdown.php on line 11, referer: https://support-toulouse.bs.fr.myatos.net/plugins/fields/front/field.form.php?id=1
```

This is because of the use of the realpath function in _front/commondropdown.php_ (or _front/commondropdown.form.php_) with a symbolic link for our `files` folder in GLPI, which makes the `$realpath` different than the `$frontpath` in the following code : 
```php
$path = PLUGINFIELDS_FRONT_PATH . '/' . $_REQUEST['ddtype'] . '.php';
$realpath = str_replace( "\\", "/", realpath($path));
$frontpath = str_replace( "\\", "/", PLUGINFIELDS_FRONT_PATH );
if (strpos($realpath, $frontpath) === 0) {
    include_once $path;
} else {
    throw new \RuntimeException('Attempt to load unsecure or missing ' . $path .'!');
}
```
Which is giving, when logged in our case, those 2 variables : 

```
realpath: /data/glpi/glpi_files/_plugins/fields/front/antivirussolutionfielddropdown.php

frontpath: /data/glpi/glpi-9.2.3/files/_plugins/fields/front
```

I'm using GLPI v9.2.4 and Fields v1.7.3.

Thank you in advance for your consideration.

**Comment by trasher** [comment]
Why do you use a symbolic link for files folder? It is possible to configure the path for a while.

**Comment by trasher** [comment]
See https://glpi-install.readthedocs.io/en/latest/install/index.html#files-and-directories-locations

GLPI (and not only the plugin) is not designed to work with symbolic links. You should use framework capabilities instead. using sympbolic links with crrent code base will probably cause several issues that would be hard to fix.
