### ISSUE TITLE
Bug Plugin fields 1.8.1

### ISSUE THREAD

**Issue by rupter** [pluginsGLPI/fields#275]
Hi everybody,

I install fields plugin in GLPI 9.3.0 but i see some problem.

When i put on this 
![image](https://user-images.githubusercontent.com/12794203/44518934-eaa42d00-a6cb-11e8-92cb-84a87f5d006f.png)
I have white page.

And when i want delete this fields
![image](https://user-images.githubusercontent.com/12794203/44519447-5c30ab00-a6cd-11e8-9d8c-85f7d78ff496.png)
i have just background ...

And when i create new "champ" on "bloc", i have white page too....
![image](https://user-images.githubusercontent.com/12794203/44519320-00662200-a6cd-11e8-9268-4345911a64e0.png)

I don't find why ....
If somebody could help me please, it would be very pleasant.

Cordialy,

Marvin.

**Comment by cedric-anne** [comment]
Hi,

Can you check in your logs (in system logs and in `glpi/files/_log/*` if you have a trace of an error ? 

Regards

**Comment by rupter** [comment]
I find this in php-errors.log :

Refresh bloc :

[2018-08-23 13:04:45] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:586                          error_log()
  inc/crontask.class.php:835                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"75@bt-srv-glpi","mem_usage":"0.027\", 2.61Mio)"}
[2018-08-23 13:04:54] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): file_put_contents(/var/www/glpi/files/_plugins/fields/inc/computerclient.class.php): failed to open stream: Permission denied
  Backtrace :
  :
  plugins/fields/inc/container.class.php:418         file_put_contents()
  plugins/fields/setup.php:249                       PluginFieldsContainer::generateTemplate()
  plugins/fields/front/regenerate_files.php:7        plugin_fields_checkFiles()
  {"user":"75@bt-srv-glpi","mem_usage":"0.021\", 1.79Mio)"}

Delete fields :

[2018-08-23 13:08:04] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 289
getFromDBByCrit expects to get one result, 2 found!  {"user":"6@bt-srv-glpi","mem_usage":"0.358\", 7.25Mio)"}

New "champ" in "bloc" :

[2018-08-23 13:10:13] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:586                          error_log()
  inc/crontask.class.php:835                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"75@bt-srv-glpi","mem_usage":"0.036\", 2.61Mio)"}
[2018-08-23 13:11:50] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): file_put_contents(/var/www/glpi/files/_plugins/fields/inc/computerip.class.php): failed to open stream: Permission denied
  Backtrace :
  :
  plugins/fields/inc/container.class.php:418         file_put_contents()
  plugins/fields/inc/container.class.php:393         PluginFieldsContainer::generateTemplate()
  inc/commondbtm.class.php:975                       PluginFieldsContainer->post_addItem()
  plugins/fields/front/container.form.php:12         CommonDBTM->add()
  {"user":"75@bt-srv-glpi","mem_usage":"0.036\", 2.63Mio)"}

**Comment by cedric-anne** [comment]
Your web server running GLPI must have writing permissions on `/var/www/glpi/files/*`. It is mandatory as fields plugin needs to create files corresponding to each bloc you want to create.

Regards

**Comment by rupter** [comment]
My server have already all permissions :
/var/www/glpi/files/*
```
drwxr-xr-x  2 root root  4096 août   2 12:22 ajax
drwxr-xr-x 18 root root  4096 août   2 12:06 Ancien
-rw-r--r--  1 root root 51023 août   2 12:22 apirest.md
-rw-r--r--  1 root root  1370 août   2 12:22 apirest.php
-rw-r--r--  1 root root  1337 août   2 12:22 apixmlrpc.php
-rw-r--r--  1 root root  7979 août   2 12:22 CHANGELOG.md
drwxrwxrwx  2 root root  4096 août  10 10:34 config
-rw-r--r--  1 root root 18092 août   2 12:22 COPYING.txt
drwxr-xr-x  4 root root  4096 août  10 14:12 css
drwxrwxrwx 15 root root  4096 août  10 10:34 files
drwxr-xr-x  2 root root 24576 août   2 15:42 front
drwxr-xr-x  3 root root 28672 août   2 12:22 inc
-rw-r--r--  1 root root  7378 août   2 12:22 index.php
drwxr-xr-x  3 root root  4096 août   2 17:18 install
drwxr-xr-x  2 root root  4096 août   2 12:22 js
drwxr-xr-x 15 root root  4096 août   2 12:22 lib
drwxr-xr-x  2 root root  4096 août   2 12:22 locales
drwxr-xr-x  7 root root  4096 août   7 12:25 pics
drwxr-xr-x 10 root root  4096 août   6 15:20 plugins
-rw-r--r--  1 root root  5664 août   2 12:22 README.md
drwxr-xr-x  3 root root  4096 août   2 12:22 scripts
drwxr-xr-x  2 root root  4096 août   2 12:22 sound
-rw-r--r--  1 root root  6421 août   2 12:22 status.php
drwxr-xr-x 17 root root  4096 août   2 12:22 vendor
```
Or need www-data on files ?

**Comment by cedric-anne** [comment]
It needs write permission recursivly on the files directory.

Maybe giving ownership of `/var/www/glpi` to `www-data` could be a better idea thant givin access to everyone, but it depends on you server configuration.

**Comment by rupter** [comment]
Thanks you for your quickly answer.

i change permission of files but is a same.
`drwxrwxrwx 15 www-data www-data  4096 août  10 10:34 files`

and in files but is a same :

```
drwxrwxrwx 2 www-data www-data   4096 août  10 10:34 _cache
drwxrwxrwx 2 www-data www-data   4096 août  10 10:34 _cron
drwxrwxrwx 2 www-data www-data   4096 août  10 10:34 _dumps
drwxrwxrwx 2 www-data www-data   4096 août  10 10:34 _graphs
drwxrwxrwx 2 www-data www-data   4096 août  10 10:34 _lock
drwxrwxrwx 2 www-data www-data   4096 août   6 08:35 _log
drwxrwxrwx 2 www-data www-data   4096 août  10 16:21 _pictures
drwxrwxrwx 6 www-data www-data   4096 août  10 10:34 _plugins
drwxr-xr-x 3 www-data www-data   4096 août   3 16:36 PNG
drwxrwxrwx 2 www-data www-data   4096 août  10 10:34 _rss
drwxrwxrwx 2 www-data www-data 581632 août  23 14:33 _sessions
drwxrwxrwx 2 www-data www-data   4096 août  10 16:21 _tmp
drwxrwxrwx 2 www-data www-data   4096 août  10 10:34 _uploads

```

**Comment by cedric-anne** [comment]
Did you change permissions recursivly ?

Trace says: `file_put_contents(/var/www/glpi/files/_plugins/fields/inc/computerclient.class.php): failed to open stream: Permission denied`. If everything under files is with 777 chmod, I do not understant how it is possible.

**Comment by rupter** [comment]
Now plugins works.

I change permission recursivly of :

drwxrwxrwx 15 www-data www-data 4096 août 10 10:34 files
drwxrwxrwx  3 www-data www-data 28672 août   2 12:22 inc

But i always this error :

```
[2018-08-23 14:41:46] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): error_log(/var/www/glpi/files/_log/cron.log): failed to open stream: Permission denied
  Backtrace :
  :
  inc/toolbox.class.php:586                          error_log()
  inc/crontask.class.php:835                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()
  {"user":"75@bt-srv-glpi","mem_usage":"0.031\", 2.64Mio)"}
```

**Comment by rupter** [comment]
Is good now.
I change permission to :
`chmod 777 files/_log/*`

But i stay 1 warning 
```
[2018-08-23 14:50:05] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 289
getFromDBByCrit expects to get one result, 2 found!  {"user":"6@bt-srv-glpi","mem_usage":"0.470\", 7.26Mio)"}


```

**Comment by cedric-anne** [comment]
Is there something else in your log ?
This trace is very generic and I cannot find where does it comes from.

**Comment by rupter** [comment]
No sorry i have just this ....
