### ISSUE TITLE
Question : How to use data injection with fields

### ISSUE THREAD

**Issue by lynch4fr** [pluginsGLPI/fields#286]
Hi, sorry i don't understand how to use "Data injection" witch "Fields"
I create a new field "Unite" 
I create a Model management (data injection) but in "Type of data to import" i don't find "Unite" ? I don"t know why ? 

GLPI 9.3.1
Fields 1.8.2
Data injection 2.6.3

Thanks a lot

**Comment by stonebuzz** [comment]
Hi @lynch4fr 

Can you check with latest version.

Best regards
