### ISSUE TITLE
Sharing a dropdown list between mutliple blocs

### ISSUE THREAD

**Issue by kabassanov** [pluginsGLPI/fields#29]
Hi,

I created a bloc per itemtype (because I can't do otherwise). In each bloc I created a dropdown list with the same name and it seems that this allows to create a kind of shared dropdown list that can be filled once with the desired items. Do you think this is a side effect, or it should really work this way?

Thanks.

**Comment by orthagh** [comment]
Hello @kabassanov 

Since last release, you can do one bloc for multiple itemtypes/
Anyways, yes, you can do a shared dropdown between itemtypes. It's intended and don't have any side effects
