### ISSUE TITLE
php-errors.log flooded with warnings

### ISSUE THREAD

**Issue by ThomasLoupiac** [pluginsGLPI/fields#292]
Hello,

While monitoring the installation done by a member of my team of the plugin fields, I stumbled across this error : 

2018-12-05 10:50:18 [XXX]
  From Toolbox::deprecated() in /var/www/glpi/inc/toolbox.class.php line 477
  Zend\Loader\SplAutoloader has been dropped from GLPI.
2018-12-05 10:50:18 [XXX]
  Backtrace :
  inc/toolbox.class.php:478                          Toolbox::backtrace()
  inc/autoload.function.php:321                      Toolbox::deprecated()
  :                                                  glpi_autoload()
  plugins/fields/inc/autoload.php:5                  spl_autoload_call()
  plugins/fields/setup.php:70                        include_once()
  inc/plugin.class.php:145                           plugin_init_fields()
  inc/includes.php:118                               Plugin::load()
  ajax/notifications_ajax.php:3                      include()

3Mo of log in 10 minutes with this error only.

Could you help me ?

Thanks.
Thomas

**Comment by trasher** [comment]
You certainly use an old version. This has been solved in https://github.com/pluginsGLPI/fields/commit/51553d163023073caafaffa8fdb4d453ce8c1920

Consider updating to the latest stable release anyways :)
