### ISSUE TITLE
[feature/bug] Can't use with "Generic Object Management" Plugin

### ISSUE THREAD

**Issue by jechange** [pluginsGLPI/fields#293]
Hi, 
We use the "Generic Objects Management" plugins for create new object not supported by GLPI.

We discovered your plugins and we would like to use it, but we cannot use it with "Generic Objects Management" because, we can't associate a new Fields for a Generic Object, because the don't appear in " Associate Element Type"

**Comment by paulopires1974** [comment]
Hi,
I have the same problem. I would like to know if Jechange found any solution?

**Comment by tinchonet** [comment]
Same here. Please help!!!

**Comment by stonebuzz** [comment]
Hi @jechange 

plugin genericobject already implement is own custom field system

see documentation -> https://glpi-plugins.readthedocs.io/en/latest/genericobject/index.html

I'm closing this issue, feel free to continue discussion here if you want.

**Comment by Megachip** [comment]
> Hi @jechange
> 
> plugin genericobject already implement is own custom field system
> 
> see documentation -> https://glpi-plugins.readthedocs.io/en/latest/genericobject/index.html
> 
> I'm closing this issue, feel free to continue discussion here if you want.

Thx... will check the following:
https://glpi-plugins.readthedocs.io/en/latest/genericobject/index.html#add-new-fields
