### ISSUE TITLE
use of Session::haveRight('user', 'r')

### ISSUE THREAD

**Issue by ctresvaux** [pluginsGLPI/fields#296]
Hi,
I use your plugin in my glpi project. 
I noticed thant there is a call to the core function Session::haveRight('user', 'r') with deprecated syntax in the file inc/field.class.php
It causes notices in php-errors log file.

I think the right syntax is now Session::haveRight('user', READ)

Regards
Christian

**Comment by cedric-anne** [comment]
Fixed by 8877cf0e13d4cefae7f0a9a35f6304c49333fc5d
