### ISSUE TITLE
Email Notification with custom fields

### ISSUE THREAD

**Issue by sworlls** [pluginsGLPI/fields#298]
Hello Guys, good night.
I saw a post but didnt see any update in regards to that.
I am facing issues to use the data into the aditional fields into the email alert of GLPI so i can send by email the aditional information to customer. Is that a thing possible to be done or this feature is still not available? thank you and have a great new year.

**Comment by juveboss** [comment]
Hello everybody, 

this feature is in the new version of the plugin? for glpi 9.4?

Thanks

**Comment by juveboss** [comment]
Hello..

Up !
soon in a release?

**Comment by sworlls** [comment]
Hello Guys, more than one year has passed! anyone can give any update if this is something would be happeing on new version? or never count on this:?
thank you

**Comment by stonebuzz** [comment]
Hi @sworlls 
Currently this feature is not available.
Several solutions :

- make a feature request here -> https://glpi.userecho.com/
- Participate financially in this feature by contacting us here -> https://portal.glpi-network.com/contactez-nous
- Develop the functionality yourself and give us a pull request here -> https://github.com/pluginsGLPI/fields/pulls

Best regards
