### ISSUE TITLE
Dropdown problems

### ISSUE THREAD

**Issue by keha35** [pluginsGLPI/fields#299]
Hi,

In using the plugin we found 2 problems for the dropdown type :

* When the dropdown name is too long, 
If you create a dropdown field it generate an error.
The field is created but can't be configured and can't be deleted.
When you try to delete it with massivaction it generate this error in debug mod :

> Fatal error: Uncaught Zend\Cache\Psr\SimpleCache\SimpleCacheInvalidArgumentException: Invalid key "glpi_plugin_fields_dclarationeffectueparfielddropdowns_ancestors_cache_2" provided; key is too long. 
> Must be no more than 64 characters in /usr/share/php/Zend/Cache/Psr/SimpleCache/SimpleCacheDecorator.php:344 
> Stack trace: #0 /usr/share/php/Zend/Cache/Psr/SimpleCache/SimpleCacheDecorator.php(279): Zend\Cache\Psr\SimpleCache\SimpleCacheDecorator->validateKey('glpi_plugin_fie...') 
> #1 /usr/share/glpi/inc/dbutils.class.php(802): Zend\Cache\Psr\SimpleCache\SimpleCacheDecorator->has('glpi_plugin_fie...') 
> #2 /usr/share/glpi/inc/db.function.php(305): DbUtils->getAncestorsOf('glpi_plugin_fie...', '2') 
> #3 /usr/share/glpi/inc/commontreedropdown.class.php(296): getAncestorsOf('glpi_plugin_fie...', '2') 
> #4 /usr/share/glpi/inc/commontreedropdown.class.php(160): CommonTreeDropdown->cleanParentsSons() 
> #5 /usr/share/glpi/inc/commondbtm.class.php(1652): CommonTreeDropdown->pre_deleteItem() 
> #6 /usr/share/glpi/inc/massiveaction.class.php(1073): in /usr/share/php/Zend/Cache/Psr/SimpleCache/SimpleCacheDecorator.php on line 344

* You can't define a default value to the dropdown

Glpi version 9.3.3
Plugin version 1.8.2

**Comment by tsmr** [comment]
![image](https://user-images.githubusercontent.com/13178158/60013128-f5c64180-967d-11e9-9f5a-8b38b86677f3.png)

**Comment by cedric-anne** [comment]
Hi @keha35 @tsmr ,

Can you check if https://github.com/glpi-project/glpi/pull/6076 fixes your problem ?

Regards

**Comment by xoryves** [comment]
@cedric-anne , we had same problems with GLPI 9.4.3 and Fields 1.10.0.
https://github.com/glpi-project/glpi/pull/6076 fixed it.

**Comment by trasher** [comment]
Thank you for the feedback @xoryves :) this will be fixed in the next core release.
