### ISSUE TITLE
Update Fileds 1.7.0 to 1.9.1 and GLPI 9.2 to 9.4 Lost Custom Fields. 

### ISSUE THREAD

**Issue by gilbertogmacedo** [pluginsGLPI/fields#303]
Hi, 
On update GLPI 9.2 to 9.4 and Fields 1.7.0 to 1.9.1 lost created fileds, configuration is clean after update. 

Thanks
Sorry for my english.

**Comment by trasher** [comment]
Most of the time, users forget to migrate their files directory to the new instance.

**Comment by stonebuzz** [comment]
Hi @gilbertogmacedo ,

have you migrate generated files under folder /giles/_plugins/fields/ ?

Best regards
