### ISSUE TITLE
Undefined index on dropdown field search list

### ISSUE THREAD

**Issue by stonebuzz** [pluginsGLPI/fields#305]
Bonjour,

lorsque l'on créer un champ de type liste déroulante avec un chiffre par exemple poste8, 
la recherche dans les intitulés de GLPI ne fonctionne pas
 
Création du bloc et de champ :
![image](https://user-images.githubusercontent.com/7335054/53636460-a072aa00-3c20-11e9-8652-e8b4a1e6ca16.png)

Voici le résultat dans la liste des intitulés 
![image](https://user-images.githubusercontent.com/7335054/53636500-c304c300-3c20-11e9-81db-c4058438b97e.png)

**Comment by trasher** [comment]
https://github.com/pluginsGLPI/fields/blob/master/inc/container.class.php#L360-L364 should follow core rules and do not allow numbers in names

**Comment by cedric-anne** [comment]
Fixed by #306 .
