### ISSUE TITLE
Solution tab does not exists anymore

### ISSUE THREAD

**Issue by Multiconecta** [pluginsGLPI/fields#309]
In Glpi 9.3 there is no Solution Tab anymore. That leads users a little puzzled as there is an option to add a block before save button in solution tab.

If it not feasible to drop that option (backward compatibilities), maybe that should be tested and some warning message should be displayed in Setup page. It's kind of foolish but I lost some time trying to figure it out where my solution tab was, and what happened to my new block/field.

**Comment by stonebuzz** [comment]
Hi @Multiconecta 

duplicate with #328 

I'll close this issue in favor of the other thread.

Best regards
