### ISSUE TITLE
ability to add fields to components

### ISSUE THREAD

**Issue by fgendorf** [pluginsGLPI/fields#312]
Hi, I use the plugin for SimCard because it have some information that component Simcard doesn't have.
I think will be great if the plugins fields can be used in GLPI components

**Comment by dgsn** [comment]
Me too...
I agree for the two points : component Simcard is incomplete and i can't add fields to a component...
Best regards

**Comment by stonebuzz** [comment]
Hi @fgendorf 

Actually this feature is not available.

You can propose a PR to implement this feature, or
If you want to refactor this part, please contact us here [GLPI Network](https://portal.glpi-network.com/plugins/formcreator/front/formdisplay.php?id=16)

Best regards

**Comment by ajasa19** [comment]
Hey guys I had the same problem but with network cards here's some code I wrote in fields/inc/container.class.php to fix the issue.

`$tabs[__('Components')] = [
'DeviceNetworkCard' => DeviceNetworkCard::getTypeName(2),
'DeviceSimcard'         => DeviceSimcard::getTypename(2)
 ];
`
you can add more items if you wish like 'DeviceBattery', DeviceHardDrive', DevicePci', etc

**Comment by Wolvverine** [comment]
@stonebuzz
Is it possible to add the ability to add additional fields to Components?
Batteries
Cases
Controllers
Drives
Graphics cards
Hard drives
Memories
Network cards
PCI devices
Power supplies
Processors
Simcards
Soundcards
The boards system

These components are purchased separately and it would be nice to have additional fields for example with no. order, link to another system, etc.

**Comment by cedric-anne** [comment]
Done in #504.
