### ISSUE TITLE
How to delete Blocks/Fields

### ISSUE THREAD

**Issue by no6una9a** [pluginsGLPI/fields#313]
Hello,

thanx for the Fiels plugin to provide room for additional information within GLPI. I installed fields plugin version 1.9.1 within my GLPI server version 9.4.0. 

Regarding the fields plugin I can create new block items, new fields within blocks and associate them to GLPI units such as computers. And they are displayed the way they should.

But once I create a new block I can not delete it later. The only "Action" I can apply to blocks is "Update". And I also can not delete fields after I create them within blocks. I can rename field labels, set them active, read-only, ... but I am not able to delete field labels once they are created. 

Is this the expected behaviour or am I missing something important?

Kind regerads,
No6una9a

![glpi_fields_blockActiions](https://user-images.githubusercontent.com/49673381/56192025-c4057e80-602d-11e9-96ae-24ecfff6792f.png)
![glpi_fields_fieldLabelList](https://user-images.githubusercontent.com/49673381/56192029-c7006f00-602d-11e9-9262-0e5e48cc2232.png)
![glpi_fields_fieldLablelDetails](https://user-images.githubusercontent.com/49673381/56192033-cbc52300-602d-11e9-988d-859cf4d74d55.png)

**Comment by kl3sk** [comment]
Interested by the answer too. Same problem.

**Comment by redisded** [comment]
Hi, same problem here.

GLPI 9.4.1.1
Fileds 1.10.0

Maybe some permissions to adjust ?

**Comment by kevinforrestconnors** [comment]
Same problem.  I have to delete manually in database.

**Comment by Osennijlis** [comment]
Same problem:
GLPI 9.4.3
Fields 1.10.0

**Comment by static302** [comment]
![image](https://user-images.githubusercontent.com/42393000/64095157-b3e50600-cd66-11e9-9338-0a391bff7d48.png)
the same for me
no delete option, but transfer
GLPI 9.4.3
Fields 1.10.1

I have another installation of the same bundle, but the second one works with no problem (i have a delete permanently option)

**Comment by kevinforrestconnors** [comment]
@static302  I am able to delete manually in the database with no issues

**Comment by albercuba** [comment]
Same problem:
GLPI 9.4.3
Fields 1.10.1

**Comment by static302** [comment]
@kevinforrestconnors yeah, I know, but we`re searching for a proper way, not workaround :)

**Comment by albercuba** [comment]
Also, I tried to delete it directly in the database but it remains in the web interface.

```
MariaDB [it_db]> show tables like '%specialaccount%';
+----------------------------------------+
| Tables_in_it_db (%specialaccount%)     |
+----------------------------------------+
| glpi_plugin_fields_userspecialaccounts |
+----------------------------------------+
1 row in set (0.00 sec)

MariaDB [it_db]> drop table glpi_plugin_fields_userspecialaccounts;
Query OK, 0 rows affected (0.00 sec)

MariaDB [it_db]> show tables like '%specialaccount%';
Empty set (0.00 sec)
```

![grafik](https://user-images.githubusercontent.com/11768756/64235634-0fdf9400-cef9-11e9-9bc1-ce99ea7b85e5.png)

**Comment by redisded** [comment]
Hello,
same problem here :

Debian 9.9
GLPI 9.4.3
Fields 1.10.1

@kevinforrestconnors : Can you tell us exactly what did you delete in DB ?

**Comment by kevinforrestconnors** [comment]
Sorry for late reply @redisded .  I think I deleted the field I no longer wanted in theglpi_plugin_fields_fields table.  And for block I think it's glpi_plugin_fields_containers

**Comment by redisded** [comment]
Late reply is better than no reply, thank you very much 😉

**Comment by tuxxic** [comment]
Confirmed #335 solves this ! Thanks @cedric-anne !

**Comment by tuxxic** [comment]
Hi,

Sorry, I was too quick.

I now have a 500 error, in php-errors.log I have this :

`[2019-10-18 13:54:12] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: ddtype
  Backtrace :
  plugins/fields/front/commondropdown.php:4
  {"user":"2@glpi.server.fr"}`

**Comment by stonebuzz** [comment]
hi @tuxxic @redisded @kevinforrestconnors @albercuba @static302  @Osennijlis  @no6una9a 

can you test this PR -> https://github.com/pluginsGLPI/fields/pull/355

which fix purge right on field form.

Best regards

**Comment by tuxxic** [comment]
Hi @stonebuzz 

Tested with GLPI 9.4.5 and it seems to work, I can now delete fields.
Now we need to delete blocks and everything is ok :)

Thanks for the first patch !

**Comment by stonebuzz** [comment]
purge block is already implemented
![image](https://user-images.githubusercontent.com/7335054/72979107-e48e1080-3dd7-11ea-8dac-c8f24e3603d3.png)
Best regards

**Comment by tuxxic** [comment]
Hi,

I do not have it :

![image](https://user-images.githubusercontent.com/4680438/72994177-eadfb500-3df6-11ea-9c85-1cb430acd0d1.png)

Which version do you use ?

**Comment by stonebuzz** [comment]
develop branch

**Comment by tuxxic** [comment]
OK, just added the file from the development branch, it seems to work :)

Thanks a lot !
