### ISSUE TITLE
Bug in search through tickets ?

### ISSUE THREAD

**Issue by laurentmele** [pluginsGLPI/fields#315]
Hi All,

I have custom fields in tickets. This fields are working well with no error, but I canno't search for tickets with the specified fields. I have no results whatever i'm looking for.
I have fields 1.9.2 same behavior with 1.9.1 and glpi 9.4. Is there any compatibility issue ?
Have no errors in the glpi's logs.

**Comment by stonebuzz** [comment]
Hi @laurentmele 

you plugin fields version is old, can you test latest ?

Best regads
