### ISSUE TITLE
simplified interface

### ISSUE THREAD

**Issue by ccastelb** [pluginsGLPI/fields#319]
My best wishes to all.
I have not been able to perform the incorporation of fields with the plugin of additional fields
Basically what I need is that you can add fields in the simplified interface when opening a ticket
can someone please guide me on how I should perform this action
we have glpi 9.4.2
Additionnal fields 1.9.1

**Comment by stonebuzz** [comment]
Hi @ccastelb 

first you nedd to upgrade your glpi and fields to latest version

after you can test develop branch of plugin  which fix the visibility of fields in simplified interface.

Best regards

**Comment by stonebuzz** [comment]
Fixed by  #327
