### ISSUE TITLE
Pb sauvegarde de données

### ISSUE THREAD

**Issue by galbourn** [pluginsGLPI/fields#32]
Bonjour,

Je viens d'installer le plugin Fields version 0.90-1.2 sur un glpi 0.90.3.
L'installation du plugin s'est bien passé.
J'ai pu ajouter un nouveau bloc (chiffrement) sur le type ordinateurs.
Quand je vais sur mes ordinateurs, je vois bien le nouvel onglet chiffrement apparaître.

Quand je vais sur ce nouvel onglet, je peux renseigner les nouveaux champs mais quand je sauvegarde, j'obtiens une page blanche.

en mode debug, j'ai le message suivant:
PHP Warning: Missing argument 3 for PluginFieldsContainer::updateFieldsValues(), called in /usr/share/glpi/plugins/fields/front/container.form.php on line 31 and defined in /usr/share/glpi/plugins/fields/inc/container.class.php at line 650
PHP Notice: Undefined variable: itemtype in /usr/share/glpi/plugins/fields/inc/container.class.php at line 662
Fatal error: Class 'PluginFieldsChiffrement' not found in /usr/share/glpi/plugins/fields/inc/container.class.php on line 663 

Dans le répertoire  /usr/share/glpi/plugins/fields/inc/, le plugin a crée deux nouveaux fichiers:
computerchiffrement.class.php
computerchiffrementinjection.class.php

Pouvez vous m'aider ?

Merci

**Comment by orthagh** [comment]
Merci pour votre retour.

C'est normalement corrigé par le commit ci dessus.

**Comment by galbourn** [comment]
C'est OK. Merci beaucoup de votre réactivité.
