### ISSUE TITLE
Bug rename table during migration

### ISSUE THREAD

**Issue by alex8276** [pluginsGLPI/fields#322]
Hello,

During migration 1.7.3 to 1.10 in fixfieldsname function, the request $bad_named_fields give some bad results. So many tables are renamed by error because of Mysql use POSIX 1003 standard and it doesn't \d.

Regards

**Comment by tomolimo** [comment]
Hello,
Which version of mySQL are you using?
Thank you,
Regards,
Tomolimo

**Comment by alex8276** [comment]
I use the version : 5.7.17

regards
