### ISSUE TITLE
Additionnal Field doesn't appear

### ISSUE THREAD

**Issue by abriuschi** [pluginsGLPI/fields#327]
Hello all! I have the following problem:
I added one additionnal field, and sometimes appear the field and sometimes doesn´t appear. 
In the simplified interface and in the standard interface too.
It's a problem because the field I added is the desire date to solve the tickets.

This field is a mandatory field.

Do you have the same problem?
Thanks!

**Comment by juveboss** [comment]
Hello,

Yes , i have the problem... 

No fix at the moment for this problem

**Comment by judish** [comment]
Hello,

I've got the same problem. As a workaround I have a JavaScript which reloads the page if my additional field is not in the DOM

**Comment by kedson42** [comment]
Hello.
I still face the same problem: additional fields sometimes are displayed and sometimes don't. When they don't, a page refresh is necessary.
Has anyone worked in a solution yet?

**Comment by abriuschi** [comment]
Hello all.
In the last version 1.10.2, we still have the same issue.

**Comment by stonebuzz** [comment]
hi @abriuschi  @juveboss @judish @kedson42 

can you give us more informations, item form (ticket, location etc ..)
step to reproduce
logs

Best regarfs

**Comment by abriuschi** [comment]
Hi @stonebuzz !

When an user try to send a ticket in simplified interface, the additional field sometimes appear and sometimes doesn't appear. But in standard interface happen the same situation.
If you press F5 to recharge the page, sometimes appear. If not, we press F5 again.

Tell me if you need more information.
Thanks!

**Comment by stonebuzz** [comment]
Additionnel are in main tab before save button or new one ?

**Comment by abriuschi** [comment]
This is the way I use it.

Insertion in the form (before save button)

**Comment by stonebuzz** [comment]
I can't reproduce, can you check if you have error log in web console (F12 in your browser)
or in glpi (/glpi/fiels/_logs) or on you webs erver (/var/log/apache2).

Can you redo a test by disabling all expecter fields plugins and check if you have the same behavior (maybe another plugin is causing a problem)

Best regards

**Comment by abriuschi** [comment]
Hello @stonebuzz!
I've receive an email that, this problem its fix. This is the link to:

https://github.com/pluginsGLPI/fields/pull/352

I think in the next version of addtional fields we will not have the issue.
Is it OK?

**Comment by stonebuzz** [comment]
This bug is for simplified interface, you  too  ?

**Comment by abriuschi** [comment]
Yes, It's for simplified interface. But I have the issue for standard interface too.

BTW, the most important issue it's from simplified interface.

If you want, I can try modify inc/field.class.php like said in the link I send before and check.

**Comment by stonebuzz** [comment]
Yes

**Comment by andreytavares** [comment]
I modified the file, but I'm not getting success.

In the standard interface the plugin is working.

**Comment by andreytavares** [comment]
I modified the file like this:

      $functions = array_column(debug_backtrace(), 'function');

      //if (!isset($_SESSION['glpi_tabs'][strtolower($item::getType())])) {
      //   return;
      //};

      //$subtype = $_SESSION['glpi_tabs'][strtolower($item::getType())];
      //$subtype = $_SESSION['glpi_tabs'][strtolower($item::getType())] ?? "";
      $subtype = isset($_SESSION['glpi_tabs'][strtolower($item::getType())]) ? $_SESSION['glpi_tabs'][strtolower($item::getType())] : "";

**Comment by stonebuzz** [comment]
Have you deco / reco before test, because patch work with session

**Comment by abriuschi** [comment]
Yes!! Now It's work great!

Thank you for your help @stonebuzz !!!

@andreytavares Do you have installed the latest version of Additional Fileds?

**Comment by andreytavares** [comment]
@stonebuzz I did not understand. deco / reco?

@abriuschi I am using version 1.10.2.

**Comment by stonebuzz** [comment]
disconnect then reconnect before test patch =)

**Comment by andreytavares** [comment]
@stonebuzz yes..I'm going to check the plugin version. :P

**Comment by andreytavares** [comment]
@abriuschi did it work for you?

**Comment by abriuschi** [comment]
@andreytavares Yes. Now it's work great!

Thanks again for your help @stonebuzz

**Comment by andreytavares** [comment]
@abriuschi were the changes I mentioned above?

**Comment by andreytavares** [comment]
@abriuschi what version of GLPI are you using?

**Comment by abriuschi** [comment]
@andreytavares Yes. I applied the changes You mentioned above. But, I use this line:

$subtype = $_SESSION['glpi_tabs'][strtolower($item::getType())] ?? "";

My GLPI version is 9.4.2

**Comment by andreytavares** [comment]
@abriuschi I am using version 9.4.1.1. I will test with version 9.4.2.

**Comment by stonebuzz** [comment]
be careful this ```$subtype = $_SESSION['glpi_tabs'][strtolower($item::getType())] ?? "";```
is compatible with php since 7.0
For previsous version of php use 
 ``` $subtype = isset($_SESSION['glpi_tabs'][strtolower($item::getType())]) ? $_SESSION['glpi_tabs'][strtolower($item::getType())] : "";```

**Comment by andreytavares** [comment]
@stonebuzz I'm using version: PHP 7.0.33-0 + deb9u3

**Comment by stonebuzz** [comment]
use this

```$subtype = isset($_SESSION['glpi_tabs'][strtolower($item::getType())]) ? $_SESSION['glpi_tabs'][strtolower($item::getType())] : "";```

**Comment by stonebuzz** [comment]
and comment this part
```
  if (!isset($_SESSION['glpi_tabs'][strtolower($item::getType())])) {
     return;
   };
```

**Comment by trasher** [comment]
Or use a supported PHP version; 7.0 has been EOL from a while

**Comment by stonebuzz** [comment]
Its okay with this modification ?

**Comment by andreytavares** [comment]
@stonebuzz  no. I will do a new installation of GLPI 9.4.2 to validate.

**Comment by stonebuzz** [comment]
Why not try with glpi 9.4.5 ?

**Comment by andreytavares** [comment]
@stonebuzz ok, i will use this version.

**Comment by stonebuzz** [comment]
Duplicate with #331

**Comment by andreytavares** [comment]
@stonebuzz good work. it worked for me in GLPI version 9.4.5.

**Comment by stonebuzz** [comment]
:+1:  nice
