### ISSUE TITLE
1.8.2 - Bug - Can't add a new field on "Notes"

### ISSUE THREAD

**Issue by Green7Kraken** [pluginsGLPI/fields#329]
After adding a new block, the new field is not created.
looking at the php logs, this message appears

glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined index: entities_id
  Backtrace :
  plugins/fields/inc/container.class.php:888
  inc/commonglpi.class.php:210                       PluginFieldsContainer->getTabNameForItem()
  inc/commonglpi.class.php:173                       CommonGLPI->addStandardTab()
  ajax/updatecurrenttab.php:46                       CommonGLPI->defineAllTabs()
  {"user":"7@id20795.example.com","mem_usage":"0.012\", 2.73Mio)"}
[2019-09-02 12:58:27] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657

I am using version 1.8.2 with a 9.3.2 glpi

**Comment by stonebuzz** [comment]
Hi @Green7Kraken 

your version is very old can you check latest version of plugin ?

Best regards

**Comment by Green7Kraken** [comment]
Hi @stonebuzz 
I'm not sure but i can take lastest version of plugins on 9.3.2 ?

**Comment by Green7Kraken** [comment]
So, i must upgrade my GLPI ? To use latest version of plugin ?

**Comment by stonebuzz** [comment]
Yes, that's right.

Best regards

**Comment by Green7Kraken** [comment]
Another final question, do you know why the new field before the save button, it shifts all the form (always in the note page) ?

**Comment by stonebuzz** [comment]
It's a problem with ```<table>``` and ```<td>``` HTML DOM.

Can  you open new issue and close this one ?

Best regards

**Comment by Green7Kraken** [comment]
Ok no problem !
