### ISSUE TITLE
Table alignment

### ISSUE THREAD

**Issue by albercuba** [pluginsGLPI/fields#330]
Hello everyone.

Can the table alignment be fixed please? It is a bit annoying that the table headers do not align with the cell's content.

![grafik](https://user-images.githubusercontent.com/11768756/64405181-98d40800-d07e-11e9-9560-337ae2f31954.png)

Best regards

**Comment by albercuba** [comment]
For now I just edited  `/var/www/html/glpi/css/styles.scss`

In line `1170` I changed the text alignment to `center`

But this of course will be lost after the next upgrade.

![grafik](https://user-images.githubusercontent.com/11768756/64407342-6a592b80-d084-11e9-9cb8-260cc65fdfe6.png)

**Comment by stonebuzz** [comment]
Hi @albercuba 

it concerns GLPI, can you open PR in the right repo ?

Best regrds
