### ISSUE TITLE
interface simplifié

### ISSUE THREAD

**Issue by romain1206** [pluginsGLPI/fields#331]
bonjour,

je suis en train de tester GLPI avec les plugins que nous utilisons actuellement, mais ca ne fonctionne pas avec le plugin fields dans l'interface simplifiée

ca fonctionnait bien en glpi 9.21 avec le plugin fields 1.4.5

maintenant je suis en glpi 9.4.3 et fields 1.10.1

je cherche a ajouter 2 elements a la saisie d'un ticket (personne a contacter et numéro de téléphone)

ca apparait bien en admin et super admin mais pas en "post only"

j'ai activer le debug mais pas d'erreur

par compte j'ai remarquer une chose, si je clique sur la page "créer un ticket en admin" et que je passe en "post only" et que je fais "créer un ticket" mon champ supplémentaire apparait

j'ai déjà eu ce phénomène dans d'autres versions précédentes #179 et #216 

merci de ce que vous pourrez faire

**Comment by romain1206** [comment]
meme soucis avec la nouvelle version sortie hier

**Comment by asuarezMision** [comment]
Hi.

This is the scenario we have implemented:

GLPI Version 9.4.3
Plugin 10.10.2

We create a custom Dropdown field associated with tickets; This field has 5 options that are:

Petition
Complain
Claim
Suggestion
Congratulation

The field belongs to the main entity and is recursive, write permissions were granted for all profiles.

Now the problems:

1. When entering to create a ticket for the first time after logging in, it does not show the custom field, at the second time it is entered if it is shown.

2. The field is shown by default in ticket templates, but at the time of creating a ticket with a profile different from Super-Admin the field is not shown.


I enclose a document with the settings and problems in case someone can help me.
[Error GLPI.pdf](https://github.com/pluginsGLPI/fields/files/3713784/Error.GLPI.pdf)

**Comment by Alwaysin** [comment]
We have exactly the same problem, can't see the addtional field except for super-admins and one usr (?? did compare it with others but same configuration as everyone, why does HE sees the field and not the others?)

**Comment by stonebuzz** [comment]
Hi @romain1206 can you test this PR
https://github.com/pluginsGLPI/fields/pull/352

Best regards

**Comment by stonebuzz** [comment]
Fixed by #352
