### ISSUE TITLE
Incorrect block registration state occurs when multi-byte inputting to the label field

### ISSUE THREAD

**Issue by coleyon** [pluginsGLPI/fields#332]
**Behavior**

1. When the block is registered with inputting multi-byte characters (Japanese) to the label field, the following error occurs.
```
Identifier name 'glpi_plugin_fields_computeroneseveneightfiveeightfourzeroeightsixzeros' is too long
```
2. After that, when showing the block list page, it appears that the block has been successfully registered.
3. In addition, if you try to add a field to that block, another error occurs.
```
0 multiple alter in glpi_plugin_fields_computeroneseveneightfiveeightfourzeroeightsixzeros - Error during the database query: ALTER TABLE `glpi_plugin_fields_computeroneseveneightfiveeightfourzeroeightsixzeros` ADD `additionalfieldfield` VARCHAR(255) DEFAULT NULL - Error is Identifier name 'glpi_plugin_fields_computeroneseveneightfiveeightfourzeroeightsixzeros' is too long
```

**Improvement proposal (my Expected Behavior)**

* If it is difficult to handle multi-byte characters (e.g. Japanese) as a label, 
the block registration function fails correctly without accepting the registration request.

**Environment**

GLPI Field plugin 1.10.1 + GLPI 9.4.3 + mysql 5.7
mysql settings: `$ mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci`

**Steps to Reproduce**

1. Inputs character `値` in japanese kanji and press Add. 
`値`'s Unicode numerical character references (NCR) is `&#20516;`.
![2019-09-09_210641](https://user-images.githubusercontent.com/24493192/64534809-1d5da980-d351-11e9-89d0-cdd48d1d3698.png)
Then Occuring the error1.
![xxx](https://user-images.githubusercontent.com/24493192/64535354-171bfd00-d352-11e9-959b-2ed5943e27b8.png)
2. Browser back (press Alt+Left) and click the link of the block showed.
![baa](https://user-images.githubusercontent.com/24493192/64535474-56e2e480-d352-11e9-8c0a-6f56a72c0460.png)
3. Entering the Block's field inputpage.
![qwe](https://user-images.githubusercontent.com/24493192/64535742-c3f67a00-d352-11e9-8f4b-7127d65848f1.png)
and press Add button then occurs error2.
![tre](https://user-images.githubusercontent.com/24493192/64535860-fb652680-d352-11e9-8302-8e75d9355668.png)

**Reference**

Registered status of db.
```
mysql> SELECT * FROM glpi.glpi_plugin_fields_containers\G
*************************** 1. row ***************************
          id: 1
        name: oneninefivesixthreefivesixfourtwo
       label: ?
   itemtypes: ["NetworkEquipment"]
        type: tab
     subtype: NULL
 entities_id: 0
is_recursive: 0
   is_active: 1
1 row in set (0.00 sec)

mysql> SELECT * FROM glpi.glpi_plugin_fields_fields\G
Empty set (0.00 sec)

mysql>
```

**Comment by stonebuzz** [comment]
Hi @coleyon  can you test this PR #351 

Your problem is due to field / container name too long for mysql table name

plugin transform name (numeric to string) and result is too long. 

Best regards

**Comment by coleyon** [comment]
Hi @stonebuzz 

Thank you for your works. I tested your PR #351 .

**Result:**

OK.

* Test1
I tried inputs the char `値` in japanese kanji and press Add. `値`'s Unicode numerical character references (NCR) is &#20516;.
![image](https://user-images.githubusercontent.com/24493192/73178444-9ae55300-4154-11ea-966d-73fec643170b.png)
I had get below message.
![image](https://user-images.githubusercontent.com/24493192/73178487-b3556d80-4154-11ea-885c-1d424f87afaf.png)
And the block registration function fails correctly without accepting the registration request.
![image](https://user-images.githubusercontent.com/24493192/73178958-b69d2900-4155-11ea-9982-c28005c21f8c.png)
    ```
    MySQL [glpi]> SELECT count(*) FROM glpi.glpi_plugin_fields_containers\G
    *************************** 1. row ***************************
    count(*): 0
    1 row in set (0.01 sec)
    ```
* Test2
I tried inputs some patterns. I think so looks likes good.

|Label input|Type input|Active input|ItemType input|value of glpi_plugin_fields_containers.name|Popup result|
|----|----|----|----|----|----|
|1|Add Tab|Yes|Computers|One|Information Item Successfully Added: ...|
|2|Add Tab|Yes|Computers|Two|Information Item Successfully Added: ...|
|a|Add Tab|Yes|Computers|a|Information Item Successfully Added: ...|
|x|Add Tab|Yes|Computers|x|Information Item Successfully Added: ...|
|X|Add Tab|Yes|Computers||Error You cannot add several blocks with identical name on same object|
|`値`|Add Tab|Yes|Computers||Information Container name is too long for database (plugin update numeric to character, try to remove them)|
|b|Add Tab|Yes|||Error You cannot add block without associated element type|
|`ē`|Add Tab|Yes|Computers||Information Container name is too long for database (plugin update numeric to character, try to remove them)|
|Our unique stock number|Add Tab|Yes|Computers|ouruniquestocknumber|Information Item Successfully Added: ...|


DB records are good too.

    ```
    MySQL [glpi]> SELECT * FROM glpi.glpi_plugin_fields_containers;
    +----+----------------------+-------------------------+--------------+------+---------+-------------+--------------+-----------+
    | id | name                 | label                   | itemtypes    | type | subtype | entities_id | is_recursive | is_active |
    +----+----------------------+-------------------------+--------------+------+---------+-------------+--------------+-----------+
    |  3 | one                  | 1                       | ["Computer"] | tab  | NULL    |           0 |            0 |         1 |
    |  4 | two                  | 2                       | ["Computer"] | tab  | NULL    |           0 |            0 |         1 |
    |  5 | a                    | a                       | ["Computer"] | tab  | NULL    |           0 |            0 |         1 |
    |  6 | x                    | x                       | ["Computer"] | tab  | NULL    |           0 |            0 |         1 |
    |  7 | ouruniquestocknumber | Our unique stock number | ["Computer"] | tab  | NULL    |           0 |            0 |         1 |
    +----+----------------------+-------------------------+--------------+------+---------+-------------+--------------+-----------+
    5 rows in set (0.00 sec)
    ```

**Environment:**

GLPI Field plugin 1.10.2 with patch of PR #351 + GLPI 9.4.3 + mysql 5.7

    $ git clone https://github.com/coleyon/glpi-docker.git
    $ cd glpi-docker/
    $ mv .env.example .env && mv .mysql.env.sample .mysql.env
    $ docker-compose up -d
    $ docker container ls
    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                               NAMES
    b1545a36139a        glpi                "/opt/entrypoint.sh …"   2 hours ago         Up 2 hours          0.0.0.0:80->80/tcp, 443/tcp         glpi
    $ docker exec -it b1545a36139a /bin/bash
    root@b1545a36139a:/var/www/html# cd glpi/plugins
    root@b1545a36139a:/var/www/html/glpi/plugins# git clone https://github.com/pluginsGLPI/fields.git -b 1.10.2
    root@b1545a36139a:/var/www/html/glpi/plugins# cd fields/
    root@b1545a36139a:/var/www/html/glpi/plugins/fields# git log -n1
    commit e915e19c01fbf7239e2fedce6328375a8d070ad7
    Merge: 71204cc 300d585
    Author: C<C3><A9>dric Anne <cedric.anne@gmail.com>
    Date:   Tue Oct 1 10:01:56 2019 +0200

        Merge branch 'release/1.10.2'
    
    
    root@b1545a36139a:/var/www/html/glpi/plugins/fields#
    root@b1545a36139a:/var/www/html/glpi/plugins/fields# curl -LO https://github.com/pluginsGLPI/fields/pull/351/commits/e91f692a696eb82626838e249225ed5c580e0a1c.patch
    root@b1545a36139a:/var/www/html/glpi/plugins/fields# patch -p1 < e91f692a696eb82626838e249225ed5c580e0a1c.patch
    patching file inc/container.class.php
    Hunk #2 succeeded at 413 (offset -1 lines).
    patching file inc/field.class.php
    patching file inc/toolbox.class.php
    root@b1545a36139a:/var/www/html/glpi/plugins/fields# git diff
    diff --git a/inc/container.class.php b/inc/container.class.php
    index acfd95e..d2acdc6 100644
    --- a/inc/container.class.php
    +++ b/inc/container.class.php
    ...
    root@b1545a36139a:/var/www/html/glpi/plugins/fields#

Thank you.
