### ISSUE TITLE
Security die. trying to load a forbidden class name

### ISSUE THREAD

**Issue by christophedumont5** [pluginsGLPI/fields#334]
Hello, 

When i'm trying to load the bloc page i get an error message 

Security die. trying to load a forbidden class name

**Comment by CAIB-MMU** [comment]
Hello,

I have the same issue.

**Comment by stonebuzz** [comment]
Hi @christophedumont5 

can you check in database if column itemtype from glpi_plguin_fields_containers is empty or like [ ] ?

Best regards

**Comment by AndrewG-usr** [comment]
forgive me I am new to this. I am also having this same issue.

**Comment by stonebuzz** [comment]
No you need to extract data with select *

**Comment by AndrewG-usr** [comment]
no the itemtypes is not empty it has the ones I previously created

**Comment by stonebuzz** [comment]
have you got a line with ["0"] value for itemtype column  in database ?

Best regards

**Comment by AndrewG-usr** [comment]
yes I have a line with ["0"] value in the itemtype column. is this what is causing it?

**Comment by stonebuzz** [comment]
yep, update'it to a real itemtype (ie: Computer, Monitor) etc ..

Best regards

**Comment by AndrewG-usr** [comment]
Thank you!!

**Comment by slompo** [comment]
Hi, thanks for this issue report and solution of user @AndrewG-usr, I resolved this same problem in my instance of GLPI, using this SQL update:

`update glpi_plugin_fields_containers set itemtypes = "[\"Computer\"]" where  itemtypes = "[\"0\"]"`

After that, I used de GLPI menu Plugin to do the customizations of fields.
