### ISSUE TITLE
Blank screen when the field is more than 16 characters long.

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/fields#337]
HI,
When create a field more than 16 charactères, index becomes too long and cannot be created.
Symptom : blank screen and message in log file : 
[Tue Sep 24 10:15:13.805373 2019] [php7:error] [pid 2018] [client MyIP:53588] PHP Fatal error:  Uncaught Zend\\Cache\\Psr\\SimpleCache\\SimpleCacheInvalidArgumentException: Invalid key "glpi_plugin_fields_codestatistiquefielddropdowns_ancestors_cache_1" provided; key is too long.

Cannot correct and resolte after this bug, have to delete plugin completly to delete the bug, because of the permanent blank screen.
Quand on créé un champ qui fait plus de 16 caractères, il y a tout d'abord un écran blanc. Dans les logs GLPI, on a une erreur (cf ci-dessus). Il est impossible par la suite de supprimer ce champ, car on a systématiquement un écran blanc. Il faut alors supprimer le plugin et le réinstaller pour corriger le bug.
other link to this problem : https://forum.glpi-project.org/viewtopic.php?id=172706
Thanks for all

**Comment by cedric-anne** [comment]
Duplicates #333.
