### ISSUE TITLE
9.4.4 Assets search Error

### ISSUE THREAD

**Issue by Nem-Tom** [pluginsGLPI/fields#339]
GPLI 9.4.3, Fields-1.10.2. new installation, works fine. Good!
GPLI 9.4.4, Fields-1.10.2. new installation, partially faulty! Not good!
Search does not work in it.

![firefox_5DmqtW5fxR](https://user-images.githubusercontent.com/57030584/67616062-72a42c00-f7d4-11e9-8750-854270d80c43.png)

sql-errors.log
[2019-10-25 15:52:06] glpisqllog.ERROR: DBmysql::query() in C:\wamp64\www\GLPI\glpi-9.4.4-temp\www\inc\dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT DISTINCT `glpi_computers`.`id` AS id, 'glpi' AS currentuser,
                        `glpi_computers`.`entities_id`, `glpi_computers`.`is_recursive`,  `glpi_computers`.`name` AS `ITEM_Computer_1`,
                        `glpi_computers`.`id` AS `ITEM_Computer_1_id`,
                        `glpi_states`.`completename` AS `ITEM_Computer_31`,  `glpi_manufacturers`.`name` AS `ITEM_Computer_23`,  `glpi_computers`.`serial` AS `ITEM_Computer_5`,  `glpi_computertypes`.`name` AS `ITEM_Computer_4`,  `glpi_computermodels`.`name` AS `ITEM_Computer_40`,  `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`.`name` AS `ITEM_Computer_45`,  `glpi_locations`.`completename` AS `ITEM_Computer_3`,  `glpi_computers`.`date_mod` AS `ITEM_Computer_19`,   GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`designation`, '__NULL__'),
                                               '$#$',`glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`id`) ORDER BY `glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`id` SEPARATOR '$$##$$')
                              AS `ITEM_Computer_17`,
                  
                  `glpi_plugin_fields_computercustomones_numberonefield`.`numberonefield` AS `ITEM_Computer_76667` FROM `glpi_computers`LEFT JOIN `glpi_states` 
                                          ON (`glpi_computers`.`states_id` = `glpi_states`.`id`
                                              )LEFT JOIN `glpi_manufacturers` 
                                          ON (`glpi_computers`.`manufacturers_id` = `glpi_manufacturers`.`id`
                                              )LEFT JOIN `glpi_computertypes` 
                                          ON (`glpi_computers`.`computertypes_id` = `glpi_computertypes`.`id`
                                              )LEFT JOIN `glpi_computermodels` 
                                          ON (`glpi_computers`.`computermodels_id` = `glpi_computermodels`.`id`
                                              ) LEFT JOIN `glpi_items_operatingsystems` 
                                          ON (`glpi_computers`.`id` = `glpi_items_operatingsystems`.`items_id`
                                              AND `glpi_items_operatingsystems`.`itemtype` = 'Computer'
                                              ) LEFT JOIN `glpi_operatingsystems`  AS `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`
                                          ON (`glpi_items_operatingsystems`.`operatingsystems_id` = `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`.`id`
                                              )LEFT JOIN `glpi_locations` 
                                          ON (`glpi_computers`.`locations_id` = `glpi_locations`.`id`
                                              ) LEFT JOIN `glpi_items_deviceprocessors` 
                                          ON (`glpi_computers`.`id` = `glpi_items_deviceprocessors`.`items_id`
                                              AND `glpi_items_deviceprocessors`.`itemtype` = 'Computer'
                                              ) LEFT JOIN `glpi_deviceprocessors`  AS `glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`
                                          ON (`glpi_items_deviceprocessors`.`deviceprocessors_id` = `glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`id`
                                              ) LEFT JOIN `glpi_plugin_fields_computercustomones`  AS `glpi_plugin_fields_computercustomones_numberonefield`
                                          ON (`glpi_computers`.`id` = `glpi_plugin_fields_computercustomones_numberonefield`.`items_id`
                                              AND `glpi_plugin_fields_computercustomones_numberonefield`.`itemtype` = 'Computer'
                                              )  WHERE  `glpi_computers`.`is_deleted` = 0  AND `glpi_computers`.`is_template` = 0  AND (    (`glpi_plugin_fields_computercustomones`.`numberonefield` = 123)  ) GROUP BY `glpi_computers`.`id` ORDER BY ITEM_Computer_1 ASC 
  Error: Unknown column 'glpi_plugin_fields_computercustomones.numberonefield' in 'where clause'
  Backtrace :
  inc\search.class.php:1246                          
  inc\search.class.php:98                            Search::constructData()
  inc\search.class.php:80                            Search::showList()
  front\computer.php:39                              Search::show()
  {"user":"2@ATS-PC"} 
[2019-10-25 15:52:51] glpisqllog.ERROR: DBmysql::query() in C:\wamp64\www\GLPI\glpi-9.4.4-temp\www\inc\dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT DISTINCT `glpi_monitors`.`id` AS id, 'glpi' AS currentuser,
                        `glpi_monitors`.`entities_id`, `glpi_monitors`.`is_recursive`,  `glpi_monitors`.`name` AS `ITEM_Monitor_1`,
                        `glpi_monitors`.`id` AS `ITEM_Monitor_1_id`,
                        `glpi_states`.`completename` AS `ITEM_Monitor_31`,  `glpi_manufacturers`.`name` AS `ITEM_Monitor_23`,  `glpi_locations`.`completename` AS `ITEM_Monitor_3`,  `glpi_monitortypes`.`name` AS `ITEM_Monitor_4`,  `glpi_monitormodels`.`name` AS `ITEM_Monitor_40`,  `glpi_monitors`.`date_mod` AS `ITEM_Monitor_19`,  `glpi_monitors`.`contact` AS `ITEM_Monitor_7`,  `glpi_plugin_fields_monitorcustomones_textonefield`.`textonefield` AS `ITEM_Monitor_76665` FROM `glpi_monitors`LEFT JOIN `glpi_states` 
                                          ON (`glpi_monitors`.`states_id` = `glpi_states`.`id`
                                              )LEFT JOIN `glpi_manufacturers` 
                                          ON (`glpi_monitors`.`manufacturers_id` = `glpi_manufacturers`.`id`
                                              )LEFT JOIN `glpi_locations` 
                                          ON (`glpi_monitors`.`locations_id` = `glpi_locations`.`id`
                                              )LEFT JOIN `glpi_monitortypes` 
                                          ON (`glpi_monitors`.`monitortypes_id` = `glpi_monitortypes`.`id`
                                              )LEFT JOIN `glpi_monitormodels` 
                                          ON (`glpi_monitors`.`monitormodels_id` = `glpi_monitormodels`.`id`
                                              ) LEFT JOIN `glpi_plugin_fields_monitorcustomones`  AS `glpi_plugin_fields_monitorcustomones_textonefield`
                                          ON (`glpi_monitors`.`id` = `glpi_plugin_fields_monitorcustomones_textonefield`.`items_id`
                                              AND `glpi_plugin_fields_monitorcustomones_textonefield`.`itemtype` = 'Monitor'
                                              )  WHERE  `glpi_monitors`.`is_deleted` = 0  AND `glpi_monitors`.`is_template` = 0  AND (    (`glpi_plugin_fields_monitorcustomones`.`textonefield`  LIKE '%abc%'  ) ) ORDER BY ITEM_Monitor_1 ASC 
  Error: Unknown column 'glpi_plugin_fields_monitorcustomones.textonefield' in 'where clause'
  Backtrace :
  inc\search.class.php:1246                          
  inc\search.class.php:98                            Search::constructData()
  inc\search.class.php:80                            Search::showList()
  front\monitor.php:39                               Search::show()
  {"user":"2@ATS-PC"} 
[2019-10-26 07:17:23] glpisqllog.ERROR: DBmysql::query() in C:\wamp64\www\GLPI\glpi-9.4.4-temp\www\inc\dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT DISTINCT `glpi_computers`.`id` AS id, 'glpi' AS currentuser,
                        `glpi_computers`.`entities_id`, `glpi_computers`.`is_recursive`,  `glpi_computers`.`name` AS `ITEM_Computer_1`,
                        `glpi_computers`.`id` AS `ITEM_Computer_1_id`,
                        `glpi_states`.`completename` AS `ITEM_Computer_31`,  `glpi_manufacturers`.`name` AS `ITEM_Computer_23`,  `glpi_computers`.`serial` AS `ITEM_Computer_5`,  `glpi_computertypes`.`name` AS `ITEM_Computer_4`,  `glpi_computermodels`.`name` AS `ITEM_Computer_40`,  `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`.`name` AS `ITEM_Computer_45`,  `glpi_locations`.`completename` AS `ITEM_Computer_3`,  `glpi_computers`.`date_mod` AS `ITEM_Computer_19`,   GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`designation`, '__NULL__'),
                                               '$#$',`glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`id`) ORDER BY `glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`id` SEPARATOR '$$##$$')
                              AS `ITEM_Computer_17`,
                  
                  `glpi_plugin_fields_computercustomones_textonefield`.`textonefield` AS `ITEM_Computer_76665` FROM `glpi_computers`LEFT JOIN `glpi_states` 
                                          ON (`glpi_computers`.`states_id` = `glpi_states`.`id`
                                              )LEFT JOIN `glpi_manufacturers` 
                                          ON (`glpi_computers`.`manufacturers_id` = `glpi_manufacturers`.`id`
                                              )LEFT JOIN `glpi_computertypes` 
                                          ON (`glpi_computers`.`computertypes_id` = `glpi_computertypes`.`id`
                                              )LEFT JOIN `glpi_computermodels` 
                                          ON (`glpi_computers`.`computermodels_id` = `glpi_computermodels`.`id`
                                              ) LEFT JOIN `glpi_items_operatingsystems` 
                                          ON (`glpi_computers`.`id` = `glpi_items_operatingsystems`.`items_id`
                                              AND `glpi_items_operatingsystems`.`itemtype` = 'Computer'
                                              ) LEFT JOIN `glpi_operatingsystems`  AS `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`
                                          ON (`glpi_items_operatingsystems`.`operatingsystems_id` = `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`.`id`
                                              )LEFT JOIN `glpi_locations` 
                                          ON (`glpi_computers`.`locations_id` = `glpi_locations`.`id`
                                              ) LEFT JOIN `glpi_items_deviceprocessors` 
                                          ON (`glpi_computers`.`id` = `glpi_items_deviceprocessors`.`items_id`
                                              AND `glpi_items_deviceprocessors`.`itemtype` = 'Computer'
                                              ) LEFT JOIN `glpi_deviceprocessors`  AS `glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`
                                          ON (`glpi_items_deviceprocessors`.`deviceprocessors_id` = `glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`id`
                                              ) LEFT JOIN `glpi_plugin_fields_computercustomones`  AS `glpi_plugin_fields_computercustomones_textonefield`
                                          ON (`glpi_computers`.`id` = `glpi_plugin_fields_computercustomones_textonefield`.`items_id`
                                              AND `glpi_plugin_fields_computercustomones_textonefield`.`itemtype` = 'Computer'
                                              )  WHERE  `glpi_computers`.`is_deleted` = 0  AND `glpi_computers`.`is_template` = 0  AND (    (`glpi_plugin_fields_computercustomones`.`textonefield`  LIKE '%abc%'  ) ) GROUP BY `glpi_computers`.`id` ORDER BY ITEM_Computer_1 ASC 
  Error: Unknown column 'glpi_plugin_fields_computercustomones.textonefield' in 'where clause'
  Backtrace :
  inc\search.class.php:1246                          
  inc\search.class.php:98                            Search::constructData()
  inc\search.class.php:80                            Search::showList()
  front\computer.php:39                              Search::show()
  {"user":"2@ATS-PC"}

**Comment by stonebuzz** [comment]
Hi @Nem-Tom 

can you try to regenerate bloc ?

![image](https://user-images.githubusercontent.com/7335054/72890243-c827a080-3d11-11ea-8768-72ca06007299.png)

Best regards

**Comment by marcamouzoun** [comment]
I have also the same problem. even after regenerating bloc

**Comment by marcamouzoun** [comment]
need help

**Comment by Nem-Tom** [comment]
My mistake is gone.
glpi 9.4.4 is broken.
glpi 9.4.5 works fine.
