### ISSUE TITLE
Champ obligatoire

### ISSUE THREAD

**Issue by FMiot** [pluginsGLPI/fields#34]
Bonjour,

Lorsque l'on passe le champ en champ obligatoire (version 0.90-1.2 du plugin) même si il est remplis, a la sauvegarde du ticket un message d'erreur apparaît en disant champ non renseigné et le ticket est tout de même créé mais le message apparaît.

Par contre le vrai problème c'est que l'on ne peux pas clôturer le ticket car le message champ non renseigné apparaît toujours et empêche la clôture du ticket.

Merci

**Comment by trasher** [comment]
Bonjour,

Je viens de tester avec la version de développement du plugin, il semble que ce problème ait été corrigé ; je n'ai pas été en mesure de le reproduire

**Comment by trasher** [comment]
Should be fixed in 0.90-1.3; feel free to reopen the ticket if the issue is still present.
