### ISSUE TITLE
1.10.1 : unable to use compare values in search for an additional field

### ISSUE THREAD

**Issue by tuxxic** [pluginsGLPI/fields#340]
Hello,

I am unable to do a query in my custom field which has "number" as type.

My goal is to select entities which have "more than" the number, or "less than" the number, but I only can choose an exact value :

![image](https://user-images.githubusercontent.com/4680438/67932539-63522380-fbc4-11e9-9d22-342d4e3bb634.png)

Is "Number" the right type for me or is it a bug ?

**Comment by stonebuzz** [comment]
Hi @tuxxic 

actually this feature is not available, but very interesting,

you can propose a PR to implement it (changing behavior of searchoption) or contact us here [GLPI Network](https://portal.glpi-network.com/plugins/formcreator/front/formdisplay.php?id=16)

best regards

**Comment by tuxxic** [comment]
Hi @stonebuzz, thanks for the labels :)

I have already subscribed a GLPI Network subscription, but it doesn't covers fields since I am not in the higher level :(

At any case, I am willing to test a patch, in case you release it :)
