### ISSUE TITLE
unable to add fields to UDE's

### ISSUE THREAD

**Issue by lorenafoia** [pluginsGLPI/fields#341]
I'm trying to create a field to UDEs, but right now it's not possible to attach a field to a UDE, because it doesn't appear in the the list.

**Comment by Du-St** [comment]
@lorenafoia Hi, I am also facing problems when the custom field is not possible to associate to some item types or it is possible to associate but the custom field does not appear.

Could you please be more specific what does the "UDE" mean?

Thank you!

D.

**Comment by lorenafoia** [comment]
@Du-St Oh, I forgot to translate that, what I meant was PDU (Power Distribution Unit).

**Comment by Du-St** [comment]
@lorenafoia Ah, I see. In that case, we have no issue in common.

However, this easy quick patch on 1.10.2 should help you with your issue:

+++ plugins/fields/inc/container.class.php      2019-11-26 21:12:07.922176794 +0100
@@ -757,7 +757,8 @@
          'Printer'          => Printer::getTypeName(2),
          'CartridgeItem'    => CartridgeItem::getTypeName(2),
          'ConsumableItem'   => ConsumableItem::getTypeName(2),
-         'Phone'            => Phone::getTypeName(2)
+         'Phone'            => Phone::getTypeName(2),
+         'PDU'              => PDU::getTypeName(2),
       ];
 
       $tabs[__('Assistance')] = [


Let me know if it works. I can create a pull request afterwards.

**Comment by lorenafoia** [comment]
It worked. Thank you! 😃
