### ISSUE TITLE
Search do not works with custom fields

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/fields#345]
Hello,

I created a a field Yes/No but when I do a search using this field it doesn't work.

Version : 1.10.2
GLPI : 9.4.4

**Comment by stonebuzz** [comment]
Hi @lolokai ,

I'm not reproducing your problem.

Can you give us screenshot concerning your search ?
Have you got some error on log file (glpi / apache) ?

Best regards

**Comment by marcamouzoun** [comment]
I have also the same problem. need help
