### ISSUE TITLE
Unable to add fields on to device network card model

### ISSUE THREAD

**Issue by AndrewG-usr** [pluginsGLPI/fields#347]
Hello I have found that I am unable to add fields to Device networkcard model... I would like to add some card specific specifications to network card models but even though I can select it in my block I and add a field to it the additional fields do now show up when I go to look at the cards.

Perhaps this is  bug or maybe I am missing something? any help would be apricated! 

Thanks.

version 1.10.2

**Comment by stonebuzz** [comment]
Hi @AndrewG-usr 

can you test this PR -> https://github.com/pluginsGLPI/fields/pull/350

Best regards
