### ISSUE TITLE
Class PluginFieldsTicketenvironnement not found in container.class.php

### ISSUE THREAD

**Issue by tuxxic** [pluginsGLPI/fields#360]
Hello,

When trying to do a massive action in my GLPI, I have a blank page and it blocks.

So I got to the error.log file, and I saw this 👍 

`[Thu Jan 30 14:45:20.718831 2020] [:error] [pid 4421] [client xxx.xxx.xxx.xxx:53265] PHP Fatal error:  Uncaught Error: Class 'PluginFieldsTicketenvironnement' not found in /var/www/glpi/plugins/fields/inc/container.class.php:540\nStack trace:\n#0 /var/www/glpi/inc/plugin.class.php(1112): PluginFieldsContainer::preItemPurge(Object(Ticket))\n#1 /var/www/glpi/inc/commondbtm.class.php(1656): Plugin::doHook('pre_item_purge', Object(Ticket))\n#2 /var/www/glpi/inc/massiveaction.class.php(1075): CommonDBTM->delete(Array, 1)\n#3 /var/www/glpi/inc/massiveaction.class.php(990): MassiveAction::processMassiveActionsForOneItemtype(Object(MassiveAction), Object(Ticket), Array)\n#4 /var/www/glpi/inc/massiveaction.class.php(969): MassiveAction->processForSeveralItemtypes()\n#5 /var/www/glpi/front/massiveaction.php(59): MassiveAction->process()\n#6 {main}\n  thrown in /var/www/glpi/plugins/fields/inc/container.class.php on line 540, referer: http://glpi/glpi/front/ticket.php`

What can go wrong ?

By the way, I have created various blocks, where "environnement" is one of them, which I see in PluginFieldsTicket**environnement**

Can you please tell me how to solve this ?

Thanks in advance !

**Comment by stonebuzz** [comment]
Hi @tuxxic 

try to regenerate block.

Best regards

**Comment by tuxxic** [comment]
Hi @stonebuzz 

I installed fields 1.10.2 freshly released and it solved my issue.

Thanks for help
