### ISSUE TITLE
Cannot open Additionnal fields

### ISSUE THREAD

**Issue by zzendon** [pluginsGLPI/fields#363]
![image](https://user-images.githubusercontent.com/43130955/74314109-2ece3600-4d75-11ea-94f6-dab1a9d57355.png)

error when opening Additionnal fields

**Comment by zzendon** [comment]
![image](https://user-images.githubusercontent.com/43130955/74314185-4e655e80-4d75-11ea-8553-68418b2fb024.png)

**Comment by zzendon** [comment]
in combination with File Injection

**Comment by stonebuzz** [comment]
Hi @zzendon 

can you give us more informations ? 

- step to reproduce
- glpi version
- plugin version
- apache2 / nginx

Best regards

**Comment by zzendon** [comment]
HI @stonebuzz 

- When i login to GLPI and i want to add a new Additional field Then i get the second picture

- The first one i get when i want to add something to a Additional field.

glpi version:
9.4.5

Plugin version:
1.10.2

Apache2 centos 7

**Comment by stonebuzz** [comment]
can you past here the result of this query

```sql
select * from glpi_plugin_fields_containers
```

Best regards

**Comment by stonebuzz** [comment]
duplicate with #334

**Comment by zzendon** [comment]
MariaDB [glpi]> select * from glpi_plugin_fields_containers;
+----+---------------+----------------+--------------+--------+---------+-------------+--------------+-----------+
| id | name          | label          | itemtypes    | type   | subtype | entities_id | is_recursive | is_active |
+----+---------------+----------------+--------------+--------+---------+-------------+--------------+-----------+
|  4 | productnummer | Product nummer | ["0"]        | domtab | NULL    |           0 |            0 |         1 |
|  6 | pcnaam        | Computers      | ["Computer"] | dom    | NULL    |           0 |            0 |         1 |
+----+---------------+----------------+--------------+--------+---------+-------------+--------------+-----------+

**Comment by stonebuzz** [comment]
You have a line with a ["0"] value for itemtypes column (that is the problem), update it to a real class (ie Computer / Ticket etc ...) et issue should be ok.

**Comment by zzendon** [comment]
Yess!!
That worked thank you!
