### ISSUE TITLE
"Add a new translation" -> Access denied.

### ISSUE THREAD

**Issue by Megachip** [pluginsGLPI/fields#366]
<img width="154" alt="image" src="https://user-images.githubusercontent.com/487352/75370105-e65e5e80-58c4-11ea-9872-59b1a162742c.png">
Super-Admin, root entity, GLPI 9.4.5, fields 1.10.3

**Comment by stonebuzz** [comment]
Hi @Megachip 

can you test this PR -> https://github.com/pluginsGLPI/fields/pull/367

Best regards

**Comment by OscarBeiro** [comment]
Hi,

It's working fine on 9.4.X. and 1.10.3 with https://github.com/pluginsGLPI/fields/pull/367

Thanks
