### ISSUE TITLE
1.8.4  displaying BUG - Problem with HTML

### ISSUE THREAD

**Issue by MarcGach** [pluginsGLPI/fields#370]
stonebuzz told me to create a another issue.
i took a screenshot about my prob.
![loo](https://user-images.githubusercontent.com/54810704/76433811-276e6c80-63b5-11ea-88a4-4862697db2c9.PNG)

**Comment by stonebuzz** [comment]
hi @Green7Kraken can you test this PR (is GLPI side)

Best regards

**Comment by Green7Kraken** [comment]
Sorry, i don't understand "PR ":/
i'm french, so i don't really understand english subtility

**Comment by Green7Kraken** [comment]
I need to download the new version of GLPI Fields ?

**Comment by stonebuzz** [comment]
Nop, just apply patch on glpi 9.4.5 =)

**Comment by Green7Kraken** [comment]
Oh ok !
So it's was in the GLPI code !

**Comment by Green7Kraken** [comment]
Heuu, but i don't how apply this patch, i must reinstall GLPI ?

**Comment by stonebuzz** [comment]
https://www.thegeekstuff.com/2014/12/patch-command-examples/

"i must reinstall GLPI " -> no because fix is just a PR for the moment

**Comment by stonebuzz** [comment]
Fixed bye https://github.com/glpi-project/glpi/pull/7039

Best regards
