### ISSUE TITLE
Cannot add additional field into a "Objects management" plugin created asset

### ISSUE THREAD

**Issue by hugollanos** [pluginsGLPI/fields#372]
Hello, I cannot add a new field through the "Additionnal fields" plugin to a new asset type created with the "Objects management" plugin. The new field created does not appear in the drop-down list where it is assigned to the registration form of the new asset.
Is there some kind of incompatibility?
I use GLPI v9.4.5, "Additional fields" v1.10.3 and "Objects management" v2.8.0

Thanks in advanced!

**Comment by stonebuzz** [comment]
Hi @hugollanos 

Because genericobject implement it's own system to add fields.

If you want to add field to a genericobject see this -> https://glpi-plugins.readthedocs.io/en/latest/genericobject/index.html

Best regards

**Comment by hugollanos** [comment]
Thank you!

Grretings.
