### ISSUE TITLE
Use existing dropdown in "additional fields" block

### ISSUE THREAD

**Issue by J-C-P** [pluginsGLPI/fields#374]
Hi,

More a question/request than a real issue :-)
Is it possible to add existing dropdown in custom block ?

For instance, I would like to add a custom block for the "Line" item with technical informations. Those informations include both end sites of the line. Those two fields are existing locations but I don't find how I can use the existing "Location" dropdown in my custom block.

Is it possible? If yes, how ?

Thanks,
Have a great confinement ;-)

**Comment by stonebuzz** [comment]
HI @J-C-P 

actually not, dropdown fields is for new dropdwon, you can't re-use native dropdown from GLPI.

Best regards

**Comment by stonebuzz** [comment]
@J-C-P 

Implemented on latest version , i close this issue 

Best regards
