### ISSUE TITLE
Question : Compatibility with fields plugin

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/fields#375]
Hello,

Would it be possible to add fields plugin fieds visible by generic object plugin ?

Thank you for your answer

Take care

**Comment by stonebuzz** [comment]
Hi @yalgva  

No, because genericobject implement it's own system to add fields.

If you want to add field to a genericobject see this -> https://glpi-plugins.readthedocs.io/en/latest/genericobject/index.html

Best regards
