### ISSUE TITLE
Error after Glpi 9.4.6 update

### ISSUE THREAD

**Issue by NT3R117** [pluginsGLPI/fields#380]
Hello,

I'm experiencing an issue with this plugin since GLPI upgradeto version 9.4.6 :

Upgrade procedure : 

- Creating new OLD folder and inserting old GLPI files
- Installing new version of GLPI
- Copying files and plugins
- Enabling plugins in GLPI

I'm getting this error in glpi log files : 

[Mon May 18 12:58:55.122184 2020] [php7:error] [pid 4047] [client myclient] PHP Fatal error:  Uncaught Error: Class 'PluginFieldsTicketexternalid' not found in /var/www/env/plugins/fields/inc/field.class.php:603\nStack trace:\n#0 /var/www/env/plugins/fields/inc/field.class.php(465): PluginFieldsField::prepareHtmlFields(Array, '55', 'Ticket', true)\n#1 /var/www/env/plugins/fields/inc/container.class.php(964): PluginFieldsField::showForTabContainer('6', '55', 'Ticket')\n#2 /var/www/env/inc/commonglpi.class.php(485): PluginFieldsContainer::displayTabContentForItem(Object(Ticket), 'externalid', '')\n#3 /var/www/env/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(Ticket), 'PluginFieldsCon...', '', Array)\n#4 {main}\n  thrown in /var/www/env/plugins/fields/inc/field.class.php on line 603, referer: http://env/front/ticket.form.php?id=55

I'm I doing something wrong ?

Thanks for your time,

**Comment by trasher** [comment]
Ensure you've migrated plugin data files from old glpi dir to new one, ensure ACLs are correct, ... And other anwser for similar issues:
https://github.com/pluginsGLPI/fields/issues?q=is%3Aissue+Class+not+found+is%3Aclosed

**Comment by NT3R117** [comment]
Hi trasher, thanks for your help, regenerating blocks worked for me :)
