### ISSUE TITLE
Unable to create fields for Certificates

### ISSUE THREAD

**Issue by lfardin** [pluginsGLPI/fields#383]
Although this plugin allows to add new fields to the dropdown table "certificates types", its not possible to add fields to "certificates".

GLPI version 9.4.5
Fields plugin release 1.10.3

**Comment by stonebuzz** [comment]
Hi @lfardin 

have you try develop branch ?

Best regards

**Comment by lfardin** [comment]
Hi @stonebuzz,
i haven't tried the develop branch since it was tested on a GLPI server in production environment.

But i figured out that, although not listing Certificates at the Container dropdown list, when editing directly at the database the itemtypes field at table glpi_plugins_field_containers the the value ["Certificate"], it was possible to use the feature.

That said, it was probably an issue at the dropdown list at container.form.php.

**Comment by yumibad** [comment]
how did you add the "certificate" table glpi_plugins_field_containers?

**Comment by lfardin** [comment]
First step: use the glpi interface to create a container, selecting any other container type (for instance: ["Computer"])
Second step: conect to GLPI database, and query the container ID at "glpi_plugins_field_containers" table
Third step: execute an update to the table, defining the field "itemtypes" value to _["Certificate"]_ for the selected container.
Fourth step: go back to GLPI interface and continue the container configuration.

**Comment by yumibad** [comment]
Would that be the command?
update glpi_plugin_fields_containers set itemtypes = '["Certificate"]' where id = 2;

**Comment by lfardin** [comment]
Did you execute the Regenerate Files command when finished the creation of the container / fields?

**Comment by yumibad** [comment]
it worked.
thanks

**Comment by cedric-anne** [comment]
Done in #410.
