### ISSUE TITLE
Set fields as required to close a ticket

### ISSUE THREAD

**Issue by ghiglesias** [pluginsGLPI/fields#385]
Hi!
Is is possible to set a field as required, in order to validate it is complete when closing a ticket?
I add 2 data-time type custom fields in ticket form, and I want to validate this fields are not empty when closing the ticket.
Thanks!

**Comment by stonebuzz** [comment]
Hi @ghiglesias 

yes it's possible

![image](https://user-images.githubusercontent.com/7335054/86110775-4446c100-bac6-11ea-9c1d-cff3bca36f94.png)


Best regards
