### ISSUE TITLE
[1.11.0-rc1]PHP Notice (8): Trying to access array offset on value of type null in /var/www/html/glpi95/marketplace/fields/inc/container.class.php at line 1267

### ISSUE THREAD

**Issue by ladenree76000** [pluginsGLPI/fields#386]
fields upgraded from 1.9.1 to 1.11.0-RC1 + glpi9.5 RC2
1 block (2 fields+header) for tickets 
upgrade using marketplace.

in debug mode :

displaying an asset (whatever computer,monitor, software, contract, appliances, users, groups, profiles  

displays **PHP Notice (8): Trying to access array offset on value of type null in /var/www/html/glpi95/marketplace/fields/inc/container.class.php at line 1267**

But no notice when displaying a ticket

**Comment by cedric-anne** [comment]
Hi @ladenree76000 ,

This is related to usage of PHP 7.4. Can you check if #387 fixes your issue ?

Regards
