### ISSUE TITLE
Add fields - Appliances Menu ( GLPI 9.5)

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/fields#389]
Hello!
With the new version 9.5, several new options have entered.
One of them is Management> Appliances

this will help to control the applications that we have in our environment. However, the fields there are still few and there is a need to create new ones.

It would be a good idea for the FIEDS plugin to also add fields to this new menu.

![image](https://user-images.githubusercontent.com/35368369/87056690-5e765280-c1dc-11ea-8bc0-6ef0eaf43139.png)

![image](https://user-images.githubusercontent.com/35368369/87056137-9761f780-c1db-11ea-8213-b4eade8985a1.png)

**Comment by cedric-anne** [comment]
Done in #410.
