### ISSUE TITLE
Droits modif champ

### ISSUE THREAD

**Issue by LucasLEL** [pluginsGLPI/fields#39]
Bonjour, 

Tout d'abord, merci pour ce plugin. 

J'aimerai savoir si il serait possible de le modifier quelque peu pour accorder ou non la modification d'un champ selon le profil de l'utilisateur.
Exemple dans le cadre d'un base en accès libre : 
- Un champ ID : c'est un champ "d'inventaire" il pourrait être modifié uniquement par les administrateurs. 
-  Un champ "Location" : c'est un champ en "mouvement" il pourrait être modifié par tous. Par exemple, l'utilisateur ABC prend un PC pour son poste de travail, il saisi alors en "location" : Poste de travail de ABC

Je ne pense pas que ce soit très compliqué à réaliser avec votre plugin en base. Simplement, lors de la création de la table fields, ajouter une colonne "droits" dans laquelle il y aura les numéros d'id des profils qui pourrait le modifier (ça inclut donc une ligne de plus sur l'interface de l'ajout de champ, où l'utilisateur selectionnerait le type de profil nécéssaire pour modif).
Et du coup lors du clic sur le bouton "Save". Pour enregistrer un champ, on comporte le profil de celui qui a cliqué sur le bouton à celui enregistré dans la base pour ce champ. Si c'est le meme l'update se fait, sinon ça update le reste mais pas celui là ... 

J'espere que ce sera possible :)
Merci !

**Comment by stonebuzz** [comment]
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
