### ISSUE TITLE
V1.11.0 : Error during install on GLPI 9.4.6

### ISSUE THREAD

**Issue by dedisoft** [pluginsGLPI/fields#391]
Hello,

I'm trying to install this plugin on GLPI 9.4.6.

After upoloading the plugin on the plugin folder, I've an error 500 when accessing the plugin page.

[15-Jul-2020 11:18:27 Europe/Paris] PHP Fatal error:  Uncaught Error: Call to undefined method Plugin::getPhpDir() in /plugins/fields/setup.php:37
Stack trace:
#0 /inc/plugin.class.php(316): include_once()
#1 /inc/plugin.class.php(318): Plugin->{closure}()
#2 /inc/plugin.class.php(287): Plugin->checkPluginState('fields')
#3 /front/plugin.php(40): Plugin->checkStates(true)
#4 {main}
  thrown in /plugins/fields/setup.php on line 37

What can I do ?

Thanks

**Comment by cedric-anne** [comment]
Hi,

The version 1.11 is compatible only with GLPI 9.5. For GLPI 9.4.6, you have to use previous version.

Regards
