### ISSUE TITLE
Error when copying to plugins dir

### ISSUE THREAD

**Issue by nathanks** [pluginsGLPI/fields#393]
When I copy the 'fields' folder into the GLPI plugin directory, I am no longer able to visit /front/plugin.php and am presented with the following error:

Fatal error: Uncaught Error: Call to undefined method Plugin::getPhpDir() in /var/www/glpi/plugins/fields/setup.php:37 Stack trace: #0 /var/www/glpi/inc/plugin.class.php(316): include_once() #1 /var/www/glpi/inc/plugin.class.php(318): Plugin->{closure}() #2 /var/www/glpi/inc/plugin.class.php(287): Plugin->checkPluginState() #3 /var/www/glpi/front/plugin.php(40): Plugin->checkStates() #4 {main} thrown in /var/www/glpi/plugins/fields/setup.php on line 37

My env is :
GLPI 9.4.5
PHP 7.4.6

**Comment by cedric-anne** [comment]
Hi,

The version you used is compatible with 9.5, but not with GLPI 9.4.
Please use previous version.

Regards
