### ISSUE TITLE
API apirest.php/PluginFieldsComputermyfield/

### ISSUE THREAD

**Issue by TBastien** [pluginsGLPI/fields#395]
Hi, since version 9.5 of GLPI and the update of the plugin I can't update fields via API.
I see nginx log and i have this :

FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot declare class PluginFieldsComputerutilisateurad, because the name is already in use in /var/www/.....

My python request : 
requests.put('%s/apirest.php/PluginFieldsComputerpropritaire/' % urlglpi,  headers = {'Session-Token':session_token,'App-Token':apptoken,'Content-Type': 'application/json'},data = json.dumps({"input": [{'id':fields_id,'items_id':id_pc, 'itemtype':'computer','plugin_fields_proprietairefielddropdowns_id':'2', 'maintenancefield':'1','dateheurefield':dateetheure } ] } ))
        

GLPI 9.5.1 - PluginFields 1.11.0 - debian 10.4 - php 7.3

Thanks for your help

**Comment by lermit4** [comment]
Hi,

I have the same problem with the same message.
What is the origin of the problem?

GLPI 9.5.1 - PluginFields 1.11.0 - Debian 4.19.118-2+deb10u1 - PHP 7.4.7

**Comment by eddiegordo** [comment]
Hi,
Same issue here.
GLPI 9.5.3
PluginField 1.12.0
PHP 8.0

Got it working by a editing file \plugins\fields\inc\autoload.php 
In the _autoload_ function, replaced line 57
`return include($test);`
with
`return include_once($test);`

Don't know if this is the right way, but I got no more error and the fields are getting updated using API

**Comment by KongNan** [comment]
I saw same problem in forum, and the eddiegordo's solution works for me:
https://forum.glpi-project.org/viewtopic.php?id=278854

Thank you eddiegordo, and hope this can be fixed officially
