### ISSUE TITLE
Can not add more than one watchers

### ISSUE THREAD

**Issue by kvk15** [pluginsGLPI/fields#401]
Can not add more than one watchers.
![Screenshot from 2020-08-17 12-20-13](https://user-images.githubusercontent.com/11851851/90379903-06a4f400-e084-11ea-8745-692c0dbd5eb2.png)
Version GLPI 9.5.1
PHP 7.2.24-0ubuntu0.18.04.6
Browsers:  Chromium Version 84.0.4147.89 (Developer Build) Fedora Project (64-bit)  and Firefox 78.0.2

**Comment by cedric-anne** [comment]
Hi,

This seems not related to fields plugin itself and duplicates https://github.com/glpi-project/glpi/issues/7766 .

Regards
