### ISSUE TITLE
Blank page when adding item in Dropdown.

### ISSUE THREAD

**Issue by MikiVazquez** [pluginsGLPI/fields#403]
GLPI: 9.5.1
Plugin: 1.11.0

Blank page when adding item in Dropdown.

Both when I click on the key it enters in the creation of the field, as when I am adding values in the edition of the asset. Clicking opens a new blank page. The url it calls is this in my example:

https://xx.xx.xx.xx/marketplace/fields/front/commondropdown.php?ddtype=metodoevalucioninicialfielddropdown

Please can you look at it, thank you!

**Comment by trasher** [comment]
Please provide related logs (check both GLPI and system ones).

**Comment by MikiVazquez** [comment]
@trasher Sorry, I think the problem it's in TAG pluggins I New Insurre in TAG https://github.com/pluginsGLPI/tag/issues/109
Information:

GLPI: 9.5.1
Additionnal fields Version: 1.11.0
Tag Management: 2.7.0

Stage:
New Fieds Type Dropdown click in add new item->blank page :(

If I look in log I can see:
==> php-errors.log <==
[2020-08-26 19:03:32] glpiphplog.CRITICAL: *** Uncaught Exception Error: Cannot instantiate abstract class CommonDropdown in /var/www/html/glpi/marketplace/tag/inc/tag.class.php at line 740
Backtrace :
marketplace/tag/setup.php:110 PluginTagTag::getCurrentItemtype()
inc/plugin.class.php:224 plugin_init_tag()
inc/plugin.class.php:186 Plugin::load()
inc/includes.php:105 Plugin->init()
marketplace/fields/front/commondropdown.php:3 include()

Additional Information:
if I deactivate the TAG plugins it works correctly.

Please can you review it, thank you very much!

**Comment by stonebuzz** [comment]
Can you test this PR

https://github.com/pluginsGLPI/tag/pull/111

Best regards
