### ISSUE TITLE
update custom field via API

### ISSUE THREAD

**Issue by vquie** [pluginsGLPI/fields#404]
Hello,

I know this might have been asked several times but none of the solutions have worked for me so far.

I've got this block called `customfield` with a custom field called `Cost Unit` which I want to update using the REST API.

According to some advices I have already found I should PUT the data `'{"input": { "costunitfield": "ABC" }}'` to https://glpi/apirest.php/Computer/123

The response I always get is `[{"123":true,"message":""}]` with nothing updated in GLPi.

`/apirest.php/listSearchOptions/computer` gives me a map for the correct field with the id 76665 which I also tried to update with no luck.

`/apirest.php/Computer/123` doesn't show this field at all.

Thanks in advance.

**Comment by vquiering** [comment]
anyone?

**Comment by vquiering** [comment]
Still none? There has to be someone who at least tried to update a field using the api.

**Comment by redisded** [comment]
Hi,

probably not the solution you want to read, but 8 update my custom fields in bash scripts by updating the database without problems since several month.

**Comment by Pierre49300** [comment]
Hi,
this ps1 code works for me 

`$body='{"input": { "id":123 , "costunitfield": "ABC"}}'

$Parameters = @{
    Method = "PUT"
    Uri =  "https://<yoururl>/apirest.php/Computer/"
    Headers = $headers
    Body = $body
}`

**Comment by static302** [comment]
Hi,
@Pierre49300 First of all, thanks for sharing. Does your field type is common text?

Anyone have success stories for updating dropdown field?

**Comment by Pierre49300** [comment]
HI @static302, yes it's a common text, not dropdown field

**Comment by quentinlegay** [comment]
Hi @vquie, can you give me the name of the block (+ label) of your custom field (name of the tab/category of the field)
Thanks

**Comment by vquie** [comment]
> Hi @vquie, can you give me the name of the block (+ label) of your custom field (name of the tab/category of the field)
> Thanks

Thanks for your response, but it has been years already. I am working for a different company now and this is not an issue for me anymore as I don't use this plugin anymore. I couldn't even answer it if I tried to. :-) 

I am closing this.

**Comment by Silejonu** [comment]
Dropdown fields must be updated in a specific way. Consider the following:

```json
"4": {
  "name": "Type",
  "table": "glpi_computertypes",
  "field": "name",
  "datatype": "dropdown",
  "nosearch": false,
  "nodisplay": false,
  "available_searchtypes": [
    "contains",
    "notcontains",
    "equals",
    "notequals"
  ],
  "uid": "Computer.ComputerType.name"
},
```

To update, you should use the value of `table` but remove the `glpi_` prefix and add the `_id` suffix. If you're using `curl`, this would result in the following command:

```bash
curl --silent --globoff --request PATCH \
  --header 'Content-Type: application/json' \
  --header 'Session-Token: foo' \
  --header 'App-Token: bar' |
  --data '{"input": {"computertypes_id": "1"}}' \
  https://glpi.domain.name/Computer/123
```
