### ISSUE TITLE
Stop working on GLPI 9.5.2

### ISSUE THREAD

**Issue by lucastva** [pluginsGLPI/fields#413]
After update GLPI for 9.5.2 the Fields Plugin not work corretly.

Check prints bellow:

![image](https://user-images.githubusercontent.com/71664545/96176523-dd2d0b00-0f02-11eb-893f-d591c588ca3a.png)

![image](https://user-images.githubusercontent.com/71664545/96176689-0f3e6d00-0f03-11eb-8743-a1e695a8fe3e.png)

**Comment by stonebuzz** [comment]
Hello

can you activate the debug mode to see if any errors occur?

Have you got any errors on glpi log files ?

Did you try to regenerate container files ?

![image](https://user-images.githubusercontent.com/7335054/96220806-bf56b900-0f89-11eb-8654-6d1f689892d5.png)

Best regards

**Comment by CaraNeS** [comment]
Hello,

I have the same issue after update to 9.5.2.
1) No error in debug mode
2) No error in GLPI Logs
3) Regenerate container files -> nothing
4) Disable/Enable block -> nothing
5) Disable/Enable fields plugins -> nothing

When we open an old ticket (created before the update)with extra fields they appear on the page then when will try to create a new ticket the added fields are present in form.
When i close my browser and clear cache, the extra fields are still missing.

---------------------------------

Bonjour,

J'ai le même problème après la mise à jour vers la 9.5.2.
1) Aucune erreur dans le mode débogage
2) Aucune erreur dans les journaux GLPI
3) Régénérer les fichiers conteneurs -> rien
4) Désactiver / Activer le bloc -> rien
5) Désactiver / Activer les plugins de champs -> rien

Lorsque nous ouvrons un ancien ticket (créé avant la mise à jour) avec des champs supplémentaires, ils apparaissent sur la page, ensuite quand essayons de créer un nouveau ticket, les champs ajoutés sont présents sur le formulaire.
Lorsque je ferme mon navigateur et efface le cache, les champs supplémentaires sont manquants.

**Comment by Dodzaxxx** [comment]
Hello,

I have a related issue.

After upgrading GLPI from 9.4 to 9.5.2 and after upgrading fields plugin to 1.11.0 I wasn't able to see my custom fields.
I have uninstalled/installed back the plugin, create new fields again but now the behavior is erratic: when I logged (any users) I can't see the custom field in "create a ticket" and in the template "standard interface" view. But I can in "simplified interface".
Finally, if I l open an old ticket the custom fields are visible and then I if go back to "create a ticket" and in the template "standard interface" the custom field are OK.

Just need to Log Out/In again the user to recreate the issue.

Regards,

**Comment by lucastva** [comment]
> Hello,
> 
> I have a related issue.
> 
> After upgrading GLPI from 9.4 to 9.5.2 and after upgrading fields plugin to 1.11.0 I wasn't able to see my custom fields.
> I have uninstalled/installed back the plugin, create new fields again but now the behavior is erratic: when I logged (any users) I can't see the custom field in "create a ticket" and in the template "standard interface" view. But I can in "simplified interface".
> Finally, if I l open an old ticket the custom fields are visible and then I if go back to "create a ticket" and in the template "standard interface" the custom field are OK.
> 
> Just need to Log Out/In again the user to recreate the issue.
> 
> Regards,

Well observed! Worked for me!

**Comment by CaraNeS** [comment]
Hello,

I have upgrading fields plugin to 1.12.0 and there is no improvement.

Regards,

**Comment by tchapamytek** [comment]
hi
I have the same problem please help me !! 
or is there another plugin that does the same work?

**Comment by lucastva** [comment]
> hi
> I have the same problem please help me !!
> or is there another plugin that does the same work?

Hi! Try to logoff and login, worked for me

**Comment by tchapamytek** [comment]
> > salut 
> > j'ai le même problème s'il vous plaît aidez-moi !! 
> > ou y a-t-il un autre plugin qui fait le même travail?
> 
> Salut! Essayez de vous déconnecter et de vous connecter, cela a fonctionné pour moi

YES BUT NOT STABLE WE DON4T TRAVEL WITH THIS SITUATION

**Comment by CaraNeS** [comment]
Hello,

Work with vers 1.12.1 👍 

@github-actions github-actions released this 21 days ago

Compatible with GLPI 9.5.

Changelog
Fixed: Extra fields not displayed on ticket creation form (#425).
