### ISSUE TITLE
"Undefined index: default_value" in bulk update actions for text fields (check missing in /inc/fields.class.php  #670 in v. 1.12)

### ISSUE THREAD

**Issue by Mirkk** [pluginsGLPI/fields#418]
Hi all,
since (at least) GLPI 9.4  an "Undefined index: default_value" appears in bulk update actions for text fields (without debug mode, the editable field does simply not appear)

The error appears in /inc/fields.class.php #681 in GLPI9.5 with Fields v. 1.11,
and in #670 in Fields v.1.12.

Solution: check for validity of the field by adding isset($field['default_value']) 
/inc/fields.class.php  #670 in Fields v.1.12:
if ($value === "" && isset($field['default_value']) && $field['default_value'] !== "") {

Thank you
Mirko

**Comment by cedric-anne** [comment]
Fixed in #448 .
