### ISSUE TITLE
bug avec droit "delete" sur l'asset

### ISSUE THREAD

**Issue by LucasLEL** [pluginsGLPI/fields#42]
Bonjour, 

Petit bug, testé sur les périphériques, je pense que le reste c'est pareil mais pas vérifié : 

Lorsque le droit "delete" sur les periphériques est actif ; organisation de la page : 
- Champs GLPI de base
- Champs ajoutés par le plugin
- Bouton de sauvegarde / de mise à la corbeille

Lorsque le droit "delete" sur les periphériques est inactif ; organisation de la page : 

- Champs ajoutés par le plugin
- Champs GLPI de base
- Bouton de sauvegarde

Pour résumer : si le droit de "delete" est actif, les champs GLPI sont en tete de page (ce qui est normal), et quand ce n'est pas le cas , les champs du plugin sont en tête .... pas pratique !

**Comment by orthagh** [comment]
Merci pour votre retour, c'est corrigé avec le commit c072d53
