### ISSUE TITLE
FIELDS 1.12 ERROR  include_once

### ISSUE THREAD

**Issue by KOkillin** [pluginsGLPI/fields#422]
![image](https://user-images.githubusercontent.com/56874833/102679171-6c9fb480-41f9-11eb-9684-fce0c566458a.png)

Warning: include_once(C:/laragon/www/glpi/plugins/fields/vendor/autoload.php): failed to open stream: No such file or directory in C:\laragon\www\glpi\plugins\fields\setup.php on line 81  Warning: include_once(): Failed opening 'C:/laragon/www/glpi/plugins/fields/vendor/autoload.php' for inclusion (include_path='.;C:/laragon/etc/php/pear') in C:\laragon\www\glpi\plugins\fields\setup.php on line 81

I try not to die(  i can't do my homework? help me pls

P.S. If it answer is really dumb, don't bullinng me. I don't learned PHP, my knowledge is tiny.

**Comment by Giudy** [comment]
Confirmed this warning using 1.12 and 9.5.3
I guess that the autoload library should be the one in the inc directory

**Comment by trasher** [comment]
You have to use the .tar.bz2 file provided on the release page; or rely on marketplace.
