### ISSUE TITLE
PHP Warning after installing 1.12.2

### ISSUE THREAD

**Issue by hgpit** [pluginsGLPI/fields#432]
Just upgraded Additional Fields plugin from 1.12.0 to 1.12.2 on GLPI v9.5.2, and now we get this following PHP warning:

![image](https://user-images.githubusercontent.com/16598973/110141809-6c14c400-7dcd-11eb-9a0a-5906b5884aec.png)

Any tips to fix?

**Comment by eduardomozart** [comment]
I'm also receiving this issue into GLPI 9.5.4 and PHP 7.3.

**Comment by hgpit** [comment]
Thanks for fixing :)
