### ISSUE TITLE
PHP warning for user after installing Fields

### ISSUE THREAD

**Issue by CorneelSoete** [pluginsGLPI/fields#435]
The following strange errors/warnings can be seen with only one of the users after installing the newest version of fields today.
It works perfectly for all other users.

![Screenshot from 2021-03-23 10-16-04](https://user-images.githubusercontent.com/38813739/112126254-8f5cb300-8bc4-11eb-87a9-adb3f353f82d.png)

**Comment by CorneelSoete** [comment]
After looking at it again I saw that he had debug mode enabled on his account so that's why he had all the errors and we didn't.

**Comment by cedric-anne** [comment]
Fixed by #224 .
