### ISSUE TITLE
Url type in fields like weburl

### ISSUE THREAD

**Issue by paologri** [pluginsGLPI/fields#438]
Good morning,
in the field I select the type 'url'.
Then I select the field to display in a list (for example printers).
The text is displayed instead of the link (see images).
(I think it's not a issue but a request)

![image](https://user-images.githubusercontent.com/21007398/115142064-f93f6f80-a03f-11eb-964e-da0017433588.png)

![image](https://user-images.githubusercontent.com/21007398/115142222-e9745b00-a040-11eb-8e10-08289d2fb94f.png)

![image](https://user-images.githubusercontent.com/21007398/115143018-1f1b4300-a045-11eb-83ec-9ad6c2b99b3c.png)

In:
fields\inc\container.class.php
I have add a case 'url'

![image](https://user-images.githubusercontent.com/21007398/115142609-06119280-a043-11eb-928e-aaabbd653170.png)

the change is the same for both version 9.4 and 9.5

**Comment by cedric-anne** [comment]
This change has already been made in 1.12.4.
