### ISSUE TITLE
Uncaught Error | method Plugin::getPhpDir() | GLPI 9.3.3 + Fields 1.12.7

### ISSUE THREAD

**Issue by TheMrLion** [pluginsGLPI/fields#454]
Hello everyone,

GLPI 9.3.3
Apache 2.4.6
PHP 7.2.22
MariaDB 10.2.11
CentOS 7.6.1810

I have the following issue - actions below:

1. Fields plugin downloaded: [1.12.7](https://github.com/pluginsGLPI/fields/releases/tag/1.12.7)
2. Transfered to GLPI server (/var/www/glpi933/plugins)
3. chmod 775 fields/ -R
4. chown apache:apache fields/ -R
5. GLPI web page's getting Error 500 (no logout=plugins page is blank | logout=Error 500 or blank page)
6. Checked the log (tail -f /var/log/httpd/error_log)

**PHP Fatal error:  Uncaught Error: Call to undefined method Plugin::getPhpDir() in /var/www/glpi933/plugins/fields/setup.php:37\nStack trace:\n#0 
/var/www/glpi933/inc/plugin.class.php(257): include_once()\n#1 
/var/www/glpi933/inc/plugin.class.php(113): Plugin->checkStates()\n#2 
/var/www/glpi933/inc/includes.php(109): Plugin->init()\n#3 
/var/www/glpi933/index.php(57): include('/var/www/glpi93...')\n#4 {​​​​​​​main}​​​​​​​\n  thrown in /var/www/glpi933/plugins/fields/setup.php on line 37**
 
Also tried this [fix](https://github.com/glpi-project/glpi/pull/5413/files), no success.

Can you guys help me?

Best regards.

**Comment by cedric-anne** [comment]
Hi,

1.12.x versions of plugin are only compatible with GLPI 9.5.x.

Regards
