### ISSUE TITLE
Os campos nao aparecem para usuarios Self -Service na visualização simplificada

### ISSUE THREAD

**Issue by bfmribeiro** [pluginsGLPI/fields#458]
Estou utilizando a versão GLPI 9.4.6 e Fields 1.10.3, o campo aparece na versao padrao normalmente para todos os usuarios e na versao simplificada nao aparece os campos para os usuarios SelfService, por favor me ajudem.

**Comment by ccaires** [comment]
Sim, estou usando a versão 9.4.2 e não mostra para interface simplificada. Conseguiu resolver esse problema?
