### ISSUE TITLE
Can't delete Computer object because of missing class

### ISSUE THREAD

**Issue by magicbret** [pluginsGLPI/fields#468]
Hi,

I have installed fields plugin in v1.12.6 and configured some fields (4) for computers. But i am unable to delete any object now that are in the recycle bin and get this error :

`Uncaught Exception Error: Class 'PluginFieldsComputerairbus' not found in /usr/share/nginx/html/glpi/plugins/fields/inc/container.class.php at line 574`

I have several entities, and my fields are only applicable to a specific entity. The computers i try to delete are not part of the entity where the fileds are configured.

If i disable the plugin, i am able to delete the computer i want. This is a workaround for the moment but not really practical.

Any help or idea ? Note that i have updated the plugin to v1.12.8 tha still have the problem. I user GLPI v 9.5.5

Thanks

**Comment by Seikosss** [comment]
Hi,
I'm already sorry for my bad english, so i will be brief.

Just found this problem on my instance, and the fact is, your added field can't finish by "s", i know this sound strange but i saw on the DB that all the tables create by "fields" finish "s" so i just thought that maybe it was linked.
Hope this will help.

**Comment by cedric-anne** [comment]
Hi,

Please try to install 1.12.12 version. It may fix the issue.
