### ISSUE TITLE
[GLPI10.0.0-rc2 + fields 1.13.0-rc2]  Read-Only fields are editable

### ISSUE THREAD

**Issue by VladoTTX** [pluginsGLPI/fields#470]
Checked 10.0.0-rc2 with fields 1.13.0-rc2 and issue with read-only fields as reported by @stonebuzz in PR #462 still exists.

I've tested all the field types.

Read Only flag does not work completely on these field types:
- Date
- DateTime

It is possible to save them regardless of "Read Only" setting in field setup.

Issue is also with Users field. If set to RO it is not displayed in container at first but after container saving, it contains value "Myself".

![image](https://user-images.githubusercontent.com/71901245/156720061-9e1d1404-37e5-4e9d-b6e0-425adba79de0.png)

Also if whole container is set as Read Only for given profile some fields are still editable (you are just not able to save them, as "Save" button is not present):
- Text Area
- Date
- DateTime

**Comment by cedric-anne** [comment]
This should be fixed by https://github.com/glpi-project/glpi/pull/11107.
