### ISSUE TITLE
[GLPI10.0.0-rc2 + fields 1.13.0-rc2] Number field type

### ISSUE THREAD

**Issue by VladoTTX** [pluginsGLPI/fields#471]
Field of type Number can't contain floats any more with 1.13.0-rc2.
In GLPI 9.5.x + fields 1.12.9 it was allowed to enter floating point numbers and it was checked properly for validity during container saving.
Now with fields 1.13.0-rc2 it is possible to enter just whole numbers, floating point are not accepted. 
It is possible to use point in the entry, but after clicking Save, error is displayed "Please enter a valid value. Two nearest valid values are .."

This will create quite a compatibility issue, when moving from 9.5 to 10 of GLPI.

**Comment by cedric-anne** [comment]
Fixed by https://github.com/pluginsGLPI/fields/pull/462/commits/30a227f65ee4d1abe4194c9bc5df02962ff546a8.
