### ISSUE TITLE
[GLPI10.0.0-rc3] Container type dom and field_class col-sm-6

### ISSUE THREAD

**Issue by VladoTTX** [pluginsGLPI/fields#482]
Containers of type of "dom" use default field template which sets field class options to col-sm-6. 
This causes that in small amount space by default 2 fields are displayed in the row.
Example:
![image](https://user-images.githubusercontent.com/71901245/160555181-77a6362a-3e2b-41aa-b7ce-14472d506ca4.png)

Probably similar to fields_panel.html.twig also fields.html.twig should have following defined for dom type container (as they are part of panel, or somehow make them inherit those?):
```
{% set field_options = {
   'full_width': true,
   'add_field_class': (is_expanded ? 'col-sm-6' : ''),
} %}
```

Later on when someone expands and collapses the panel it gets corrected as javascripts takes care of removing col-sm-6 but it should work right after the load.

**Comment by VladoTTX** [comment]
Maybe like this:
https://github.com/pluginsGLPI/fields/pull/483

**Comment by VladoTTX** [comment]
Thanks. But looks like 1.13.0-rc5 seems to break the "tab" type of container.
It is formatted as wide column:
![image](https://user-images.githubusercontent.com/71901245/161303413-dc24d2d1-c050-4a83-ac7a-3e329ac8714f.png)

**Comment by cedric-anne** [comment]
Should be fixed in rc6
