### ISSUE TITLE
1.2.10 and 1.2.11 - Custom Fields missing!!

### ISSUE THREAD

**Issue by andrepetinga** [pluginsGLPI/fields#485]
Hello.
Today we updated plugin to 1.2.10 version and the fields are not showing in the tickets!!!!

Just realized there is a new version - 1.2.11, but even with this version, no fields showing up yet.

Reversing to 1.2.9 solved our problem.

**Comment by stephane-chazelas** [comment]
<sup>I think the OP meant 1.12.1{0,1}, not 1.2.1{0,1} above.</sup>

Same here, same work around. We have a custom tab with one custom yes/no field. After upgrading glpi from 9.4.4 to 9.5.7  and the "fields" plugin from 1.10.2 to 1.12.10 on Friday, the tab is still there, but the field is gone. Same after updating to 1.12.11.

Reverting to 1.12.9 also restores the fields.

(possibly related, we can also not add new fields. Submitting the "add field" form leads to a blank page. No error in the apache error.log. Reverting to 1.12.9 fixes that as well.).

**Comment by pocheoleg** [comment]
> Hello. Today we updated plugin to 1.2.10 version and the fields are not showing in the tickets!!!!
> 
> Just realized there is a new version - 1.2.11, but even with this version, no fields showing up yet.
> 
> Reversing to 1.2.9 solved our problem.

Try after the update to use this function in the plugin settings
![Pic1](https://user-images.githubusercontent.com/68099778/161745634-c20bc084-6ebe-422d-be85-1c188bd40a6a.PNG)

**Comment by cedric-anne** [comment]
Hi,

Installling 1.12.12 version should fix this issue. Please confirm.
