### ISSUE TITLE
Uncaught Exception Error

### ISSUE THREAD

**Issue by ricardo98349** [pluginsGLPI/fields#488]
Version of GLPI 9.5
Debian version 10
When I do a bulk delete the screen goes blank and displays the log:

Uncaught Exception Error: Class 'PluginFieldsNetworkEquipmentdispositivoip' not found in /var/www/html/glpi/marketplace/fields/inc/container.class.php at line 610
![%pn_dia_05_mes_04_10](https://user-images.githubusercontent.com/80924754/161755671-f621c5fa-8c1f-4628-a05d-bcfc67e99f05.jpg)

**Comment by btry** [comment]
Hi

Please show the backtrace for this error. You should in your http server logs.

**Comment by ricardo98349** [comment]
The line it mentions is: $fields = new $classname();

**Comment by ricardo98349** [comment]
> 


sorry did not understand

**Comment by btry** [comment]
If you run Apache 2, the logfile you must check is usually /var/log/apache2/errors.log (it depends on your configuration).

When a fatal error ocurs you may find in thizs file a stack of all called functions until the line throwing the exception you got. This is often required to understand the problem and fix it.

**Comment by ricardo98349** [comment]
> If you run Apache 2, the logfile you must check is usually /var/log/apache2/errors.log (it depends on your configuration).
> 
> When a fatal error ocurs you may find in this file a stack of all called functions until the line throwing the exception you got. This is often required to understand the problem and fix it.

[Tue Apr 05 00:00:02.111926 2022] [mpm_prefork:notice] [pid 393] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Tue Apr 05 00:00:02.111991 2022] [core:notice] [pid 393] AH00094: Command line: '/usr/sbin/apache2'
[Tue Apr 05 07:29:59.193298 2022] [php7:notice] [pid 19451] [client 10.2.17.113:51491] PHP Notice:  Undefined variable: fields in /var/www/html/glpi/marketplace/fields/inc/container.class.php on line 237, referer: http://10.2.17.36/glpi/front/marketplace.php
[Tue Apr 05 07:29:59.194435 2022] [php7:warn] [pid 19451] [client 10.2.17.113:51491] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/glpi/marketplace/fields/inc/container.class.php on line 237, referer: http://10.2.17.36/glpi/front/marketplace.php
[Tue Apr 05 07:33:21.160907 2022] [php7:notice] [pid 22198] [client 10.2.17.113:51707] PHP Notice:  Undefined index: status in /var/www/html/glpi/inc/ticket.class.php on line 7044, referer: http://10.2.17.36/glpi/front/ticket.php?is_deleted=1&as_map=0&criteria%5B0%5D%5Blink%5D=AND&criteria%5B0%5D%5Bfield%5D=12&criteria%5B0%5D%5Bsearchtype%5D=equals&criteria%5B0%5D%5Bvalue%5D=notold&itemtype=Ticket&start=0&_glpi_csrf_token=0f8f9e8a8f4b1e845e10b02512a8daf3fc85352ed9ca23e235c44f5617d8263a

**Comment by ricardo98349** [comment]
This is the log information you requested

**Comment by btry** [comment]
it seems that no backtrace has been logged.

**Comment by btry** [comment]
what did you try to delete ?

**Comment by ricardo98349** [comment]
> ‎o que você tentou apagar?‎

but the same error happens when I try to delete printer and phones

**Comment by btry** [comment]
Check if there are containers for  these object types. If not, do you remember if such containers existed in the past ?

**Comment by btry** [comment]
you need to  check if the file for the missing class exists in /var/ww/glpi/files/_plugins/fields/

**Comment by ricardo98349** [comment]
> ‎você precisa verificar se o arquivo para a classe faltante existe em‎

![WinSCP_dia_05_mes_04_12](https://user-images.githubusercontent.com/80924754/161761149-64eb4930-fe5c-4a0a-8b92-0394cea3e833.jpg)

**Comment by ricardo98349** [comment]
> ‎você precisa verificar se o arquivo para a classe faltante existe em‎ /var/ww/glpi/files/_plugins/fields/

sorry but where?

**Comment by ricardo98349** [comment]
![WinSCP_dia_05_mes_04_13](https://user-images.githubusercontent.com/80924754/161761408-2b5aaca0-aff6-400c-acda-fd665de5da42.jpg)

**Comment by btry** [comment]
in /var/ww/html/glpi/files/_plugins/fields/ (i forgot **html** dir in the path, sorry)

**Comment by btry** [comment]
open **inc** subdirectory

**Comment by ricardo98349** [comment]
> open **inc** subdirectory

![WinSCP_dia_05_mes_04_14](https://user-images.githubusercontent.com/80924754/161761591-89765ba4-3077-4348-bec9-8dd74569a70d.jpg)

**Comment by ricardo98349** [comment]
> open **inc** subdirectory

![WinSCP_dia_05_mes_04_15](https://user-images.githubusercontent.com/80924754/161761917-97357619-7a23-47e6-a2d3-bf24499f45b4.jpg)

**Comment by ricardo98349** [comment]
for having used the marketplace fo the way must change

**Comment by ricardo98349** [comment]
![WinSCP_dia_05_mes_04_16](https://user-images.githubusercontent.com/80924754/161762098-c1869b6b-ddf1-469c-9d40-4a875049557d.jpg)

**Comment by btry** [comment]
in /Var/www/html/glpi/files/_plugins/fields/inc : a file for your class is missing. No need to look in plugins or marketplace subdirs.

**Comment by ricardo98349** [comment]
> ‎em /Var/www/html/glpi/files/_plugins/fields/inc : falta um arquivo para sua classe. Não há necessidade de olhar em plugins ou subdirs de mercado.‎

my glpi was not migrated, i installed it from scratch

**Comment by ricardo98349** [comment]
the error happens right in the marketplace path: /var/www/html/glpi/marketplace/fields/inc/container.class.php at line 610

**Comment by btry** [comment]
I think there is a reference to the missing class somewhere in the DB, in a table related to your types impacted by the issue. 

Without backtrace or an access to the Database it is hard to find what happens. You should consider subscribing support to let an expert access your instance and its database.

**Comment by cedric-anne** [comment]
Hi,

It should be fixed by installation of 1.12.12 release. Please confirm.
