### ISSUE TITLE
Conflict between Data Injection and Fields plugin

### ISSUE THREAD

**Issue by SumErgoCogito** [pluginsGLPI/fields#49]
I don't know in which plugin the problem exists, but when creating a new file injection model within the File Injection plugin, no dropdown is visible to select the object type. I turned debug mode on and received the error in the attached image.

![image](https://cloud.githubusercontent.com/assets/20585627/17037245/cad1bdd4-4f44-11e6-9394-03587718c383.png)

Workaround is to disable Fields plugin while creating file injection models, however this makes it impossible to create injection models that utilize custom fields (I think this was possible at some point in the past)!

Using GLPI 0.90.4-1 (latest from Remi Repo), CentOS 7 and the following plugins enabled:
Additional Fields v. 1.2
File Injection 2.4.1
OCS Inventory 1.2.1

**Comment by SumErgoCogito** [comment]
I looked at the latest version of this file (hook.php), and ended up grabbing the section at the very end that handles integration into the datainjection plugin (indicated by the error, line 252). This fixed my problem. I no longer receive the error message and can create new datainjection models.

**Comment by TICgal** [comment]
Thanks

**Comment by aldiop** [comment]
Dear SumErgoCogito

Please can you describe me the steps that you did to fix your problem.

Thanks
