### ISSUE TITLE
Update Plugin from 1.12.4 to 1.14

### ISSUE THREAD

**Issue by barte91** [pluginsGLPI/fields#498]
Hi,

I've tried to update my plugin from 1.12.4 to 1.14.0; I download and extract plugin version 1.14 in >GLPI_ROOT>/plugins but if I go to GLPI Web into plugin I see the old one: 
![immagine](https://user-images.githubusercontent.com/19166634/165709189-3eea8e96-b860-4b84-8cdc-320b3dd7c880.png)

Here my plugins direcotry:
![immagine](https://user-images.githubusercontent.com/19166634/165709367-0c81d21d-b2b3-4445-b0c3-5fa218da94ca.png)

Can anyone help me,please?

**Comment by cedric-anne** [comment]
I guess you extracted it in `plugins/plugins`.

By the way, using the marketplace feature could help you to have up to date plugins.

**Comment by barte91** [comment]
Hi,

I update it via Marketplace and all work fine!! 

Thanks!
