### ISSUE TITLE
Allow tab on user preferences

### ISSUE THREAD

**Issue by wawax** [pluginsGLPI/fields#5]
It would be great to allow adding a tab in user's preferences

**Comment by trasher** [comment]
till not possible actually... Current hooks are not called on user tabs as of GLPI 9.1.2

**Comment by stonebuzz** [comment]
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
