### ISSUE TITLE
Use in templates

### ISSUE THREAD

**Issue by VadimZhe** [pluginsGLPI/fields#51]
Hello!

I tried to use custom fields only for tickets of certain categories. So, I went to templates (.../front/tickettemplate.php) to set up. And I found out that I cannot use my custom fiels in the templates to make them (un)visible, obligatory or assign default values based on the ticket category, as I used to do with standard fields.
Isn't it supported yet? Or I do something wrong?

Thank you!

**Comment by jstival** [comment]
Je suis dans le même cas, je souhaiterai ajouter des champs personnalisés qui seraient visibles uniquement pour certaines catégories (donc utilisable dans les gabarits de tickets).

Exemple : 
Catégorie = Demande / Sous-Catégorie = Demande de nouveau serveur
Dans le gabarit de ticket utilisée pour la sous-catégorie (Demande de nouveau serveur), on aurait les champs : 
- Faut-il une sauvegarde ? Oui/Non
- Faut-il monitorer le serveur ? Oui/Non
- Etc...

Pour une autre sous-catégorie, qui utiliserait un autre gabarit de ticket, on aurait d'autres champs personnalisables...

Difficile a implémenter ?

**Comment by trasher** [comment]
It seems it will not be trivial to do

**Comment by stonebuzz** [comment]
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
