### ISSUE TITLE
Generic Object plugins and Fields

### ISSUE THREAD

**Issue by Wolvverine** [pluginsGLPI/fields#512]
It is not possible to add fields in Asset created with the Generic Object plugin.

Only for some dropdowns: Models, Types, Category.

**Comment by Giudy** [comment]
Hello, 
  I guess the point is that this plugin is not compatible, if I'm not wrong, with Generic object. So If a new object is created in the inventory, it is not possible to customize the fields for that object.

davide

**Comment by tomolimo** [comment]
Hello @Giudy 
I don't understand your issue, as I'm able to do what your proposed:
I've created a new Object type, and I'm able to add "additionnal fileds" to it.
So be kind enough to detail your issue step by step, so that I'll be able to help you.
Thank you,
Regards,
Tomolimo

**Comment by Giudy** [comment]
SOrry Tomolino, you're right I was trying on a 9.5.x version and it wasn't working. on the 10 it is working fine thank you

**Comment by Wolvverine** [comment]
@tomolimo
I am currently personally migrating my installations slowly to 10.0.x.
But I think some people will be happy, of those who won't be able to migrate for a while yet.

**Comment by trasher** [comment]
Hi, we do not plan to maintain any feature for GLPI 9.5; it's officially no longer maintained. Of course, any of you is free to provide any backport patch, but that will stay unofficial and not merged :)

**Comment by Wolvverine** [comment]
THX @tomolimo

**Comment by Giudy** [comment]
Thank you!!! @tomolimo
