### ISSUE TITLE
Issues with ticket groups [GLPI 10.0.0]

### ISSUE THREAD

**Issue by GKurtasov** [pluginsGLPI/fields#517]
Group applications are displayed incorrectly.

![image](https://user-images.githubusercontent.com/95675278/169295866-b126257e-cef2-42de-a5a3-b099920d36a3.png)

[GLPI 10.0.0]

**Comment by cconard96** [comment]
Can you explain the issue a bit more? It doesn't seem like this issue is for this plugin, but for GLPI itself?

**Comment by GKurtasov** [comment]
> Can you explain the issue a bit more? It doesn't seem like this issue is for this plugin, but for GLPI itself?

I'm sorry I messed up this is really a GLPI problem

**Comment by GKurtasov** [comment]
issue can be closed
