### ISSUE TITLE
Blank page after trying add a field,

### ISSUE THREAD

**Issue by gevorg1808** [pluginsGLPI/fields#522]
Dear community, After tryin add field I am redirecting to empty blank page, apache error log is empty, do you have any suggestion?

**Comment by cedric-anne** [comment]
> HAVE GLPI 10.0.0-rc1.

Maybe using a stable release of GLPI would fix the issue.

**Comment by androidofff** [comment]
> > HAVE GLPI 10.0.0-rc1.
> 
> Maybe using a stable release of GLPI would fix the issue.

Yes, Doing upgrade to 10.0.0 solved the problem.
