### ISSUE TITLE
Unable to Add Form Block on Printers

### ISSUE THREAD

**Issue by SumErgoCogito** [pluginsGLPI/fields#53]
I get the error message: "You cannot add several blocs with type 'Insertion in the form' on same object" when I try to create a new form block within the main form of the printer-type object. I do not have any existing custom fields for printers nor do I have any currently existing form blocks that include printer as an asset type. I get the same error when attempting to do this for any other asset types.  I do have main form blocks for Computers, Tickets, Peripheral (Custom Devices), Phone and Contract.

edit: Updated to fields 1.3 and this problem still persists. I'm unable to add any new main form blocks, even for asset types that do not have any custom fields. Here is the message in my /var/log/httpd/error_log:
`[Tue Aug 30 14:46:45.960471 2016] [:error] [pid 31843] [client 10.0.0.152:62204] script '/usr/share/glpi/plugins/fields/ajax/container_itemtypes_dropdown.php' not found or unable to stat, referer: http://glpi.ccso.ds.clackamas.us/plugins/fields/front/container.form.php` 

GLPI: 0.90.5
fields: 0.90-1.3
datainjection: 2.4.1
mydashboard: 1.2.1
ocsinventoryng: 1.2.1

**Comment by SumErgoCogito** [comment]
Found the reference to /ajax/container_itemtypes_dropdown.php in inc/container.class.php line 402. I commented the line out and tried again, but get the same message "You cannot add several blocks with type 'Insertion in the form' on same object". No more httpd error message however.

**Comment by TICgal** [comment]
Same here.
GLPi: 0.90.5
fields: 0.90-1.3
File injection: 2.4.1

Funny I found your 402 reference  inc/container.class.php at 241
Commented out the whole if and message persists.

**Comment by tomolimo** [comment]
Hello,
Could you download the master sources and do a new test?
I believe that #57 is fixing these problems.
Thank you
Regards,
Tomolimo

**Comment by SumErgoCogito** [comment]
I'm getting a 500 error now. Here is the relevant message from /etc/httpd/log/error_log

`[Fri Sep 23 09:26:53.534376 2016] [:error] [pid 2432] [client 10.36.27.152:52132] PHP Fatal error:  Call to undefined function array_column() in /usr/share/glpi/plugins/fields/inc/container.class.php on line 240, referer: http://hostname/plugins/fields/front/container.form.php`

To "update" to the master branch I first disabled the plugin, backed up the current plugins/fields directory, then overwrote the plugins/fields directory with the files from the master branch.

**Comment by SumErgoCogito** [comment]
Sorry, just realized I am still on php 5.4. Let me update that and get back to you.

**Comment by SumErgoCogito** [comment]
Works great! Thanks tomolimo.

**Comment by tomolimo** [comment]
You're welcome
