### ISSUE TITLE
Unable to add new fields to Component Items

### ISSUE THREAD

**Issue by Tellurek** [pluginsGLPI/fields#540]
GLPI 10.0 / plugin 1.15.3
Unable to add new fields to component items forms (i.e. Graphic card item, Hard Drive Item).
It's only possible to add fields to Component types (i.e. Graphic card, Hard Drive).

I need to add fields that are item-specific similar to serial number.

**Comment by cedric-anne** [comment]
Hi,

Can you test #541 ?
Display of fields in form may be improved, but IMHO, it has to be done on GLPI side (replacement of table layout by a flex layout).
