### ISSUE TITLE
Afficher les sous-entités dans le champ

### ISSUE THREAD

**Issue by Julien-degardin** [pluginsGLPI/fields#547]
Bonjour ! 

Je viens d'installer votre plugin et il a l'air très complet !
Cependant lorsque j'essaie de créer un champ pour assigner un client (entité) à un projet, je n'ai comme choix que les entités. Leurs sous-entités ne sont pas affichées.

![image](https://user-images.githubusercontent.com/50171776/175548319-80e27c76-771d-4864-88e2-3fdf7144dc90.png)
![image](https://user-images.githubusercontent.com/50171776/175548367-b1a9bcb5-0066-4ed2-b9e9-a86b3a6f9013.png)

Est-ce une erreur de ma part ou une fonctionnalité non implémentée ? 
Merci !

**Comment by cedric-anne** [comment]
Hi,

#548 should fix your issue.
