### ISSUE TITLE
Bouton "sauvegarder" disparaît si Fields activé

### ISSUE THREAD

**Issue by SI-AURAL** [pluginsGLPI/fields#556]
Bonjour,

GLPI v10.0.2, compte glpi utilisé, fresh install, installation du plugin "fields" depuis le marketplace (pas testé en install standalone).

Lorsque le plugin est activé, le bouton "Sauvegarder" disparaît à certains endroits.

Par exemple:
Dans Administration > Entités > ROOT_ENTITY, onglet "Notifications".

Je précise que le problème ne s'applique pas partout.

**Comment by cedric-anne** [comment]
Hi,

Can you check if there are logs added in `files/_log/php-errors.log` when button disappears ?

**Comment by SI-AURAL** [comment]
Hello,
Sorry I was on vacation.

There is no log when installing or activating the plugin. However, once the plugin is installed and activated, when you go to an entity (root for example) only in the "Advanced information", "Notifications" and "UI Customization" tabs have this problem (see the 3 paragraphs log below).
I did not look elsewhere.

Log from files/_log/php-errors.log

> [2022-07-25 13:50:52] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /srv/glpi/prod/marketplace/fields/inc/field.class.php at line 693
  Backtrace :
  src/Plugin.php:1482                                PluginFieldsField::showForTab()
  src/Entity.php:1675                                Plugin::doHook()
  src/Entity.php:470                                 Entity::showAdvancedOptions()
  src/CommonGLPI.php:670                             Entity::displayTabContentForItem()
  ajax/common.tabs.php:111                           CommonGLPI::displayStandardTab()
  
> [2022-07-25 13:50:55] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /srv/glpi/prod/marketplace/fields/inc/field.class.php at line 693
  Backtrace :
  src/Plugin.php:1482                                PluginFieldsField::showForTab()
  src/Entity.php:2427                                Plugin::doHook()
  src/Entity.php:474                                 Entity::showNotificationOptions()
  src/CommonGLPI.php:670                             Entity::displayTabContentForItem()
  ajax/common.tabs.php:111                           CommonGLPI::displayStandardTab()
  
> [2022-07-25 13:51:14] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /srv/glpi/prod/marketplace/fields/inc/field.class.php at line 693
  Backtrace :
  src/Plugin.php:1482                                PluginFieldsField::showForTab()
  src/Entity.php:2527                                Plugin::doHook()
  src/Entity.php:486                                 Entity::showUiCustomizationOptions()
  src/CommonGLPI.php:670                             Entity::displayTabContentForItem()
  ajax/common.tabs.php:111                           CommonGLPI::displayStandardTab()

**Comment by SI-AURAL** [comment]
HI,

Upgrade plugin to 1.17.1 seems to resolv the problem. Thanks !

**Comment by 3gmgithub** [comment]
I am seeing this problem with version 1.21.21 using GLPI 10.0.18, and suggestions?
