### ISSUE TITLE
PHP Warning: Undefined array key "entities_id"

### ISSUE THREAD

**Issue by VLuisVLT** [pluginsGLPI/fields#560]
When I import an user from my AD an error page shows and when I read the error in the "php-error.log" shows me this:

glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "entities_id" in C:\inetpub\wwwroot\glpi-test\plugins\fields\inc\container.class.php at line 1462
  Backtrace :
  src\Plugin.php:1448                                PluginFieldsContainer::preItem()
  src\CommonDBTM.php:1229                            Plugin::doHook()
  src\AuthLDAP.php:2820                              CommonDBTM->add()
  src\AuthLDAP.php:3143                              AuthLDAP::ldapImportUserByServerId()
  front\user.form.php:210                            AuthLDAP::importUserFromServers()
  
If I desactivate the pluging the error does not shows.

**Comment by cedric-anne** [comment]
Hi,

Can you test #562 ?

**Comment by VLuisVLT** [comment]
It works just fine now. Thanks
