### ISSUE TITLE
Fields and Form Creator

### ISSUE THREAD

**Issue by wc55** [pluginsGLPI/fields#570]
Hi

Can fields be used in conjunction with Form Creator?

I tried to use the new fields created within the forms, but the information is not saved in the ticket description.

**Self-service:**

1 - Access a form that has fields created by fields:

![image](https://user-images.githubusercontent.com/106084399/186440663-6c792ed2-6571-42c7-adaf-8c7bb84701af.png)

![image](https://user-images.githubusercontent.com/106084399/186440822-1a103d1b-4709-4bb0-85f4-e86e7d0d1349.png)

2 - Click on the button to open the ticket:

![image](https://user-images.githubusercontent.com/106084399/186441011-2842ec17-5d33-4f95-989c-0af8c55f68fb.png)

3 - See the ticket:

![image](https://user-images.githubusercontent.com/106084399/186441192-10f252f7-ddda-4582-9585-03b163d81be7.png)

**Super-Admin:**

1 - The information appears in the side bar, but does not appear in the description.

The intention was to hide these fields for the self-service profile, but the information should be in the description
![image](https://user-images.githubusercontent.com/106084399/186441675-061205ca-c5c8-458e-97fc-d0c1de5554f8.png)

2 - Form Answer:

![image](https://user-images.githubusercontent.com/106084399/186442420-bcae927c-0604-4e53-bb06-dece250d8ecd.png)

3 - Target:

![image](https://user-images.githubusercontent.com/106084399/186442772-017f9c80-8ac7-41de-9dce-387996c222e1.png)

++++++++++++++++++++++++++

Is there any way to save the user's choice in the ticket description as well?

**Comment by btry** [comment]
Hi

When Formcreator builds the content from the ##FULLFORM## tag it excludes the questions od type "additional fields". You may update the content of the  target ticket by inserting the tags of the question. Something likd ##question_42## and ##answer_42## where 42 is the ID of the question. Available tags are listed on the bottom of the page.

**Comment by wc55** [comment]
Hi


I will reconfigure and test

**Comment by wc55** [comment]
Hi

Changed target:

![image](https://user-images.githubusercontent.com/106084399/186450195-0913615c-fdd7-41df-968b-ce73f5eaf33a.png)

The Ticket:

![image](https://user-images.githubusercontent.com/106084399/186450353-573ba5d7-5dad-452c-9d78-398c6470b9d8.png)

It worked

Thanks

**Comment by btry** [comment]
Hi

Great, I close this ticket.
