### ISSUE TITLE
Champ "Valeurs par défaut" bloqué sur type texte

### ISSUE THREAD

**Issue by kelenbi** [pluginsGLPI/fields#573]
GLPI 10.0.2
Fields 1.17.2
PHP 7.4

Quand j'ajoute un nouveau champ et que je change le type, le champ "valeurs par défaut" reste bloqué comme si j'étais en "Texte (ligne simple)".
Impossible de choisir un texte par défaut en texte multiligne, en date, oui/non... Seul "objet GLPI" semble fonctionner.
Si je choisis "Liste déroulante (Intitulé)", je n'ai également pas la main pour créer la liste et l'ajout d'un tel champ rend HS l'ensemble du bloc (les autres champs deviennent invisibles).
![image](https://user-images.githubusercontent.com/112713888/188180226-8d6fb50f-9dd4-46b2-9f22-62f22f39ec46.png)

Le problème est apparu avec la mise à jours de GLPI en version 10.0.2 avec le plugin en 1.16. j'ai par la suite mis à jours le plugin en 1.17.2 mais même problème.

**Comment by tomolimo** [comment]
Hello
Please post in English,
Thank you
Regards,
Tomolimo

**Comment by kelenbi** [comment]
Sorry ! Little translation : 
When adding a new field in a bloc, when I change de field type, the "default value" field doesn't change and stay as a "Text (single line)".
If I change the field type to be a date, a yes/no or multiline field, I can't add a default value accordingly to the field type. 
If i chose "title list" (sorry, don't know if it's the correct english name), the whole bloc become broken and other fields of the same bloc become invisible.

The problem began after upgrading GLPI to 10.0.2 with fields 1.16, and the problem is still here with fields 1.17.2

**Comment by kelenbi** [comment]
Solved by #611
