### ISSUE TITLE
Cannot install plugin - "Run composer install --no-dev in the plugin directory"

### ISSUE THREAD

**Issue by RobertAdam995** [pluginsGLPI/fields#589]
Hello,
I cannot install the plugin. I place the plugin in the plugins directory, but when i go in glpi to install the plugin, i receive the message "Run composer install --no-dev in the plugin directory".
I don't have this situation with any other plugin.
Can you please support me with this situation ?
Thank you !
![Screenshot 2022-11-04 151717](https://user-images.githubusercontent.com/117455359/199981741-aca9d3f8-f47c-4a77-8c1a-e71f1916015a.png)

**Comment by stonebuzz** [comment]
Please use the ```tar.bz2``` archive instead of ```source code```
