### ISSUE TITLE
URL field type with a #38 bug!

### ISSUE THREAD

**Issue by holtzmichael** [pluginsGLPI/fields#591]
Hello All!

I created a field with the URL type, and when I put the URL it works, but after leaving the screen and coming back, a #38 simply appears in the middle of the URL and the same break, because it doesn't exist.
Help please ?!

Thanks in advance.

**Comment by holtzmichael** [comment]
> Hello All!
> 
> I created a field with the URL type, and when I put the URL it works, but after leaving the screen and coming back, a #38 simply appears in the middle of the URL and the same break, because it doesn't exist. Help please ?!
> 
> Thanks in advance.

I found that it adds the #38; always after the & in any URL.

**Comment by cedric-anne** [comment]
Will be fixed by #609 .
