### ISSUE TITLE
[9.5.11] add fields error : blocking for update

### ISSUE THREAD

**Issue by falco2001** [pluginsGLPI/fields#594]
Good morning,
I had no mistake in 9.5.9. Fields 1.13.0
It is impossible to add a field I have a blank page. What is blocking is that the added fields are no longer visible
and error: 

`[2022-11-17 10:34:44] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginFieldsContractchampssupplmentaire' not found in /var/www/assistance-dev3/plugins/fields/inc/field.class.php at line 166
  Backtrace :
  inc/commondbtm.class.php:1136                      PluginFieldsField->prepareInputForAdd()
  plugins/fields/front/field.form.php:43             CommonDBTM->add()
`
thanks

**Comment by falco2001** [comment]
Hello,
I specify that I am in 9.5.11 and that users can no longer enter data in the additional fields and even see them .
I have looked at the code and there are calls to the PluginFieldsContract class that does not exist in the folder inc.
Do you have any idea? 
Thank you

**Comment by trasher** [comment]
You certainly miss to retrieve the files directory which contains  specific classes you've created.

Also, 9.5 is no longer maintained; please update to GLPI 10 and feel free to reopen if your problem persists.
