### ISSUE TITLE
Fields and glpi 10.0.5 blank page

### ISSUE THREAD

**Issue by rafacss** [pluginsGLPI/fields#598]
After migrating to glpi 10.0.5. plugin fields version 1.18.2 appears to be a possible bug. On page > configure > fields, all created items are displayed normally.

When viewed in a linked ticket, the page is completely blank, and it is not possible to view or include information.

![image](https://user-images.githubusercontent.com/67194670/203173028-a9cd920d-08d9-4b8a-ba79-a28eaa39b6a4.png)

**Comment by tomolimo** [comment]
Hello @rafacss 
Any error messages in the PHP error logs?
Thank you,
Regards,
Tomolimo

**Comment by rafacss** [comment]
Hi @tomolimo !

I found these errors in the requested file. If you need more information, I'm happy to help!

I'm using fields 1.18.2 and glpi 10.0.5.

currently using the fields: servicecollection and serviceorder (PluginFieldsTicketserviocoleta, PluginFieldsTicketordemservico)

[2022-11-22 08:22:10] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "PluginFieldsTicketserviocoleta" not found in /home/mysite.com/public_html/marketplace/fields/inc/field.class.php at line 880
  Backtrace :
  marketplace/fields/inc/field.class.php:639         PluginFieldsField::prepareHtmlFields()
  marketplace/fields/inc/container.class.php:1039    PluginFieldsField::showForTabContainer()
  src/CommonGLPI.php:689                             PluginFieldsContainer::displayTabContentForItem()
  ajax/common.tabs.php:113                           CommonGLPI::displayStandardTab()
  
[2022-11-22 08:22:13] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "PluginFieldsTicketordemservico" not found in /home/mysite.com/public_html/marketplace/fields/inc/field.class.php at line 880
  Backtrace :
  marketplace/fields/inc/field.class.php:639         PluginFieldsField::prepareHtmlFields()
  marketplace/fields/inc/container.class.php:1039    PluginFieldsField::showForTabContainer()
  src/CommonGLPI.php:689                             PluginFieldsContainer::displayTabContentForItem()
  ajax/common.tabs.php:113                           CommonGLPI::displayStandardTab()

**Comment by rafacss** [comment]
the upgrade process to 10.0.5 went without a hitch. The files from the previous base of files were maintained without any problems. Any recommendations or suggestions for new tests?

> Did you properly restore all contents from `files` directory form the old GLPI into the new one?

**Comment by chri-bra** [comment]
Hi, we are using GLPI version 9.5.9 with Fields 1.13.0. And we also had the problem that after updating from 9.5.9 to 9.5.11 the tabs were not displayed anymore.

Now after I copied the data again as follows, it works.
[migration-script.txt](https://github.com/pluginsGLPI/fields/files/10085186/migration-script.txt)


Thank you for the tip to the folder "files".

**Comment by trasher** [comment]
Either you forget to retrieve some files, or you have permission issues. Fields plugin creates classes in the files directory, yours are missing.
