### ISSUE TITLE
Access restrictions not correctly applied

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/fields#6]
see http://forum.glpi-project.org/viewtopic.php?id=127152

Bonjour,

Je test actuellement le plugin fields (remplaçant de customfields)

Sur les blocs, on peut paramétré qui a accès ou non aux champs personnalisés, en fonction du profil. Mais cela ne semble pas fonctionner.

Lors d'un type "Ajout d'un onglet".

Quand l'on sélectionne Aucun accès pour un profil, on a quand même les droits en lecture dessus.

Lors d'un type " Insertion dans le formulaire (avant le bouton sauvegarder) "

- Lorsque l'on sélectionne Aucun accès ou Lecture, le profil a quand même les droits en écritures.

Cela fait-il la même chose chez vous ? Je suis en GLPI 0.85.5.

**Comment by tomolimo** [comment]
Hello,
Could you re-try with the latest sources?
Thank you

**Comment by trasher** [comment]
Bonjour, 

À tester avec les dernières sources. 

Si le problème persiste, n'hésitez pas à rouvrir ce ticket.
