### ISSUE TITLE
Default values not save in multi selection question

### ISSUE THREAD

**Issue by Sicoval31** [pluginsGLPI/fields#601]
I have many multi select questions.
if i add a default value and save my choice, the default value is erased.
Creating a ticket depend of the value choosen and the default value because it's impossible to have a null value in condition.

---- le créateur du plugin étant français ....
j'ai plusieurs questions qui sont des sélections multiples.
Lorsque je veux avoir une valeur par défaut (incluse dans la liste de choix), cette valeur n'est pas conservée lors de la sauvegarde de la question.
![image](https://user-images.githubusercontent.com/42040529/204515926-474bb8da-3ee8-4d6f-a2b9-e66f782bb101.png)

J'ai besoin de cette valeur (je souhaite mettre "aucun" comme valeur par défaut) pour valider la création (ou pas) d'un ticket cible puisqu'il n'est pas possible d'avoir dans les conditions une interrogation sur une valeur non remplie (champ = NULL ne fonctionne pas, ou champ = [rien] non plus)
![image](https://user-images.githubusercontent.com/42040529/204516085-237c819f-b5ef-4d6d-837c-865c8f1ee3d7.png)

Merci

**Comment by cedric-anne** [comment]
Hi,

This problem seems to be relative to formcreator plugin. Please open an issue on this plugin repository.
