### ISSUE TITLE
update from 1.18 to 1.19 failed

### ISSUE THREAD

**Issue by RathW** [pluginsGLPI/fields#605]
Hello, 
we are currently using glpi 10.0.5 and are very happy with it.
One of the plugins we used so far is the fields plugin.
Unfortunately the update to version 19.1 failed.
Triggering the update via gui just results in little donut, although it now shows the version 1.19
running: 
root@helpdesk:/home# /var/www/glpi/bin/console glpi:plugin:activate fields
results in
Verarbeitung des Plugins "fields"...
Plugin "fields" has to be installed and configured before activation.

trying the install via cli shows various errors.
root@helpdesk:/home# /var/www/glpi/bin/console glpi:plugin:install fields          
User to use:glpi
Verarbeitung des Plugins "fields"...
MySQL tables installation
PHP Warning (2): Undefined array key "multiple" in /var/www/glpi/marketplace/fields/inc/field           .class.php at line 314
PHP Warning:  Undefined array key "multiple" in /var/www/glpi/marketplace/fields/inc/field.cl           ass.php on line 314
PHP Warning (2): Undefined array key "multiple" in /var/www/glpi/marketplace/fields/inc/field           .class.php at line 314
PHP Warning:  Undefined array key "multiple" in /var/www/glpi/marketplace/fields/inc/field.cl           ass.php on line 314
PHP Warning (2): Undefined array key "multiple" in /var/www/glpi/marketplace/fields/inc/field           .class.php at line 314
PHP Warning:  Undefined array key "multiple" in /var/www/glpi/marketplace/fields/inc/field.cl           ass.php on line 314
PHP Warning (2): Undefined array key "plugin_fields" in /var/www/glpi/marketplace/fields/inc/           toolbox.class.php at line 281
PHP Warning:  Undefined array key "plugin_fields" in /var/www/glpi/marketplace/fields/inc/too           lbox.class.php on line 281
PHP Warning (2): foreach() argument must be of type array|object, null given in /var/www/glpi           /marketplace/fields/inc/toolbox.class.php at line 281
PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/glpi/ma           rketplace/fields/inc/toolbox.class.php on line 281
PHP Warning (2): require_once(kritikalittfield (Kopie)dropdown.class.php): Failed to open str           eam: No such file or directory in /var/www/glpi/marketplace/fields/inc/dropdown.class.php at            line 184
PHP Warning:  require_once(kritikalittfield (Kopie)dropdown.class.php): Failed to open stream           : No such file or directory in /var/www/glpi/marketplace/fields/inc/dropdown.class.php on lin           e 184
Uncaught Exception Error: Failed opening required 'kritikalittfield (Kopie)dropdown.class.php           ' (include_path='.:/usr/share/php') in /var/www/glpi/marketplace/fields/inc/dropdown.class.ph           p at line 184

Does anyone have an idea what has happened and/or how to fix it?
Thanks so much in advance!

Wolfgang

**Comment by Aeto-J** [comment]
Hello,
I tried to reproduce the error on my side but without success I must be missing some conditions in order to test the error and find where it comes from, can you send me your table fields without the content please?

Thank you,
Regards,
Aeto-J

**Comment by RathW** [comment]
Hello Aeto-J,
thank you for your fast reply.
Sorry, maybe it got lost in translation, do you mean the structure of the table glpi_plugin_fields_fields?
Here is the create statement.

CREATE TABLE `glpi_plugin_fields_fields` (
  `id` int(10) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `label` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plugin_fields_containers_id` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `ranking` int(11) NOT NULL DEFAULT 0,
  `default_value` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `is_readonly` tinyint(1) NOT NULL DEFAULT 1,
  `mandatory` tinyint(1) NOT NULL DEFAULT 0,
  `allowed_values` mediumtext COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


Yours Wolfgang

**Comment by cedric-anne** [comment]
Hi,

You probably had an issue during migration.

Can you try to execute, from GLPI root directory, the following command: `php bin/console glpi:plugin:install --force --username=glpi --force fields && php bin/console glpi:plugin:activate fields`?

It will force migration to run again, and maybe the same error as initial migration will be triggered, and it would help to investigate.

**Comment by RathW** [comment]
Hello Cedric,
thanks for your message.
I got the following output:
root@helpdesk:/var/www/glpi# php bin/console glpi:plugin:install --force --username=glpi --force fields && php bin/console glpi:plugin:activate fields?
Verarbeitung des Plugins "fields"...
MySQL tables installation
PHP Warning (2): Undefined array key "multiple" in /var/www/glpi/marketplace/fields/inc/field.class.php at line 314
PHP Warning:  Undefined array key "multiple" in /var/www/glpi/marketplace/fields/inc/field.class.php on line 314
PHP Warning (2): Undefined array key "multiple" in /var/www/glpi/marketplace/fields/inc/field.class.php at line 314
PHP Warning:  Undefined array key "multiple" in /var/www/glpi/marketplace/fields/inc/field.class.php on line 314
PHP Warning (2): Undefined array key "multiple" in /var/www/glpi/marketplace/fields/inc/field.class.php at line 314
PHP Warning:  Undefined array key "multiple" in /var/www/glpi/marketplace/fields/inc/field.class.php on line 314
PHP Warning (2): Undefined array key "plugin_fields" in /var/www/glpi/marketplace/fields/inc/toolbox.class.php at line 281
PHP Warning:  Undefined array key "plugin_fields" in /var/www/glpi/marketplace/fields/inc/toolbox.class.php on line 281
PHP Warning (2): foreach() argument must be of type array|object, null given in /var/www/glpi/marketplace/fields/inc/toolbox.class.php at line 281
PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/glpi/marketplace/fields/inc/toolbox.class.php on line 281
PHP Warning (2): require_once(kritikalittfield (Kopie)dropdown.class.php): Failed to open stream: No such file or directory in /var/www/glpi/marketplace/fields/inc/dropdown.class.php at line 184
PHP Warning:  require_once(kritikalittfield (Kopie)dropdown.class.php): Failed to open stream: No such file or directory in /var/www/glpi/marketplace/fields/inc/dropdown.class.php on line 184
Uncaught Exception Error: Failed opening required 'kritikalittfield (Kopie)dropdown.class.php' (include_path='.:/usr/share/php') in /var/www/glpi/marketplace/fields/inc/dropdown.class.php at line 184

I hope it is helpful. 

Yours Wolfgang

**Comment by cedric-anne** [comment]
Could you try the following patch ?

```diff
diff --git a/hook.php b/hook.php
index df6daad..b6f6fbe 100644
--- a/hook.php
+++ b/hook.php
@@ -91,12 +91,11 @@ function plugin_fields_install()
                 if (!call_user_func([$class,'install'], $migration, $version)) {
                     return false;
                 }
+                $migration->executeMigration();
             }
         }
     }
 
-    $migration->executeMigration();
-
     if (!isCommandLine()) {
         echo "</td>";
         echo "</tr>";
```

**Comment by RathW** [comment]
Dear Cedric, 
same result. 
Could it be caused by the entered data?
My colleage just mentioned that there have been some error messages in the past while using very long names for some of the fields items.
There are not so much real data in the system. 
We could  reset and re-enter them, could this be helpful?

Yours Wolfgang

**Comment by RathW** [comment]
no nothing special in there, we just started to use the plugin....
https://cloud.woehlk.com/index.php/s/2ayjkWijiqQC6fR

**Comment by RathW** [comment]
Great! 
Works like a charm!
Thanks so much for your fast help!
