### ISSUE TITLE
Yes/No bug

### ISSUE THREAD

**Issue by 1soproni** [pluginsGLPI/fields#607]
I think there is a bug with Yes/no fields.
Frontend shows "no" instead "N/A" or "-" when it was not filled out yet.
I think the default value should be NULL in the database if yes or no was not set on field creation.

The main problem: you cannot decide if the field was set to no already or is it still untouched.

**Comment by tomolimo** [comment]
Hello @1soproni 
Please see this: https://github.com/pluginsGLPI/fields/issues/606
Thank you,
Regards,
Tomolimo
