### ISSUE TITLE
exposed to 9.1 REST API

### ISSUE THREAD

**Issue by axlroden** [pluginsGLPI/fields#61]
I'm guessing this is not exposed in the 9.1 REST API?

**Comment by ashmonger** [comment]
I have the same question.
I have fields I have created and need to retrieve, but it seems that the REST API doesn't know there are others fields than the originals ones.

**Comment by trasher** [comment]
I'm not sure the API on the core side is actually able to do things like this. Possibility must be added in core first; please ask on the forums/mailing lists and then fill a RFE if needed.

**Comment by orthagh** [comment]
In fact, you could access the additional data in a way.

Let say you add a "test" block on computer class.
You should have a glpi/files/_plugins/field/computertest.class.php
And the api should answer data on apirest.php/PluginFieldsComputertest?session_token=xxx

BTW, I'll think about a way to add additional data directly in Computer call
