### ISSUE TITLE
1.20.0 breaks user search

### ISSUE THREAD

**Issue by t0rb3n** [pluginsGLPI/fields#614]
I updated Fields from 1.13.0 to 1.20.0 and the user search (`/front/user.php`) is broken with following error:
![grafik](https://user-images.githubusercontent.com/28067972/208502230-6bcf585f-bd33-4b9c-b55b-8216cb2436bc.png)

Neither `php_errors.log` nor apache's `error.log` show any error.

I will try to create a minimal working example.
Also please let me know if you need additional logs of some sort.

Thank you!

I did some further research and can confirm that is indeed the update to 1.20. Manually updated Fields (copied the folders into marketplace directory) from 1.13 to 1.19 and everything worked. 
When updating to 1.20 the search is broken again and so is the database. I can't find any command to rollback the update.

**Comment by tomolimo** [comment]
Hello @t0rb3n 
Could you try to regenerate the field container files after the 1.20 upgrade?
![image](https://user-images.githubusercontent.com/7569958/209659877-69f230c8-fc37-425d-b466-73b6d4c1beae.png)


Thank you,
Regards,
Tomolimo

**Comment by t0rb3n** [comment]
Hello @tomolimo,
unfortunately this did not work. The error is still there. 
Some additional information: 
When I go to a user per direct-link (e.g.`../fron/user.form.php?id=2` and turn on the Debug Mode of GLPI following errors are shown:
![grafik](https://user-images.githubusercontent.com/28067972/209790783-cb017921-13a0-4d06-854b-22cc57e4506f.png)
The dropdowns in question do not have any values but I could set them again. 

I assume that during migration some of the dropdowns are not correctly migrated. Reason for that assumption is that for a this additional field there are two more dropdowns that work perfectly fine.

This is a screenshot of the two working dropdowns with the two that don't.
![grafik](https://user-images.githubusercontent.com/28067972/209793223-8eb482f9-d59f-4cd6-90ab-9aab68d08009.png)
When printing the `$found_v` in Line 1054 from `field.class.php` with 
`echo '<pre>'; print_r($found_v); echo '</pre>';`
following output is produced: 

```
Array
(
    [id] => x
    [items_id] =>x
    [itemtype] => User
    [plugin_fields_containers_id] => X
    [plugin_fields_fivethreeverantwortungfielddropdowns_id] => 9
    [plugin_fields_fivethreelevelfielddropdowns_id] => 4
    [plugin_fields_fivethreerollefielddropdowns_id] => 5
    [plugin_fields_businessunitfielddropdowns_id] => 1
   ... (removed for privacy)
)
```

If we compare the PHP Notice missing indices with the ones that are actually in there we can see that they somehow differ: 

```
plugin_fields_fivethreebusinessunitbufielddropdowns_id                  (NOTICE)
plugin_fields_businessunitfielddropdowns_id                             (ACTUAL)
=> Missing the `fivethree` and `bu` at the end of `businessunit`
```

and 
```
plugin_fields_fivethreeverantwortungsbereichfielddropdowns_id           (NOTICE)
plugin_fields_fivethreeverantwortungfielddropdowns_id                   (ACTUAL)
=> missing the `sbereich`
```

**Comment by t0rb3n** [comment]
Quick question, should this command run before or after updating to 1.20(.1)?

**Comment by stonebuzz** [comment]
Just update to latest version 1.20.2 release few minutes ago =)

**Comment by t0rb3n** [comment]
Today we updated from 1.19 to 1.20.5
The issues still persists. I tried to force the migration with the commands from @stonebuzz but the error is still there.

Please let me know what you need in order for us to fix this issue. This is quite serious to us.

**Comment by stonebuzz** [comment]
hi @t0rb3n 
community support is done in best effort.

I can't reproduce your problem with the new version of the plugin (it certainly depends on your data) you should consider taking a subscription.

Best regards

**Comment by t0rb3n** [comment]
I absolutely understand that. 
I will try to create a minimal example. Maybe that can be helpful.

**Comment by stonebuzz** [comment]
Maybe error is different now?

New version fix ```one```, ```two```, ```three``` etc ... occurrences.

Bu other occurrence are missing > ```sbereich``` from your example.

maybe the names may have to be corrected manually

**Comment by t0rb3n** [comment]
> maybe the names may have to be corrected manually

How would I do this? Literally go into the database and manually update their names to the ones that are expected?

**Comment by stonebuzz** [comment]
yes

**Comment by t0rb3n** [comment]
I will give that a try. Thank you very much so far.

**Comment by t0rb3n** [comment]
I gave that a try and it seems to be working for now. Not sure if there are any more columns that are broken but time will tell.

Thank you very much for your help!
