### ISSUE TITLE
entity restriction issue

### ISSUE THREAD

**Issue by VincentLegros** [pluginsGLPI/fields#619]
The entity restriction to display fields seems to not working when a container is set as "dom" and not "tab"

**Comment by tomolimo** [comment]
Helllo @VincentLegros 
Could you give an example (with step by step infos, and screencopies) in order to reproduce this issue?
Thank you,
Regards,
Tomolimo

**Comment by VincentLegros** [comment]
Let's create an entity struccture like:
![image](https://user-images.githubusercontent.com/20357060/211837439-94d2cbd1-04f5-4087-be08-c514bb7593bf.png)

Let's define a field on a container (insert before Save Button)
The container is defined like : 
![image](https://user-images.githubusercontent.com/20357060/211835960-0cfe0255-2e97-47d7-a657-e332f9708f3f.png)
and the field:
![image](https://user-images.githubusercontent.com/20357060/211836156-f20bdefd-14b4-46bd-87fd-2e93b286afa6.png)

So This field should be visible only in the sub entity where the container is defined (
![image](https://user-images.githubusercontent.com/20357060/211836389-ac0bd777-0b7b-45cf-9dc3-0803bf30b811.png)
)
When we are in the Root entity (recursive) this field is visible

**Comment by tomolimo** [comment]
Hello @VincentLegros 
Knowledgebase Items are not entity dependant (there is no entities_id field in the table), but only targets are: so it will not be possible to restrict field block (in the dom) with the KB item entity (as it is not existing).
Thank you,
Regards,
Tomolimo
