### ISSUE TITLE
Fields plugin Issue "Uncaught Exception Error"

### ISSUE THREAD

**Issue by Fredprincegithub** [pluginsGLPI/fields#622]
Hi, 
i have this error , when in try to install the plugin 1.20  and GLPI 10.0.3

root@MYSERVER/var/www/glpi# php bin/console glpi:plugin:install --force --username=ict --force fields && php bin/console glpi:plugin:activate fields                                                                                                                    
Traitement du plugin « fields »...                                                                                                     
Installation des tables MySQL                                                                                                          
Uncaught Exception Error: Class 'PluginFields0gemalto' not found in /var/www/glpi/plugins/fields/inc/container.class.php at line 558 

BR,

**Comment by stonebuzz** [comment]
Hi @Fredprincegithub 

is the corresponding class present in the folder ```glpi/files/_plugins/fields/inc/```

**Comment by humboldtux** [comment]
I have the same kind of error:

```console
Uncaught Exception Error: Class "PluginGenericobjectObject" not found in /var/lib/glpi/_plugins/genericobject/inc/electronique.class.php at line 31
```

In /var/lib/glpi/_plugins/genericobject/inc/electronique.class.php, line 31:

```php
class PluginGenericobjectElectronique extends PluginGenericobjectObject {
```

GLPI 10.0.6
GenericObject plugin 2.14.1
Fields 1.18.2, trying update to 1.20.2

**Comment by philgprobesys** [comment]
Thanks @stonebuzz for your comment, i thnik that the problem is that these files are not presents .The problem is when you upgrade glpi and the plugin, i thik theses files are note re-generate. Is there a command to regenerate this files ?

**Comment by stonebuzz** [comment]
Hi @philgprobesys 
From ```container``` list you can regenerate files.
