### ISSUE TITLE
Issue with saving user groups during creation with 'Fields' plugin

### ISSUE THREAD

**Issue by Hisoka974** [pluginsGLPI/fields#626]
## Issue with saving user groups during creation with 'Fields' plugin

I installed the "fields" plugin and added a drop-down list to the user creation form to select the user's groups at creation.

![image](https://user-images.githubusercontent.com/62468159/215695661-d6e1ac5b-0107-4012-befb-fea3bb04fc8d.png)

My problem is that when I validate the creation of my user, the group I selected is not saved in the database and the user is not attached to any group.

Could someone help me, please?

**Comment by tomolimo** [comment]
Hello @Hisoka974 
If you re-open the newly created user, do you have the "Groupes" field on the main user tab?
Thank you,
Regards,
Tomolimo

**Comment by Hisoka974** [comment]
Hello @tomolimo 
Thx for your answer !


Yes, I can see the "Groupes" field when I reopen the new user and it is pre-filled with the value selected during creation. But when I go to the "Groupes" tab of GLPI there is no assigned group.

![image](https://user-images.githubusercontent.com/62468159/215732600-cffee60e-73d8-4635-8246-c24d95d0b5ce.png)

**Comment by tomolimo** [comment]
Hello @Hisoka974,

You have to understand that a field that is added to a form is not part of the GLPI core objects, but it is an add-on to an existing object, and it is not bound to existing fields of the GLPI core object.
So the behaviours you're mentionning is perfectly normal: you've added a fields to the user form creation and this field IS NOT linked (bound) to the user's groups, but it is a list of groups you wanted to add to this user.

PS: I've in my feature list the developpement of such binding mechanism, but currently it's not yet implemented.

Thank you,
Regards,
Tomolimo

**Comment by Hisoka974** [comment]
@tomolimo 

I understand better how the plugin works. Thank you very much for your answers.

Regards,
Hisoka974
