### ISSUE TITLE
Lost values!

### ISSUE THREAD

**Issue by admintechblog** [pluginsGLPI/fields#634]
Hi,

There is a bug with the fields plugin dropdown lists. (fields version 1.20.0 / glpi version 10.0.6).

How to reproduce:

Select a new value from any "fields plugin" dropdown list (let's call it field A)
Now select a new value for any other dropdown list that is not part of the "fields" plugin.
You will see that the value from field A is now lost (reverts to the old value)
One solution would seem to be saving the value from field A before doing anything else. But this is not evident or natural. When working with the dropdown lists fro the fields plugin, info will be lost.

**Comment by stonebuzz** [comment]
Hi @admintechblog 
can you try this-> https://github.com/pluginsGLPI/fields/pull/630

**Comment by admintechblog** [comment]
> Hi @admintechblog can you try this-> #630

Hi @stonebuzz. Perfect, it worked!

**Comment by stonebuzz** [comment]
Nice =)
