### ISSUE TITLE
PHP Error 

### ISSUE THREAD

**Issue by msizec** [pluginsGLPI/fields#637]
Hi
Here is an error showing since last glpi update and plugin update (glpi 10.0.6 / fields 1.20)

PHP Notice (8): Undefined index: plugin_fields_applicationsimpactefielddropdowns_id in /var/www/glpi/plugins/fields/inc/field.class.php at line 1057

Index is not found in the $found_v variable.
Looking at this variable, I found an index named _plugin_fields_applicationsimpacte**S**fielddropdowns_id_ with a S after 'impacte'
Looking at the sql tables, I found a table named _glpi_plugin_fields_applicationsimpactefielddropdowns_ without a S after 'impacte'
And finally, looking in this sql table, I found a fied and an index named _plugin_fields_applicationsimpacteSfielddropdowns_id_ with a S after 'impacte'

Something went wrong, but I don't know when nor why.
It is possible that someone changed the field name through glpi ui (not in the db).

Now Im looking for a way to correct this

**Comment by msizec** [comment]
this looks like a weird issue
And I don't really know how to address it ...

**Comment by stonebuzz** [comment]
Hi @msizec 

We have encountered the problem twice with our customers without finding a way to reproduce it.

Just rename table to _plugin_fields_applicationsimpacte**S**fielddropdowns_id_

this should be enough to fix your issue.

Best regards

**Comment by msizec** [comment]
Hi stonebuzz,
thanks,
I did rename it but I still have the php error : 
`PHP Notice (8): Undefined index: plugin_fields_applicationsimpactefielddropdowns_id in /var/www/glpi/plugins/fields/inc/field.class.php at line 1057`

also a new error on top of the dropddown : 
`SQL Error "1146": Table 'glpi.glpi_plugin_fields_applicationsimpactefielddropdowns' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_fields_applicationsimpactefielddropdowns`"`

**Comment by stonebuzz** [comment]
can you revert your change (rename table)

Maybe you should consider subscribing to GLPI?

As I was saying we can't reproduce for the moment

access to your GLPI and your data should allow us to solve your problem

**Comment by msizec** [comment]
Hi
I found another table where I change a filed name and now problem is resolved

**Comment by stonebuzz** [comment]
nice =)
