### ISSUE TITLE
After Update to 1.20.2 plugin field d'ont work properly

### ISSUE THREAD

**Issue by DooBio** [pluginsGLPI/fields#642]
**Glpi** : 
- GLPI 10.0.6 (/glpi => /var/www/glpi)
- Current language:fr_FR
- PHP version (8.1.17) is supported.PHP version (8.1.17) is supported.
- Database engine version (10.6.12) is supported.Database engine version (10.6.12) is supported.
**Field** : 
- Version : 1.20.2

Problem: Following the update field no longer works correctly

1. On the Ticket part, creating a new my Field ticket does not register.

When I create a ticket I pass the value to yes
![image](https://user-images.githubusercontent.com/32511461/226287906-5078b853-c05f-4986-afe2-7ab418dc5099.png)
I save and I come back to my ticket
![image](https://user-images.githubusercontent.com/32511461/226288357-ff2c5d83-a3b2-426f-bdc4-7c1e4f39a93f.png)
and the value does not register
![image](https://user-images.githubusercontent.com/32511461/226288454-e371392c-0365-4f09-bd37-0d1686a524df.png)

2. ticket Search filter
when I want to search with my criteria related to my Field I get an error message
![image](https://user-images.githubusercontent.com/32511461/226288774-086833a6-a5bd-4d41-bddf-e5aa63e0c8cc.png)
`Unknown column 'glpi_plugin_fields_ticketastreintes_demandeenpriodedastreintefieldtwo.demandeenpriodedastreintefieldtwo' in 'field list'`

Well, I hope my recap is as complete as possible.

Good luck and thank you

**Comment by stonebuzz** [comment]
@DooBio 

can you retry with this -> https://github.com/pluginsGLPI/fields/pull/643

**Comment by DooBio** [comment]
The [(https://github.com/pluginsGLPI/fields/pull/643)] did not solve my problems

don't hesitate if you want me to do another test

**Comment by stonebuzz** [comment]
can you run this command (at the root of GLPI)

```php bin/console glpi:plugin:install fields -f```

then

```php bin/console glpi:plugin:activate field```

and retry

**Comment by DooBio** [comment]
Perfect thank you very much my two problems are solved 😎

**Comment by stonebuzz** [comment]
:+1:
