### ISSUE TITLE
plugin fields update issue

### ISSUE THREAD

**Issue by Mirkk** [pluginsGLPI/fields#652]
Dear all,

sorry if maybe I'm wrong here with this question/error.
On GLPI 10.0.6 with any tentative of update from any version <= 2.18.2 to any version >= 2.19.0 I get the following error:

> "Uncaught Exception ErrorException: Undefined index: plugin_fields in /usr/share/glpi/plugins/fields/inc/toolbox.class.php at line 287"

This seems not to happen on a completely clean installation, but on different GLPI updated from 9.5.9, and I was not able to break it down to a specific cause. However, I would like to ask if this line #287 
>  foreach ($PLUGIN_HOOKS['plugin_fields'] as $itemtype) {

was intended to be like this. 
The only place, where it is set (to an empty array) is setup.php #91, only if Plugin::isPluginActive('fields'). Thus, it is not set when the plugin is not yet active. Is this intended?

If I comment toolbox.class.php line 287 just during the update, afterwards it seems to be always defined as an empty array and all seems to work.

Merci for any feedback!

**Comment by cedric-anne** [comment]
Hi @Mirkk,

#653 should fix this issue.

Weird thing is that an undefined index should not result in a fatal error. What PHP version are you using?

**Comment by servicepipe** [comment]
It works on 8.1 without fatal errors, I just checked, the only thing in the folder with the plugin is that there is no ./vendor/, because of this, line 84 in setup.php will give an error.

**Comment by Mirkk** [comment]
Thank you!

the same (not urgent) in

 Undefined index: multiple in
/usr/share/glpi/plugins/fields/inc/field.class.php at line 314


&& ($this->fields['multiple'] ?? false)
so it passes also with my php version (7.4.30) & settings (error_reporting
= E_ALL) which I can't change on this server.

Thank you
Mirko

Am Fr., 21. Apr. 2023 um 15:57 Uhr schrieb Cédric Anne <
***@***.***>:
