### ISSUE TITLE
glpi 10.0.7 et fields 1.20.4 Loss of large amount of data: How to ?

### ISSUE THREAD

**Issue by falco2001** [pluginsGLPI/fields#659]
Fields like - DSI contact - and - Commercial contact - lost

How do I do this? 

I just went into production!
I do also : php bin/console plugin:fields:regenerate_files and  php bin/console  plugin:fields:check_database but this fields are empty and others are ok 

can I export the tables from the old prod database and how can I reintegrate them? Is there information in the glpi_configs table?
Thank you

**Comment by falco2001** [comment]
Before
![image](https://github.com/pluginsGLPI/fields/assets/31952346/8fadf0b3-d8fd-4a0d-9f20-57aa29821025)
AFter : 
![image](https://github.com/pluginsGLPI/fields/assets/31952346/02884639-5ed7-4242-a7ed-8d134921c72d)

**Comment by falco2001** [comment]
PHP Warning (2): Undefined array key "plugin_fields_interlocuteurdsifielddropdowns_id" in /var/www/assistance-dev/plugins/fields/inc/field.class.php at line 1056

An idee ? I didn’t know how to recover my data? MErci

**Comment by stonebuzz** [comment]
I @falco2001 

from your screenshot i see 'onetwothree', related to bug fix in last version.

Install latest version, if problem persist just re-run this

php bin/console glpi:plugin:install fields --force

 'onetwothree' should be removed

**Comment by falco2001** [comment]
I see no other solutions than to restore an old version via an sql export and then retract the sql to have the current data but without the bug in the fields in question . Thank you
Is it related to a change of a field name that I made 1 month ago in the fields table and the translation table but in 9.5.6 it worked well and I didn’t have a display bp? Is this the cause of my problem . Because here I am in production and the plug(in fields is disabled!! Thanks to you

**Comment by falco2001** [comment]
Good morning,
I was able to recover data from version n-2 and then recover from the latest production version.
I imported all this in glpi 10.0.7 and latest version of the fields plugin and I now have access to my data! but I have this error: PHP Warning (2): Undefined array key "plugin_fields_interlocuteurdsifielddropdowns_id" in /var/www/assistance-dev/plugins/fields/inc/field.class.php at line 1056
Do you have any idea?
Thank you

`CREATE TABLE `glpi_plugin_fields_contractchampssupplmentaires` (
  `id` int(11) NOT NULL,
  `items_id` int(11) NOT NULL,
  `itemtype` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'Contract',
  `plugin_fields_containers_id` int(11) NOT NULL DEFAULT '2',
  `plugin_fields_interlocuteurtechniquefielddropdowns_id` int(11) NOT NULL DEFAULT '0',
  `datesignaturefield` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dateeffetcontratfield` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `duretotalefield` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fineffetcontratfield` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `traittwozeroonefivefield` int(11) NOT NULL DEFAULT '0',
  `traittwozeroonesixfield` int(11) NOT NULL DEFAULT '0',
  `traittwozeroonesevenfield` int(11) NOT NULL DEFAULT '0',
  `traittwozerooneeightfield` int(11) NOT NULL DEFAULT '0',
  `interlocuteurtechniquefield` int(11) NOT NULL DEFAULT '0',
  `interlocuteurcommercialfield` text COLLATE utf8_unicode_ci,
  `plugin_fields_interlocuteurcommercialfielddropdowns_id` int(11) NOT NULL DEFAULT '0',
  `maildelinterlocuteurcommercialfield` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `traitementfield` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `traittwozerooneninefield` int(11) NOT NULL DEFAULT '0',
  `traittwozerotwozerofield` int(11) NOT NULL DEFAULT '0',
  `traittwozerotwoonefield` int(11) NOT NULL DEFAULT '0',
  `traittwozerotwotwofield` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `glpi_plugin_fields_fields` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `label` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `type` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `plugin_fields_containers_id` int(11) NOT NULL DEFAULT '0',
  `ranking` int(11) NOT NULL DEFAULT '0',
  `default_value` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `is_readonly` tinyint(1) NOT NULL DEFAULT '1',
  `mandatory` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `glpi_plugin_fields_contracttraittwozerotwotwos` (
  `id` int(11) NOT NULL,
  `items_id` int(11) NOT NULL,
  `itemtype` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'Contract',
  `plugin_fields_containers_id` int(11) NOT NULL DEFAULT '4'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

-- Structure de la table `glpi_plugin_fields_interlocuteurcommercialfielddropdowns`
--

CREATE TABLE `glpi_plugin_fields_interlocuteurcommercialfielddropdowns` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `completename` text COLLATE utf8_unicode_ci,
  `comment` text COLLATE utf8_unicode_ci,
  `plugin_fields_interlocuteurcommercialfielddropdowns_id` int(11) DEFAULT NULL,
  `level` int(11) DEFAULT NULL,
  `ancestors_cache` text COLLATE utf8_unicode_ci,
  `sons_cache` text COLLATE utf8_unicode_ci,
  `entities_id` int(11) NOT NULL DEFAULT '0',
  `is_recursive` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Structure de la table `glpi_plugin_fields_interlocuteurtechniquefielddropdowns`
--

CREATE TABLE `glpi_plugin_fields_interlocuteurtechniquefielddropdowns` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `completename` text COLLATE utf8_unicode_ci,
  `comment` text COLLATE utf8_unicode_ci,
  `plugin_fields_interlocuteurtechniquefielddropdowns_id` int(11) DEFAULT NULL,
  `level` int(11) DEFAULT NULL,
  `ancestors_cache` text COLLATE utf8_unicode_ci,
  `sons_cache` text COLLATE utf8_unicode_ci,
  `entities_id` int(11) NOT NULL DEFAULT '0',
  `is_recursive` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `glpi_plugin_fields_labeltranslations` (
  `id` int(11) NOT NULL,
  `plugin_fields_itemtype` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `plugin_fields_items_id` int(11) NOT NULL,
  `language` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `label` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
`
