### ISSUE TITLE
Problem : Incorrect table name 

### ISSUE THREAD

**Issue by VS-VAR** [pluginsGLPI/fields#663]
Hello,

I've a problem with migration plugin glpi 9.5.6 to glpi 10.0.7.
I'm trying to update plugin to 1.20.5 with glpi markeplace and manual installation (php bin/console glpi:plugin:install fields) but i've an error message : 
SQL Error "1103": Incorrect table name 'glpi_plugin_fields_pluginwebapplicationswebapplicationserveurhbergeurs' in query

Logs:
Traitement du plugin « fields »...
Installation des tables MySQL
PHP User Warning (512): Usage of "utf8" charset/collation detected, should be "utf8mb4" in /var/www/glpi/src/DBmysql.php at line 2003
PHP Warning:  Usage of "utf8" charset/collation detected, should be "utf8mb4" in /var/www/glpi/src/DBmysql.php on line 2003
SQL Error "1103": Incorrect table name 'glpi_plugin_fields_pluginwebapplicationswebapplicationserveurhbergeurs' in query "CREATE TABLE IF NOT EXISTS `glpi_plugin_fields_pluginwebapplicationswebapplicationserveurhbergeurs` (                   `id`                               INT(11)      NOT NULL auto_increment,                   `items_id`                         INT(11)      NOT NULL,                   `itemtype`                         VARCHAR(255) DEFAULT 'PluginWebapplicationsWebapplication',                   `plugin_fields_containers_id`      INT(11)      NOT NULL DEFAULT '27',                   PRIMARY KEY                        (`id`),                   UNIQUE INDEX `itemtype_item_container`                      (`itemtype`, `items_id`, `plugin_fields_containers_id`)                ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;"

Can you help me ?

Ty.

OS : Debian 10.13
MariaDB : 10.3.38
GLPI : 10.0.7

**Comment by Cedri49** [comment]
Hello,

I have the same problem.

Thank You.

**Comment by cconard96** [comment]
MySQL and MariaDB both have 64 character limits for table names. `glpi_plugin_fields_pluginwebapplicationswebapplicationserveurhbergeurs` is 70.

**Comment by VS-VAR** [comment]
Hello,

Thank you for your answer.
