### ISSUE TITLE
Email Notification with custom fields

### ISSUE THREAD

**Issue by ibapt53** [pluginsGLPI/fields#67]
Hello, 

Is it possible to create a new tag?
I would like an email notification to the end of a date for a custom field.
For example, I create a field "Maintenance start" and "end of maintenance" and I would be aware of the expiry of that date.

Thank you for your job.

**Comment by xerodan** [comment]
There are any chances we will see custom field tags in notification options? This is such a great plugin and if this could be added its even better.

**Comment by Armin83** [comment]
Maybe this topic is done with #184 ?

**Comment by trasher** [comment]
Indeed, this is part of 1.7.0 :)

**Comment by juveboss** [comment]
Hello Trasher,

Can a field on my ticket interface be integrated into my notification template? So that the user receives by email the title, the description and my fields added thanks to the plugin fields?

I did not find this possibility ..

**Comment by sworlls** [comment]
Hello Guys good afternoon.
Anyone had any lucky by sending emails with custom fields information? I am struggling by trying searching for tags to add to the templates so i can send the information by notification email. 
Anyone could solve this, if so can give me some help on this?
thank you

**Comment by juveboss** [comment]
Hello everybody,

this feature is in the new version of the plugin? for glpi 9.4?

Thank you....
