### ISSUE TITLE
Installation plugin "champs supplémentaires"

### ISSUE THREAD

**Issue by maubursin** [pluginsGLPI/fields#7]
Bonjour,
J'ai installé le nouveau plugin "champs supplémentaires" (merci aux auteurs).
Juste une petite question, en mode debug j'ai les message suivants;
PHP Notice: Undefined index: status in /var/www/glpi/plugins/fields/inc/field.class.php at line 687
PHP Notice: Undefined index: status in /var/www/glpi/plugins/fields/inc/field.class.php at line 688
Dans le fichier glpi/files/_log/php-errors.log
**\* PHP Notice(8): Undefined index: status
  Backtrace :
  plugins/fields/inc/field.class.php:688
  plugins/fields/inc/field.class.php:650             PluginFieldsField::prepareHtmlFields()
  plugins/fields/ajax/load_dom_fields.php:8          PluginFieldsField::AjaxForDomContainer()

Auriez vous une idée sur la nature du problème.
Merci

Michel Aubrsin

**Comment by tomolimo** [comment]
Hello,
Could you re-try with latest version of sources?
thank you
