### ISSUE TITLE
Compatible with glpi 10.0.9

### ISSUE THREAD

**Issue by cemartins70** [pluginsGLPI/fields#708]
Is this latest version compatible with GLPI version 10.0.9?

**Comment by trasher** [comment]
Yes

**Comment by cemartins70** [comment]
Any operating system version prerequisites, database and PHP version?
Because I have already made the plugin available on SO but it does not appear in GLPI\Plugins to be installed.
My configuration is:
Debian 11 OS
GLPI 10.0.9
PHP 7.4.28
Apache/2.4.53
10.5.15-MariaDB
