### ISSUE TITLE
Error 500 since last update

### ISSUE THREAD

**Issue by jsdarges** [pluginsGLPI/fields#709]
Hello,

I was on 1.20, I have upgraded to 1.21.2 and since then, when a ticket use your plugin when we update any properties of the ticket and click on save button, we get an error 500.

I tried also to upgrade to 1.21.3 but same result.

The php error logs:

`[2023-09-14 10:50:57] glpiphplog.WARNING:   *** PHP Warning (2): Undefined variable $updates in C:\inetpub\wwwroot\marketplace\fields\inc\container.class.php at line 1330
  Backtrace :
  marketplace\fields\inc\container.class.php:1195    PluginFieldsContainer::constructHistory()
  marketplace\fields\inc\container.class.php:1595    PluginFieldsContainer->updateFieldsValues()
  src\Plugin.php:1475                                PluginFieldsContainer::preItemUpdate()
  src\CommonDBTM.php:1591                            Plugin::doHook()
  front\ticket.form.php:84                           CommonDBTM->update()
  
[2023-09-14 10:50:57] glpiphplog.WARNING:   *** PHP Warning (2): foreach() argument must be of type array|object, null given in C:\inetpub\wwwroot\marketplace\fields\inc\container.class.php at line 1330
  Backtrace :
  marketplace\fields\inc\container.class.php:1195    PluginFieldsContainer::constructHistory()
  marketplace\fields\inc\container.class.php:1595    PluginFieldsContainer->updateFieldsValues()
  src\Plugin.php:1475                                PluginFieldsContainer::preItemUpdate()
  src\CommonDBTM.php:1591                            Plugin::doHook()
  front\ticket.form.php:84                           CommonDBTM->update()
  
`

Can you have a look please ?

**Comment by cedric-anne** [comment]
Hi,

Could you test #710?

**Comment by jsdarges** [comment]
It works! thanks a lot
