### ISSUE TITLE
REST API Field ID changes on Upgrade from 9.5 to 10.0

### ISSUE THREAD

**Issue by chri-bra** [pluginsGLPI/fields#714]
Hi there

We are using Fields (v 1.13.0) on GLPI 9.5.12. (OS Ubuntu 20.04)
One of our custom fields (e.g. "patching status") has the ID 76668. See screenshot.

![GLPI 9 5](https://github.com/pluginsGLPI/fields/assets/77125749/76080bf3-0dc5-492e-8e50-b5bf9188298e)

We are on the migration from GLPI 9.5 to 10.0.
On a new Server (Ubuntu 22.04) and GLPI 10.0.9 and Fileds 1.20.5, the ID of the custom field "patching status" changes. It changes to 76675. Although we have copied/migrated the database. And therefore, in our opinion, the fields or REST API IDs should not change.

![GLPI 10](https://github.com/pluginsGLPI/fields/assets/77125749/a10ded4d-96bb-4cc2-9fa7-687595317cb8)

Why does the field ID change? Is it possible to configure somewhere that the numbers/IDs of the REST API stay the same?

**Comment by cedric-anne** [comment]
Hi,

Previously, in `fields` plugin, search options IDs were not constant across profiles, and were changing when fields were removed. This was changed in https://github.com/pluginsGLPI/fields/pull/593 , but we were not able to prevent side effects. With this change, search options IDs will always keep the same ID, whatever the profile used, and whatever the changes made on other fields.
