### ISSUE TITLE
Probllème / et \ dans commondropdown.php et commondropdown.form.php

### ISSUE THREAD

**Issue by johannsan** [pluginsGLPI/fields#73]
Bonjour.
Lors de l'ajout d'une liste déroulante, il faut aller dans les intitulés ajouter des éléments à la liste.
J'ai alors une erreur 500 à cause des deux fichiers commondropdown.php et commondropdown.form.php.
Vous comparez realpath($path) et  PLUGINFIELDS_FRONT_PATH)
et les deux valeurs sont 
T:\wamp\www\glpi\files_plugins\fields\front\testfielddropdown.php
T:\wamp\www\glpi/files/_plugins/fields/front

Il n'y a donc pas égalité sous windows entre les / et .

Ces deux phph affichent donc la RuntimeException.

cdt

**Comment by boillatlucas** [comment]
j'ai exactement le même problème, impossible de remplir les données dans la liste déroulante

**Comment by boillatlucas** [comment]
problème résolu 
dans glpi\plugins\fields\front\commondropdown.php les realpath posaient problème 
voici le code modifié.
`<?php

include "../../../inc/includes.php";
$path = PLUGINFIELDS_FRONT_PATH . '/' . $_GET['ddtype'] . '.php';
if (strpos(realpath($path), realpath(PLUGINFIELDS_FRONT_PATH)) === 0) {
    include_once $path;
} else {
    throw new \RuntimeException('Attempt to load unsecure or missing ' . $path .'!');
}
`

**Comment by trasher** [comment]
Will be fixed in the 1.3.2 release.
