### ISSUE TITLE
Can't reinstall Plugin

### ISSUE THREAD

**Issue by MrDick-11** [pluginsGLPI/fields#734]
There was a bug with creating a new field and I'm trying to reinstall this plugin. I could hardly remove it first, but now I can't install it because of this error: Can't create table glpi.glpi_plugin_fields_containers (errno: 184 "Tablespace already exists")
And I can't find this tablespace:
| glpi_plugin_dashboard_map                                |
| glpi_plugin_datainjection_infos                          |
| glpi_plugin_datainjection_mappings                       |
| glpi_plugin_datainjection_modelcsvs                      |
| glpi_plugin_datainjection_models                         |
| glpi_plugin_glpiinventory_agentmodules                   |
| glpi_plugin_glpiinventory_collects                       |
| glpi_plugin_glpiinventory_collects_files                 |
| glpi_plugin_glpiinventory_collects_files_contents        |
| glpi_plugin_glpiinventory_collects_registries            |

**Comment by trasher** [comment]
This issue seems related to your database server, not to the plugin nor glpi itself.
