### ISSUE TITLE
problème liste déroulante

### ISSUE THREAD

**Issue by boillatlucas** [pluginsGLPI/fields#74]
Bonjour,
Je veux rajouter un champs type "liste déroulante", jusque là tout va bien.
En revanche quand je veux remplir cette liste, on me retourne une erreur serveur HTTP 500.
Voici l'extrait du php-errors.log : 
`2016-10-25 14:46:09 [2@SRV-EIE]
  *** PHP Notice(8): Undefined index: ddtype
  Backtrace :
  plugins\fields\front\commondropdown.php:4`

Pas d'erreur SQL et Javascript

---

Hello,
I want to add a field type "drop-list", it is good.
However when I want to complete this list, it returns me an HTTP 500 server error.
Here is the extract from php-errors.log:
`2016-10-25 14:46:09 [2@SRV-EIE]
  *** PHP Notice(8): Undefined index: ddtype
  Backtrace :
  plugins\fields\front\commondropdown.php:4`

No SQL and Javascript error

**Comment by boillatlucas** [comment]
problème résolu 
dans glpi\plugins\fields\front\commondropdown.php les realpath posaient problème 
voici le code modifié.
`<?php

include "../../../inc/includes.php";
$path = PLUGINFIELDS_FRONT_PATH . '/' . $_GET['ddtype'] . '.php';
if (strpos(realpath($path), realpath(PLUGINFIELDS_FRONT_PATH)) === 0) {
    include_once $path;
} else {
    throw new \RuntimeException('Attempt to load unsecure or missing ' . $path .'!');
}
`

**Comment by trasher** [comment]
Will be fixed in the 1.3.2 release.
