### ISSUE TITLE
You cannot add several blocks with type 'Insertion in the form' on same object (Different entity)

### ISSUE THREAD

**Issue by berilslv** [pluginsGLPI/fields#744]
Hello,

Thanks for developing this great plugin, but I'm facing issue:

I'm trying to create another additional field block in dropdown->locations section.
I have already created additional fields in location for Entity A. Now I need additional fields in location section for entity B. But I'm getting error bellow:
 You cannot add several blocks with type 'Insertion in the form' on same object

Is there any workaround how can I create custom additional fields in location section for each entity?

Thanks!
p.s. running on 10.0.10 , ubuntu 22.04

**Comment by CorentinS6** [comment]
same problem here.
Waiting a clean solution, it seems to work with a dirty sql query : set type to "dom" after bloc creation (table : glpi_plugin_fields_containers)

**Comment by stonebuzz** [comment]
The plugin needs to generate PHP files to work

Modifying the values in the database is clearly not a good idea.

it's clearly intended to prevent modification after creation

best regards

**Comment by CorentinS6** [comment]
ok @stonebuzz, but the issue is not solved...

**Comment by stonebuzz** [comment]
To complete my remarks, 
The "fields" plugin is not currently designed to think in terms of entities.

The "Insert before saved button" type can only be applied once per object (I won't go into the technical details, but it's a question of container identifiers).

However, the "Add a tab" type can be used several times.
In this case, you would simply need to add conditions to hide the tabs depending on the entity.

![image](https://github.com/pluginsGLPI/fields/assets/7335054/7051641b-16f6-40a7-9280-1a96a434a871)

Best regards
