### ISSUE TITLE
Misalignment | New field by fields plugin GLPI

### ISSUE THREAD

**Issue by HADOUDA** [pluginsGLPI/fields#745]
I am working on GLPI 10.0.10, and I installed this plugin. However, when I added a field to the ticket form, I noticed a misalignment of the new field. Can you help me??
![aaaaaa](https://github.com/pluginsGLPI/fields/assets/34125392/0541656a-730f-4b86-9745-e7016a13e187)

**Comment by trasher** [comment]
duplicates #713
