### ISSUE TITLE
Unable to Install Fields Plugin after updating to 10.0.11

### ISSUE THREAD

**Issue by PlaneNuts** [pluginsGLPI/fields#748]
Hello, 

I've had the fields plugin installed on previous installations. After updating when trying to install the Fields plugin I get the following message.

`Uncaught Exception Error: Class "PluginFieldsPlugingenericobjectmobiledevicemobilecustom" not found in /var/www/html/glpi/marketplace/fields/inc/container.class.php at line 617`

I do also have the Generic Object plugin installed. I tied uninstalling it, and installing Fields first, but no luck. 

Has anyone else had this or know how to get around this?

Edit: Just to add to this, I deleted the Plugingenericobjectmobiledevicemobilecustom table from the DB, and no longer get the Class Not Found error, however, when hitting install on this plugin from https://glpi.myserver.com/front/plugin.php I just get the following screen

![image](https://github.com/pluginsGLPI/fields/assets/88776392/beb0d349-e684-4683-b04f-b73002f38ca1)

**Comment by stonebuzz** [comment]
Hi

are the files generated by the plugin present in the folder

```/var/www/glpi/files/_plugins/_fields/```

**Comment by PlaneNuts** [comment]
I'd have to take a look.

I ended up downgrading my installation and going back to 10.0.10. I would need to try updating again to see if I come across the same issue. I guess this can be closed out for now since I can't duplicate this again at the moment.
