### ISSUE TITLE
Error adding dropdown list

### ISSUE THREAD

**Issue by 19snk86** [pluginsGLPI/fields#750]
An error occurs when trying to add a dropdown list 

![error](https://github.com/pluginsGLPI/fields/assets/152609614/c63895c2-e9c6-4c54-b030-f16f50a3f047)

What's in this dropdown list?

**Comment by stonebuzz** [comment]
It's not so much the content that's important, the problem reported here is that the name of your field is too long, please shorten it

You should no longer encounter the problem

Best regards

**Comment by 19snk86** [comment]
The problem was in the language in which I named the field.
In English, the length of the characters entered does not matter.
Perhaps you have already fixed this in the updated version 1.21.6
Thank you
