### ISSUE TITLE
Search in multiple value field

### ISSUE THREAD

**Issue by F78-Fli** [pluginsGLPI/fields#752]
Hello,
I am using GLPI 10.0.6 et Fields 1.20.5
I defined several additional fields (with several different types: text, date, dropdown,..) including 2 multiple dropdown fields.
Search works fine except for these multiple dropdown fields.
When I want to find an article based on the content of a "multiple valued" field with rule "contains", the search engine never brings anything.
And search with rule "does not contains" brings every thing, whatever string value I put in search rule.
Same behaviour for both multiple dropdown fields that I have. 

PS: I cannot test with Fields 1.21.6 as there is an issue in "Hiding block" capability (that I need) but I have not seen anything about "multiple dropdown fields search" in all the following releases (from 1.20.6 to last one).

**Comment by Jarzamendia** [comment]
I'm going through the same problem. I created a field with a dropdown with multiple values ​​to be chosen and I can't search.

**Comment by stonebuzz** [comment]
Hi @F78-Fli , @Jarzamendia 

can you try with this -> https://github.com/pluginsGLPI/fields/pull/754

**Comment by stonebuzz** [comment]
Fixed from latest version
