### ISSUE TITLE
Values from the additional fields disappear when the ticket is being updated

### ISSUE THREAD

**Issue by Ratherius** [pluginsGLPI/fields#753]
Hello!
Let me share the following issue:
I have some additional fields that had been set up with the plugin. When a user creates a ticket, he fills in all these fields and saves the ticket. Everything is ok. But after the update of the page some of these fields become empty.

Is there any way to fix the situation? Thank you in advance.

**Comment by stonebuzz** [comment]
Hi 

can you retry with latest version (GLPI and Plugin)

Bestr egards
