### ISSUE TITLE
New type of field : signature

### ISSUE THREAD

**Issue by yodaa59** [pluginsGLPI/fields#755]
Hello,

Is it possible to add a signature field type?

This one are perfect : https://codepen.io/rongxike/pen/MJMopq

Thanks a lot

**Comment by stonebuzz** [comment]
Hi 

It is related to a new feature, please open a topic to discuss with community about this enhancement on [suggestion website](https://glpi.userecho.com/).

You may also consider taking a [subscription](https://glpi-project.org/subscriptions/) to get professionnal support or [contact GLPI editor team](https://portal.glpi-network.com/contact-us) directly.

You can also offer this feature as a ```pull request```
