### ISSUE TITLE
After Update Field plugin Bloc associated elements disappear

### ISSUE THREAD

**Issue by sdiwakar123** [pluginsGLPI/fields#757]
After Update Field plugin Bloc associated elements disappear.
Update to 1.21.6.
all data and tabs are missing in my old tickets in GLPI.

**Comment by berilslv** [comment]
Hi,
Im having similar issue regarding additional field.
Flow:
Upgraded 10.0.10 to 10.0.11 and I couldn't see additional fields.
After trying upgrading plugin to 1.21.6 im getting cought by error:
`Uncaught Exception Error: Class "PluginFieldsPlugingenericobjectetrelriepatabbriepa" not found in /var/www/html/glpi/plugins/fields/inc/container.class.php at line 617`
This plugin is really important in our env. as it cointains very much information.
Can we hope for fix in nearest future?

**Comment by stonebuzz** [comment]
Hi 

all files generated by the plugin are located in 

```/my_glpi/files/_plugins/fields/```

Are they there?

**Comment by Luck1010** [comment]
> Após a atualização do plugin de campo, os elementos associados ao bloco desaparecem. Atualize para 1.21.6. todos os dados e guias estão faltando em meus tickets antigos no GLPI.



> After Update Field plugin Bloc associated elements disappear. Update to 1.21.6. all data and tabs are missing in my old tickets in GLPI.

In this version 1.21.6 when I open the ticket using the additional fields, I will be able to see the field in the ticket in the technical view (after the ticket is opened)?
