### ISSUE TITLE
1.21.7 version : PHP Warning (2): Undefined array key "itemtype" in fields/inc/container.class.php at line 1444

### ISSUE THREAD

**Issue by DamienGombaultRecia** [pluginsGLPI/fields#764]
Hi.

We have updated the field plugin to version 1.21.7 on our GLPI instance.
We cannot save objects with custom fields anymore.

We get this error :
```
PHP Warning (2): Undefined array key "itemtype" in /mnt/diskhome/home/osu7snko7a9h/dbn41swHoff/htdocs/marketplace/fields/inc/container.class.php at line 1444
Uncaught Exception Error: Class name must be a valid object or a string in /mnt/diskhome/home/osu7snko7a9h/dbn41swHoff/htdocs/marketplace/fields/inc/container.class.php at line 1444
```

The involved code was modified yesterday :
https://github.com/pluginsGLPI/fields/commit/3453f4f85cd12f939015c335c3f974196243f439
It may have introduce a regression.

Thank you.

**Comment by stonebuzz** [comment]
Hi @DamienGombaultRecia 

Can you contact us on support, I'm going to apply this patch

https://github.com/pluginsGLPI/fields/pull/765

**Comment by merlin-tc** [comment]
Got hit by the same bug and now we can't create new tickets. How long does it take until the fixed version shows up in the market place or should I replace it with git version until it's uploaded?

**Comment by stonebuzz** [comment]
@merlin-tc 

can you try this to confirm the fix

https://github.com/pluginsGLPI/fields/pull/765

**Comment by DamienGombaultRecia** [comment]
@stonebuzz I cannot contact Teclib and create ticket on support.
Our GLPI instance is directly managed by Teclib on the GLPI Network Cloud SAAS.

**Comment by stonebuzz** [comment]
@DamienGombaultRecia 

contact me in private

**Comment by merlin-tc** [comment]
> @merlin-tc
> 
> can you try this to confirm the fix
> 
> #765

@stonebuzz I checked out the branch to the plugins directory of our GLPI installation and it seems to be fixed. I could successfully create a new ticket.

**Comment by stonebuzz** [comment]
The release should arrive shortly
