### ISSUE TITLE
Field in main form hides inventory information

### ISSUE THREAD

**Issue by peterVoisin** [pluginsGLPI/fields#770]
Hi,
Fields v1.21.8 makes it bug glpiiventory

This is not the first time that Fileds has bugged the display of "Inventory information" in Assets>Computers and in Computer view.

Disabling Fields allow to display Inventory information again.

**Comment by stonebuzz** [comment]
Hi @peterVoisin 
maybe some screenshots could help us "understand" and solve the problem

**Comment by peterVoisin** [comment]
Thanks for your reply @stonebuzz 
no problem with fields 1.21.7 as in this screenshot, the red zone isn't displayed in 1.21.8

![fields-bug](https://github.com/pluginsGLPI/fields/assets/24912561/aa8e7932-c950-47db-9c73-aa0d51bb7be6)

**Comment by trasher** [comment]
I cannot reproduce. It's probably due to either fields definition, or data... Did you try to regenerate?

We need a way to reproduce from a fresh install in order to investigate.

**Comment by trasher** [comment]
(I've edited the title: inventory information are provided from GLPI core since GLPI 10, not from inventory plugin)

**Comment by Kuba-Pawlak** [comment]
But seems like plugin made a changes in code generated by PHP. If I switch off "fields" plugin then whole section is visible again.

**Comment by stonebuzz** [comment]
no problem on my side (same version of fields and latest version of GLPI)

![image](https://github.com/pluginsGLPI/fields/assets/7335054/22ad2b71-ad30-4bed-97bd-b598c7142ebc)

Can you show us the fields in the fields container?

**Comment by trasher** [comment]
No feedback from reporter; I close.
