### ISSUE TITLE
Falha ao aparecer o campo addicional fields depois da abertura do chamado

### ISSUE THREAD

**Issue by Luck1010** [pluginsGLPI/fields#774]
Prezados, tudo bem?

Ao acrescentar o campo addicional fields no formulário (dentro do plugin formcreator) o mesmo é criado porém depois de criado o campo addicional fields não aparece no perfil técnico conforme consta em print anexo:

![Capturar](https://github.com/pluginsGLPI/fields/assets/40967265/4c877833-b5d2-4188-9939-e34f7d860ee1)

![Capturar1](https://github.com/pluginsGLPI/fields/assets/40967265/5b08be01-3e5e-4857-b53e-5ad07d076a17)

**Comment by stonebuzz** [comment]
Please write in english

**Comment by Luck1010** [comment]
Dear all, how are you?

When requiring additional fields on the form (within the formcreator plugin) it is created, but after creating the additional fields it does not appear in the technical profile as shown in the attached print:



![Capturar](https://github.com/pluginsGLPI/fields/assets/40967265/02274c05-bac4-4254-b0af-550c86d6653d)
![Capturar1](https://github.com/pluginsGLPI/fields/assets/40967265/19e8cda1-9778-4abf-9e2a-befd2be001cd)

**Comment by trasher** [comment]
Seems related to formcreator plugin; please open issue on its repository.
