### ISSUE TITLE
1.3.1 - mandatory field always complain

### ISSUE THREAD

**Issue by mathieuchateau** [pluginsGLPI/fields#78]
Hello,

with 1.3.1:
1. Add a new field (text, dropdown, user..) in Tab/block. Make it mandatory.
2. Go to asset, fill the field. Save. value stays ok.
3. Go to main tab (computer for example). Make a change. Click save.
4. Alert popup complains field created before is mandatory and block update.

**Comment by trasher** [comment]
Will be fixed in the 1.3.2 release.
