### ISSUE TITLE
adding conditionned fields

### ISSUE THREAD

**Issue by touilmohammed** [pluginsGLPI/fields#785]
i need to add conditions on fields dependent on some other fields on the same block.
To be more specific, if the category of my ticket is X i need some fields to be shown and if it s Y others must be shown ;
Or even as an alternative if a field that i create for exemple has A as a response  i need some fields to be shown and if it s B others must be shown ;
If anyone can help;

**Comment by chloegeof** [comment]
Hi, I've the same request as @touilmohammed 
Is the feature under development?

**Comment by stonebuzz** [comment]
Hi 

Currently, only a single block can be displayed or hidden based on a condition. 
There is no functionality to conditionally display or hide a field within a block. 

To work around this limitation, you can create multiple blocks with different fields, displayed according to your conditions.

This feature is not currently planned for inclusion in the roadmap. 

Best regards
