### ISSUE TITLE
Impossible to access to fields dropdown

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/fields#80]
Hello

We would like to add a dropdown but we can't access to all dropdown from fields

![image](https://cloud.githubusercontent.com/assets/15144026/20220343/6e2ced14-a82d-11e6-9824-63bd77f11d88.png)

**Comment by btry** [comment]
Hi

Error 500 ? then have a look to your HTTP server's logs. You should find a backtrace to show here.

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/20220779/2336fe10-a82f-11e6-89d1-504e0646d11a.png)
![image](https://cloud.githubusercontent.com/assets/15144026/20220794/312863d8-a82f-11e6-84a5-2451b2ef6329.png)

**Comment by satyan01** [comment]
I have restarted the iis server and it is same result

**Comment by satyan01** [comment]
and only on fields dropdown pages

**Comment by btry** [comment]
this is an IIS server ?

I don't know enough these servers to tell you where to get the backtrace of the error.

What you provided seems close to the access.log Apache maintains.

Do you have something equivalent to errors.log ?

**Comment by trasher** [comment]
As far as I know, there is a separate log for PHP on those installations; but I can't say more, since it can be installed... anywhere.

**Comment by satyan01** [comment]
I found that :+1:

**Comment by satyan01** [comment]
[15-Nov-2016 09:47:03 Europe/Berlin] PHP Fatal error:  Uncaught RuntimeException: Attempt to load unsecure or missing C:\inetpub\wwwroot\glpi/files/_plugins/fields/front/consequencesfielddropdown.php! in C:\inetpub\wwwroot\glpi\plugins\fields\front\commondropdown.php:8
Stack trace:
#0 {main}
  thrown in C:\inetpub\wwwroot\glpi\plugins\fields\front\commondropdown.php on line 8

**Comment by trasher** [comment]
Are you working from a fresh install or is it an update?

If you've updated, could you tell if the generated files were present in the plugin directory itself before you upgrade?

**Comment by satyan01** [comment]
yes fresh upgrade of glpi 01/11/2016
Additionnal fields	1.3.1

during migration I have empty the plugin folder and added last version of all plugins

**Comment by trasher** [comment]
So that is the issue I guess... Plugin uses to write generated files in its own directory, which is not a good idea; I've changed that.

Generated files must be migrated to the new dir (`glpi/files/_plugins/fields`), the update process take care of that... But if original files did not exists; it can't do anything...

You'll have to copy all files from your old plugin directory located into `inc` and`front` excepted plugin files (refer to the new directory to identify those ones). Once done, it should work again.

An alternative would be to restore the full old plugin directory, along with its database tables, and run again the update process.

**Comment by satyan01** [comment]
inc and front are already in  (glpi/files/_plugins/fields) I have copied inc and front from glpi/plugins/fields but anything has changed

**Comment by satyan01** [comment]
It was fixed thx.

Just a question : I would like to limit to add a new line in the dropdown to some profiles, It is possible ?

**Comment by trasher** [comment]
I do not know but I don't think so.
