### ISSUE TITLE
Issue with updating Fields plugin on GLPI 10

### ISSUE THREAD

**Issue by kvnwszr** [pluginsGLPI/fields#806]
I'm facing an issue while updating the "Fields" plugin on GLPI 10. After attempting the update via the plugin management interface, the process does not complete successfully. The following errors are logged in the php-errors.log file:

```
[2024-07-02 14:46:44] glpiphplog.CRITICAL: *** Uncaught Exception Error: Class "PluginFields0caseacocher" not found in /var/www/html/glpi/marketplace/fields/inc/container.class.php at line 643
Backtrace :
marketplace/fields/inc/container.class.php:355 PluginFieldsContainer::create()
marketplace/fields/hook.php:86 PluginFieldsContainer::installUserData()
src/Plugin.php:922 plugin_fields_install()
: Plugin->install()
src/Marketplace/Controller.php:546 call_user_func()
src/Marketplace/Controller.php:436 Glpi\Marketplace\Controller->setPluginState()
ajax/marketplace.php:83 Glpi\Marketplace\Controller->installPlugin()
public/index.php:82 require()
```

Context:

The class PluginFields0caseacocher is not found when executing the PluginFieldsContainer::create() method.
The create method attempts to generate a class name based on item types and field names, then calls the install() method on this class.
The getClassname method seems to generate incorrect class names or the corresponding classes do not exist.

Actions Taken:

Executed the command composer install --no-dev in the plugin directory to ensure all dependencies are correctly installed.

Relevant Logs:

php-errors.log:
```
[2024-07-02 14:46:44] glpiphplog.CRITICAL: *** Uncaught Exception Error: Class "PluginFields0caseacocher" not found in /var/www/html/glpi/marketplace/fields/inc/container.class.php at line 643
Backtrace :
marketplace/fields/inc/container.class.php:355 PluginFieldsContainer::create()
marketplace/fields/hook.php:86 PluginFieldsContainer::installUserData()
src/Plugin.php:922 plugin_fields_install()
: Plugin->install()
src/Marketplace/Controller.php:546 call_user_func()
src/Marketplace/Controller.php:436 Glpi\Marketplace\Controller->setPluginState()
ajax/marketplace.php:83 Glpi\Marketplace\Controller->installPlugin()
public/index.php:82 require()

```
Request for Assistance:

I seek your assistance in resolving this issue with updating the Fields plugin on GLPI 10. Any information or assistance regarding the correction of the class not found error would be greatly appreciated.

**Comment by kvnwszr** [comment]
Thank you for your response.
The commands are also not working.

```
[root@gloopy glpi]# php bin/console glpi:plugin:install fields -f
User to use:glpi
Traitement du plugin « fields »...
Installation des tables MySQL
Uncaught Exception Error: Class "PluginFields0caseacocher" not found in /var/www/html/glpi/marketplace/fields/inc/container.class.php at line 643
```

**Comment by stonebuzz** [comment]
CAn you check from 

glpi/files/_plugins/fields/inc/ what is the name of the file linked to this class

can you upload the file here ?

**Comment by kvnwszr** [comment]
I have checked all files in glpi/files/_plugins/fields/inc/ and I couldn't find any reference to this class.

**Comment by stonebuzz** [comment]
during GLPI update did you take over the glpi/_files/ folder?

**Comment by kvnwszr** [comment]
No, I did not modify the glpi/_files/ folder during the GLPI update.

**Comment by stonebuzz** [comment]
the plugin fields writes files in the folder glpi/files/_plugins/ which must be included if you update GLPI using this procedure

https://glpi-install.readthedocs.io/fr/latest/update.html

Can you give me the result of the following SQL query?

SELECT * from glpi_plugin_fields_containers

**Comment by kvnwszr** [comment]
I followed this procedure carefully
Here is the result of the query

![Capture d’écran 2024-07-02 162750](https://github.com/pluginsGLPI/fields/assets/160158327/c86dba95-d60f-4532-90d7-7b8ba46379f0)

**Comment by stonebuzz** [comment]
Ok, drop line with ID 14 (itemtypes = ["0"] -> not possible)

```DELETE FROM glpi_plugin_fields_containers WHERE id = 14```

and it should work properly

**Comment by kvnwszr** [comment]
it worked
thanks a lot for your help
