### ISSUE TITLE
Updated to 1.21.10 can no longer map using Data Injection

### ISSUE THREAD

**Issue by soupisawesome** [pluginsGLPI/fields#809]
GLPI v10.0.15
Data Injection v2.13.5
Additional Fields v1.21.10

Since updating Addition Fields to v1.21.10 I can no longer map additional fields in the data injection plug-in model.

It allows me to select the Table made by Additional Fields, but the Field selection disappears.

**Comment by stonebuzz** [comment]
Hi @soupisawesome 

please apply this -> https://github.com/pluginsGLPI/fields/pull/807

(youneed te regenerate file after)

**Comment by stonebuzz** [comment]
Fixed by https://github.com/pluginsGLPI/fields/releases/tag/1.21.11
