### ISSUE TITLE
Version 9.1

### ISSUE THREAD

**Issue by jpclerc** [pluginsGLPI/fields#81]
Bonjour

Je suis en version 9.1 et j'essaie d'utiliser le plugin "field"

Cela marche ... un peu

Je veux un champ obligatoire
Il apparaît bien uniquement dans le formualire standard (ticket)

Si je ne la saisie pas, j'ai un message rouge qui indique qu'uil est manquant et je reste sur le formulaire MAIS, le ticket a été créé !
Ce qui fait que si je renseigne le champ et que je sauvegarde j'ai 2 tickets
D'ailleurs après le message rouge, j'ai le bouton "Ajout" et non "Sauvegarde"

Quand je saisis un ticket depuis le formualire simplifié, le ticket est enregistré et j'ai un message rouge qui m'indique que le champ oligatoire est manquant

Jusqu'à quelle version avez vous utilisé ce plugin ?
Est-il envisageable d'avouir une évolution de celui-ci si le dysfonctionnement ne vient pas de moi ?

Merci
Jean-Paul

**Comment by trasher** [comment]
Hello,

It seems that the issue here is the same than #78.

Closing as duplicate, feel free to reopen if this is not a dup.

**Comment by jpclerc** [comment]
It's seems to be a littile bit the same that means the plug in is not available in 9.1

Is it good in 9.0 ?
Will it be improve soon for 9.1 ?

Thanks

**Comment by tomolimo** [comment]
Hello jpclerc,

I'm using this plugin in 9.1 GLPi version, without any troubles, but not in the same scenario than you.
I've one tab for Tickets, one tab for Entities, and one tab for Computers:
Tickets:
![image](https://cloud.githubusercontent.com/assets/7569958/20422336/0678a220-ad6a-11e6-956f-e64f6e1767d4.png)

Entities:
![image](https://cloud.githubusercontent.com/assets/7569958/20422360/24dc1ab2-ad6a-11e6-9caf-e9b4e89ee04f.png)

Computers:
![image](https://cloud.githubusercontent.com/assets/7569958/20422391/6ab20e70-ad6a-11e6-8391-e4a2e1fc3bc4.png)


So yes it is compatible with 9.1, and yes there are (like any other software) some bugs to be fixed...

regards,
Tomolimo

**Comment by jpclerc** [comment]
Thanks for you reply

Are your added fields mandatory ?

**Comment by trasher** [comment]
Thanks @tomolimo for your feedback :)

@jpclerc a few bugs have been reported against the last release, and yes, we plan to fix them; of course! 

But I can't give any date, it will probably not happen until a few weeks... We'll do our best but we have other priorities for now unfortunately.

**Comment by tomolimo** [comment]
@jpclerc : in fact no as we are using [formvalidation](http://plugins.glpi-project.org/#/plugin/formvalidation) plugin for that, as it is more generic and can validate with formulas instead of only check the `mandatory`, and can validate any fields on any form.
