### ISSUE TITLE
Add a field to generic object

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/fields#83]
Hello

Question : Is it possible to add a field to a generic object ?

Thank you for your answer

**Comment by trasher** [comment]
This duplicates #23

**Comment by satyan01** [comment]
Hello Why it is closed ? Is it possible to add a field to generic object ? if yes how to do it ?

![image](https://cloud.githubusercontent.com/assets/15144026/20663229/016899ee-b557-11e6-9e9d-ec6fb3b6dc85.png)

**Comment by trasher** [comment]
It is closed because this is the same demand as #23
