### ISSUE TITLE
Add custom field to licenses ?

### ISSUE THREAD

**Issue by bzouille** [pluginsGLPI/fields#84]
Hi,

I wanted to add some custom filed to licenses form and i found your plugin, It works fine with many forms but not for licenses (entry not present in  Associated item type)
Is it possible to create a new block with Associated item type : Licenses ?
Can't find licenses in the list why ?

Thanks for your help.
Regards

**Comment by bzouille** [comment]
Hi,
Solved by adding :
 'SoftwareLicense'    => _n("License", "Licenses", 2),
line 568 of container.class.php

Not sure it's the best idea but it works.

Regards,

**Comment by trasher** [comment]
Will be fixed in the 1.3.2 release.
