### ISSUE TITLE
Champs non visibles sur interface simplifiée

### ISSUE THREAD

**Issue by ocs-lsanchez** [pluginsGLPI/fields#85]
Bonjour,

J'ai créé un bloc avec des champs textes associés à l'élément Tickets. Les champs sont bien visibles dans l'interface standard pas dans l'interface simplifiée. Certains champs sont obligatoires et la création d'un ticket via l'interface simplifiée remonte une anomalie champ obligatoire non renseigné.
Une fois le ticket créé, le champ est bien visible dans la gestion du ticket.
Testé en version 0.90.05 et 9.1.1

**Comment by spicot** [comment]
Bonjour,
J'ai exactement le même problème avec GLPI 0.90.5 et le plugin Champs supplémentaires 1.3.1.
Le champ créé en texte simple en suivant la doc du plugin est visible en interface standard mais pas dans l'interface simplifiée.
Merci pour votre aide.

**Comment by trasher** [comment]
This duplicates #19, closing
