### ISSUE TITLE
failed to install 

### ISSUE THREAD

**Issue by hjonathan2019** [pluginsGLPI/fields#850]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### GLPI Version

10.0.16

### Plugin version

latest

### Bug description

when i try to install the plugin i have no error but nothing happens.
![image](https://github.com/user-attachments/assets/0c050492-4e34-4e1f-9971-2c0be5ed0702)

**Comment by stonebuzz** [comment]
Hi @hjonathan2019 

Surprising that you don't have any logs!

Can you look in the GLPI logs (`files/_logs/`) as well as in your Web server logs (perhaps the error is not caught by GLPI, but by the Web server)?

**Comment by fixwhat** [comment]
I had exactly this problem on a dev instalation. The only way to get rid of it was to manually delete all glpi_plugins_fields_*.
Not a big deal to me since it was a dev install. It would be different if it was a production enviroment.

**Comment by trasher** [comment]
Development specific issues are something totally different.

Anyway, no feedback from original reporter; I close.
