### ISSUE TITLE
"Delete permanently" buttons disappeared

### ISSUE THREAD

**Issue by psyrius1** [pluginsGLPI/fields#859]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### GLPI Version

10.0.17

### Plugin version

1.21.15

### Bug description

Since we upgraded to GLPI 10.0.17 the "Delete permanently" button disappeared from the block and field separator. 
![Additional fields - Block](https://github.com/user-attachments/assets/1ec7184a-5a43-4c74-bcbe-65ff65f98e34)
![Field](https://github.com/user-attachments/assets/038fa2c0-57c5-47f5-883f-c25a70b1436b)

### Your GLPI setup information

**Server**
 
Operating system: Linux 5.15.0-125-generic #​135-Ubuntu SMP Fri Sep 27 13:53:58 UTC 2024 x86_64
PHP 8.3.13 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, random, readline, session, shmop, soap, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.37
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi10dev@10.0.51.22:3306/glpi10dev
	Host info: 10.0.51.22 via TCP/IP
	
PHP version (8.3.13) is supported.PHP version (8.3.13) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.37) is supported.Database engine version (8.0.37) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/glpi10dev/files/_cache has been validated. Write access to /var/www/glpi10dev/files/_cron has been validated. Write access to /var/www/glpi10dev/files has been validated. Write access to /var/www/glpi10dev/files/_dumps has been validated. Write access to /var/www/glpi10dev/files/_graphs has been validated. Write access to /var/www/glpi10dev/files/_lock has been validated. Write access to /var/www/glpi10dev/files/_pictures has been validated. Write access to /var/www/glpi10dev/files/_plugins has been validated. Write access to /var/www/glpi10dev/files/_rss has been validated. Write access to /var/www/glpi10dev/files/_sessions has been validated. Write access to /var/www/glpi10dev/files/_tmp has been validated. Write access to /var/www/glpi10dev/files/_uploads has been validated.Write access to /var/www/glpi10dev/files/_cache has been validated.
Write access to /var/www/glpi10dev/files/_cron has been validated.
Write access to /var/www/glpi10dev/files has been validated.
Write access to /var/www/glpi10dev/files/_dumps has been validated.
Write access to /var/www/glpi10dev/files/_graphs has been validated.
Write access to /var/www/glpi10dev/files/_lock has been validated.
Write access to /var/www/glpi10dev/files/_pictures has been validated.
Write access to /var/www/glpi10dev/files/_plugins has been validated.
Write access to /var/www/glpi10dev/files/_rss has been validated.
Write access to /var/www/glpi10dev/files/_sessions has been validated.
Write access to /var/www/glpi10dev/files/_tmp has been validated.
Write access to /var/www/glpi10dev/files/_uploads has been validated.

Web server root directory configuration seems safe.Web server root directory configuration seems safe.
Sessions configuration is secured.Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi10dev/marketplace has been validated.Write access to /var/www/glpi10dev/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

GLPI constants
 
GLPI_ROOT: "/var/www/glpi10dev"
GLPI_CONFIG_DIR: "/var/www/glpi10dev/config"
GLPI_VAR_DIR: "/var/www/glpi10dev/files"
GLPI_MARKETPLACE_DIR: "/var/www/glpi10dev/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/var/www/glpi10dev/files"
GLPI_CACHE_DIR: "/var/www/glpi10dev/files/_cache"
GLPI_CRON_DIR: "/var/www/glpi10dev/files/_cron"
GLPI_DUMP_DIR: "/var/www/glpi10dev/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/glpi10dev/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi10dev/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi10dev/files/_lock"
GLPI_LOG_DIR: "/var/www/glpi10dev/files/_log"
GLPI_PICTURE_DIR: "/var/www/glpi10dev/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi10dev/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi10dev/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi10dev/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi10dev/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi10dev/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi10dev/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi10dev/locales"
GLPI_VERSION: "10.0.17"
GLPI_SCHEMA_VERSION: "10.0.17@bde16719fbd4112f59a9a7d34c66c959bce73434"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

Libraries
 
htmlawed/htmlawed version 1.2.14 in (/var/www/glpi10dev/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi10dev/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi10dev/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.7.5 in (/var/www/glpi10dev/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi10dev/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi10dev/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi10dev/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi10dev/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi10dev/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi10dev/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi10dev/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi10dev/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi10dev/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi10dev/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi10dev/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi10dev/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi10dev/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi10dev/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi10dev/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi10dev/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi10dev/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi10dev/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/glpi10dev/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi10dev/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi10dev/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi10dev/vendor/psr/cache/src)
league/csv in (/var/www/glpi10dev/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi10dev/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi10dev/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi10dev/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi10dev/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi10dev/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi10dev/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi10dev/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi10dev/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi10dev/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi10dev/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi10dev/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi10dev/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi10dev/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi10dev/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi10dev/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi10dev/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

**Comment by cconard96** [comment]
This is a bug in GLPI itself, not the plugin. It will be fixed in GLPI 10.0.18.
https://github.com/glpi-project/glpi/pull/18286

The PR mentions notification templates, but it applies to almost every form.
