### ISSUE TITLE
Add custom Field to Ticket Task?

### ISSUE THREAD

**Issue by dan723** [pluginsGLPI/fields#86]
I would like to add a custom field to a ticket task, it would be very useful.

Thanks

**Comment by dan723** [comment]
I would like to add a custom field to a ticket task, it would be very useful.

Thanks

**Comment by dan723** [comment]
Hi,
Any idea if it will be possible in a future release?
Thanks a lot

**Comment by trasher** [comment]
This is not planned yet; I do not really have enough time to work on this right now.

**Comment by dan723** [comment]
Ok, thanks

**Comment by dan723** [comment]
Hi, 
Is this feature planned? 
It would be the last thing to complete the implementation of GLPI.
Thanks

**Comment by stonebuzz** [comment]
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Comment by EC2311** [comment]
Hi @stonebuzz 
It's very sorry not to have possibility to add fields on tickets tasks [version fields : 1.12.8]
