### ISSUE TITLE
No Delete Button after Upgrade

### ISSUE THREAD

**Issue by RainerAuva** [pluginsGLPI/fields#873]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### GLPI Version

10.0.17

### Plugin version

1.21.16

### Bug description

After update there is no button for delete blocks or fields. Only the Save-Button is visible.

### Page URL

https://server/plugins/fields/front/field.form.php?id=395

### Your GLPI setup information

GLPI 10.0.17 ( => C:\inetpub\glpi)
Installation mode: TARBALL
Current language:de_DE

Operating system: Windows NT Server 10.0 build 17763 (Windows Server 2019) AMD64
PHP 8.3.3 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	random, readline, session, soap, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" disable_functions="" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
Server Software: mariadb.org binary distribution
	Server Version: 10.11.6-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_connect@xxxxxx/glpi
	Host info: xxxxxxxx via TCP/IP
	
PHP version (8.3.3) is supported.PHP version (8.3.3) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.11.6) is supported.Database engine version (10.11.6) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\inetpub\glpi/files/_cache has been validated. Write access to C:\inetpub\glpi/files/_cron has been validated. Write access to C:\inetpub\glpi/files has been validated. Write access to C:\inetpub\glpi/files/_dumps has been validated. Write access to C:\inetpub\glpi/files/_graphs has been validated. Write access to C:\inetpub\glpi/files/_lock has been validated. Write access to C:\inetpub\glpi/files/_pictures has been validated. Write access to C:\inetpub\glpi/files/_plugins has been validated. Write access to C:\inetpub\glpi/files/_rss has been validated. Write access to C:\inetpub\glpi/files/_sessions has been validated. Write access to C:\inetpub\glpi/files/_tmp has been validated. Write access to C:\inetpub\glpi/files/_uploads has been validated.Write access to C:\inetpub\glpi/files/_cache has been validated.
Write access to C:\inetpub\glpi/files/_cron has been validated.
Write access to C:\inetpub\glpi/files has been validated.
Write access to C:\inetpub\glpi/files/_dumps has been validated.
Write access to C:\inetpub\glpi/files/_graphs has been validated.
Write access to C:\inetpub\glpi/files/_lock has been validated.
Write access to C:\inetpub\glpi/files/_pictures has been validated.
Write access to C:\inetpub\glpi/files/_plugins has been validated.
Write access to C:\inetpub\glpi/files/_rss has been validated.
Write access to C:\inetpub\glpi/files/_sessions has been validated.
Write access to C:\inetpub\glpi/files/_tmp has been validated.
Write access to C:\inetpub\glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.Web server root directory configuration seems safe.
Sessions configuration is secured.Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\glpi/marketplace has been validated.Write access to C:\inetpub\glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by RainerAuva** [comment]
![image](https://github.com/user-attachments/assets/2547c94b-5453-4910-b3e9-38e97dedec4c)

**Comment by stonebuzz** [comment]
Hi @RainerAuva 

Its' a GLPI issue (already fixed but not released yet)

Just apply this -> https://github.com/glpi-project/glpi/pull/18286
