### ISSUE TITLE
Add field into specific tab, does not show asset list.

### ISSUE THREAD

**Issue by boedyirh** [pluginsGLPI/fields#874]
Add Field into specific tab, In associated items doest not list asset (computer, monitor,etc ) But it shows Administration and entities.

![image](https://github.com/user-attachments/assets/8aff99e2-09ce-4cdf-a568-4478da86015c)

**Comment by stonebuzz** [comment]
Hi @boedyirh 

can you post here related field configuration?

Best regards

**Comment by cconard96** [comment]
Not a bug.
There were only a few itemtypes that supported this mode, and since GLPI 10 only Entity remains supported.

See #118 and #741
