### ISSUE TITLE
Error when deleting entries in dust bin

### ISSUE THREAD

**Issue by xsgoodbox** [pluginsGLPI/fields#9]
Hello, I got this error in assets, doing:
→ Show deleted items
→ Action(s), "Delete permanently *"

` Fatal error: Class 'PluginFieldsComputer4jscomputerfields' not found in /var/www/html/glpi09/plugins/fields/inc/container.class.php on line 270`

What can we do ?

Thanks in advance, 
have a good night!

**Comment by xsgoodbox** [comment]
This seems to be a duplicate of:
 https://github.com/pluginsGLPI/fields/issues/3

**Comment by awiamo** [comment]
I've the same problem. I can't permanently delete items from trash. When I turn off the plugin, the items are deleted without problems. 

The item 35 is in the trash
-> click the computer/item
http://myglpi.tld/front/computer.form.php?id=35
-> click 'Delete Permanently' button
http://myglpi.tld/front/computer.form.php - (empty page)
item 35 still exist
