### ISSUE TITLE
Change associated items

### ISSUE THREAD

**Issue by trasher** [pluginsGLPI/fields#93]
Actually, you can select linked items types when creating a new block, but you can't change once it has been created.

**Comment by Djiock** [comment]
Hello !
I second this, that would be very helpfull !
Thanks

**Comment by Djiock** [comment]
Hi !
Sorry to write again but as I wrote about a year ago this would be very useful... Any chance to have it implemented within the next months ?

Thanks very much

**Comment by stonebuzz** [comment]
Hi

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
